<?php
/**
 * 权限定义配置文件
 */
return array(
    //超级管理员,所有权限
    "administrator" => array(
        "homepage",
        "monitor",
            "task","current_job","history_job",
            "alarm","task_alarm","system_alarm",
            "log","job_log","system_log",
            "report","vm_report","storage_report",
        "vmprotect",
            "vm_overview",
            "vmbackup",
            "vmrecover",
            "vminstantrecover",
            "vmrecovera",
            "vmdata",
        
        "dbtiming",
            "dbtbackup",
            "dbtrecovery",
            "dbtdata",
            "dbtagent",
            "dbtstorage",
            // "dbtlog",
        
        "dbprotect",
            "dbcdpbackup",
            "dbdataRecovery",
            "dbdata",
            "dbhost",
        "fileprotect",
            "filebackup",
            "filerecover",
            "filedata",
            "agent","agent_manager","my_agent",
        "datacopy",
            "vmcopy",
            "vmcopyback",
            "vmcopydata",
       "data_archive",
            "archive_add",
            "archive_back",
            "archive_data",
//         "orch",
//             "orch_environment",
//             "orch_plan",
//             "orch_task",
//             "orch_report",
        "resmanagement",
            "vcenter_manager",
            "appliance_manager",
//             "node_manager",
            "storage_manager",
//             "storage_lanfree",
            "global_strategy",
        "sysmanagement",
            "setting_manager",
            "users",
            "authorization_module"
    ),
    
    //审计员
    "auditor" => array(
        "homepage",
        "monitor",
            "alarm","task_alarm","system_alarm",
            "log","job_log","system_log",
            "report","storage_report","vm_report",
    ),
    
    
    
    //管理员
    "manager" => array(
        "homepage",
        "monitor",
            "task","current_job","history_job",
            "alarm","task_alarm","system_alarm",
            "log","job_log","system_log",
            "report","vm_report","storage_report",
        "vmprotect",
            "vm_overview",
            "vmbackup",
            "vmrecover",
            "vminstantrecover",
            "vmrecovera",
            "vmdata",
        "dbtiming",
            "dbtbackup",
            "dbtrecovery",
            "dbtdata",
            "dbtagent",
            "dbtstorage",
            // "dbtlog",
        "dbprotect",
            "dbcdpbackup",
            "dbdataRecovery",
            "dbdata",
            "dbhost",
        "fileprotect",
            "filebackup",
            "filerecover",
            "filedata",
            "agent","agent_manager","my_agent",
        "datacopy",
            "vmcopy",
            "vmcopyback",
            "vmcopydata",
        "data_archive",
            "archive_add",
            "archive_back",
            "archive_data",
//         "orch",
//             "orch_environment",
//             "orch_plan",
//             "orch_task",
//             "orch_report",
        "resmanagement",
            "vcenter_manager",
            "appliance_manager",
//             "node_manager",
            "storage_manager",
//             "storage_lanfree",
            "global_strategy",
        "sysmanagement",
            "setting_manager",
            "users",
            "authorization_module"
    ),
    
    //操作员
    "operator" => array(
        "homepage",
        "monitor",
            "task","current_job","history_job",
            "alarm","task_alarm","system_alarm",
            "log","job_log","system_log",
            "report","vm_report","storage_report",
        "vmprotect",
            "vm_overview",
            "vmbackup",
            "vmrecover",
            "vminstantrecover",
            "vmrecovera",
            "vmdata",
        "dbtiming",
            "dbtbackup",
            "dbtrecovery",
            "dbtdata",
            "dbtagent",
            "dbtstorage",
            // "dbtlog",
        "dbprotect",
            "dbcdpbackup",
            "dbdataRecovery",
            "dbdata",
            "dbhost",
        "datacopy",
            "vmcopy",
            "vmcopyback",
            "vmcopydata",
        "data_archive",
            "archive_add",
            "archive_back",
            "archive_data",
    	"fileprotect",
    		"filebackup",
    		"filerecover",
    		"filedata",
    		"agent","my_agent",
//     	"orch",
//     		"orch_environment",
//     		"orch_plan",
//     		"orch_task",
//     		"orch_report",
        "resmanagement",
            "vcenter_manager",
            "appliance_manager",
//             "node_manager",
//             "storage_manager",
//             "storage_lanfree",
            "global_strategy",
    ),
    
    //标准版admin用户权限
    "admin" => array(
        "homepage",
        "monitor",
            "task","current_job","history_job",
            "alarm","task_alarm","system_alarm",
            "log","job_log","system_log",
            "report","vm_report","storage_report",
        "vmprotect",
            "vm_overview",
            "vmbackup",
            "vmrecover",
            "vminstantrecover",
            "vmdata",
        "resmanagement",
            "vcenter_manager",
            "appliance_manager",
//             "node_manager",
            "storage_manager",
//             "storage_lanfree",
            "global_strategy",
        "sysmanagement",
            "setting_manager",
            "authorization_module"
    ),

);

