<?php

return [
    'AGENT_PACKAGE_TYPE' => [
        'UNKNOWN' => 0,
        'AGENT_PACKAGE_TYPE_REDHAT_5' => 1,
        'AGENT_PACKAGE_TYPE_REDHAT_6' => 2,
        'AGENT_PACKAGE_TYPE_ORACLE_6' => 3,
        'AGENT_PACKAGE_TYPE_REDHAT_7' => 4,
        'AGENT_PACKAGE_TYPE_ORACLE_7' => 5,
        'AGENT_PACKAGE_TYPE_ANOLIS_7' => 6,
        'AGENT_PACKAGE_TYPE_REDOS' => 7,
        'AGENT_PACKAGE_TYPE_REDHAT_8' => 8,
        'AGENT_PACKAGE_TYPE_ANOLIS_8' => 9,
        'AGENT_PACKAGE_TYPE_ROCKY_8' => 10,
        'AGENT_PACKAGE_TYPE_OPENEULER' => 11,
        'AGENT_PACKAGE_TYPE_OPENEULER_ARM' => 12,
        'AGENT_PACKAGE_TYPE_ORACLE_8' => 13,
        'AGENT_PACKAGE_TYPE_REDHAT_9' => 14,
        'AGENT_PACKAGE_TYPE_ORACLE_9' => 15,
        'AGENT_PACKAGE_TYPE_ROCKY_9' => 16,
        'AGENT_PACKAGE_TYPE_UOS' => 17,
        'AGENT_PACKAGE_TYPE_UOS_ARM' => 18,
        'AGENT_PACKAGE_TYPE_KYLIN' => 19,
        'AGENT_PACKAGE_TYPE_KYLIN_ARM' => 20,
        'AGENT_PACKAGE_TYPE_NFSCHINA' => 21,
        'AGENT_PACKAGE_TYPE_SUSE' => 22,
        'AGENT_PACKAGE_TYPE_DEBIAN' => 23,
        'AGENT_PACKAGE_TYPE_UBUNTU' => 24,
        'AGENT_PACKAGE_TYPE_ASTRA' => 25,
        'AGENT_PACKAGE_TYPE_WINDOWS' => 26,
    ],
    'AGENT_PACKAGE_TYPE_MAP' => [
        'UNKNOWN',
        'RHEL5',
        'RHEL6',
        'ORACLELINUX6',
        'RHEL7',
        5 => 'ORACLELINUX7',
        'ANOLIS7OSX64',
        'REDOS',
        'RHEL8',
        'ANOLIS8OSX64',
        10 => 'ROCKYLINUX8',
        'EulerX86',
        'EulerAARCH64',
        'ORACLELINUX8',
        'RHEL9',
        15 => 'ORACLELINUX9',
        'ROCKYLINUX9',
        'UNIONTECHX86',
        'UNIONTECH',
        'KYLINX86',
        20 => 'KYLIN',
        'ZKFD-V4',
        'SUSE',
        'DEBIAN',
        'UBUNTU',
        25 => 'ASTRALINUX',
        'WINDOWS',
    ],
];
