<?php
/*******************************************
 ** 任务日志描述配置信息
 **
 ** @author       xiezhuowei@vinchin.com
 ** @date         2015-06-06 下午15:16:44
 ** @version      1.0.0
 ** @copyright    Copyright 2015 vinchin.com
 ********************************************/

return array(
    //***************PF*******************//
    "BD_TASKLOG_DESC_KEY_CREATE_TASK_SUCCESS" => Xphp::$_lang['WEB_LOG_TASK_CREATE_TASK_SUCCESS'],
    "BD_TASKLOG_DESC_KEY_CREATE_TASK_FAILURE" => Xphp::$_lang['WEB_LOG_TASK_CREATE_TASK_FAILURE'],
    "BD_TASKLOG_DESC_KEY_START_TASK_SUCCESS" => Xphp::$_lang['WEB_LOG_TASK_START_TASK_SUCCESS'],
    "BD_TASKLOG_DESC_KEY_START_TASK_FAILURE" => Xphp::$_lang['WEB_LOG_TASK_START_TASK_FAILURE'],
    "BD_TASKLOG_DESC_KEY_DELETE_TASK_SUCCESS" => Xphp::$_lang['WEB_LOG_TASK_DELETE_TASK_SUCCESS'],
    "BD_TASKLOG_DESC_KEY_DELETE_TASK_FAILURE" => Xphp::$_lang['WEB_LOG_TASK_DELETE_TASK_FAILURE'],
    "BD_TASKLOG_DESC_KEY_STOP_TASK_SUCCESS" => Xphp::$_lang['WEB_LOG_TASK_STOP_TASK_SUCCESS'],
    "BD_TASKLOG_DESC_KEY_STOP_TASK_FAILURE" => Xphp::$_lang['WEB_LOG_TASK_STOP_TASK_FAILURE'],
    "BD_TASKLOG_DESC_KEY_MODIFY_TASK_SUCCESS" => Xphp::$_lang['WEB_LOG_TASK_MODIFY_TASK_SUCCESS'],
    "BD_TASKLOG_DESC_KEY_MODIFY_TASK_FAILURE" => Xphp::$_lang['WEB_LOG_TASK_MODIFY_TASK_FAILURE'],
    "BD_TASKLOG_DESC_KEY_START_TASK_TIME_STRATEGY" => Xphp::$_lang['WEB_LOG_TASK_START_TASK_TIME_STRATEGY'],
    "BD_TASKLOG_DESC_KEY_START_BACKUP" => Xphp::$_lang['WEB_LOG_TASK_START_BACKUP'],
    "BD_TASKLOG_DESC_KEY_GET_BACKUP_DATA_TOTAL_SIZE" => Xphp::$_lang['WEB_LOG_TASK_GET_BACKUP_DATA_TOTAL_SIZE'],
    "BD_TASKLOG_DESC_KEY_CHECKING_BACKUP_STORAGE_SPACE" => Xphp::$_lang['WEB_LOG_TASK_CHECKING_BACKUP_STORAGE_SPACE'],
    "BD_TASKLOG_DESC_KEY_START_TRANSPORT_DATA" => Xphp::$_lang['WEB_LOG_TASK_START_TRANSPORT_DATA'],
    "BD_TASKLOG_DESC_KEY_TASK_ABNORMAL" => Xphp::$_lang['WEB_LOG_TASK_TASK_ABNORMAL'],
    "BD_TASKLOG_DESC_KEY_TASK_FAILURE" => Xphp::$_lang['WEB_LOG_TASK_TASK_FAILURE'],
    "BD_TASKLOG_DESC_KEY_TASK_SUCCESS" => Xphp::$_lang['WEB_LOG_TASK_TASK_SUCCESS'],
    "BD_TASKLOG_DESC_KEY_TASK_STOPPED" => Xphp::$_lang['WEB_LOG_TASK_TASK_STOPPED'],
    "BD_TASKLOG_DESC_KEY_START_RECOVERY" => Xphp::$_lang['WEB_LOG_TASK_START_RECOVERY'],
    "BD_TASKLOG_DESC_KEY_GET_RECOVERY_DATA_TOTAL_SIZE" => Xphp::$_lang['WEB_LOG_TASK_GET_RECOVERY_DATA_TOTAL_SIZE'],
    "BD_TASKLOG_DESC_KEY_CHECKING_RECOVERY_STORAGE_SPACE" => Xphp::$_lang['WEB_LOG_TASK_CHECKING_RECOVERY_STORAGE_SPACE'],
    "BD_TASKLOG_DESC_KEY_NEW_ROOT_IS_NOT_ENOUGH_ERROR" => Xphp::$_lang['WEB_LOG_TASK_NEW_ROOT_IS_NOT_ENOUGH_ERROR'],
    "BD_TASKLOG_DESC_KEY_TRANSPORT_DATA_SUCCESS" => Xphp::$_lang['WEB_LOG_TASK_TRANSPORT_DATA_SUCCESS'],
    "BD_TASKLOG_DESC_KEY_RETRANSPORT_DATA_SUCCESS" => Xphp::$_lang['WEB_LOG_TASK_RETRANSPORT_DATA_SUCCESS'],
    "BD_TASKLOG_DESC_KEY_TRANSPORT_TIMEOUT_WARN" => Xphp::$_lang['WEB_LOG_TASK_TRANSPORT_TIMEOUT_WARN'],
    "BD_TASKLOG_DESC_KEY_TRANSPORT_TIMEOUT_ERROR" => Xphp::$_lang['WEB_LOG_TASK_TRANSPORT_TIMEOUT_ERROR'],
    "BD_TASKLOG_DESC_KEY_TRANSPORT_DATA_FAILURE" => Xphp::$_lang['WEB_LOG_TASK_TRANSPORT_DATA_FAILURE'],
    "BD_TASKLOG_DESC_KEY_CREATING_SNAPSHOT" => Xphp::$_lang['WEB_LOG_TASK_CREATING_SNAPSHOT'],
    "BD_TASKLOG_DESC_KEY_CREATE_SNAPSHOT_FAULURE" => Xphp::$_lang['WEB_LOG_TASK_CREATE_SNAPSHOT_FAULURE'],
    "BD_TASKLOG_DESC_KEY_CLEANUP_TASK_TEMP_RESOURCE" => Xphp::$_lang['WEB_LOG_TASK_CLEANUP_TASK_TEMP_RESOURCE'],
    "BD_TASKLOG_DESC_KEY_AGENT_OFFLINE" => Xphp::$_lang['WEB_LOG_TASK_AGENT_OFFLINE'],
    "BD_TASKLOG_DESC_KEY_AGENT_NOT_AUTH" => Xphp::$_lang['WEB_LOG_TASK_AGENT_NOT_AUTH'],
    "BD_TASKLOG_DESC_KEY_STORAGE_NOT_BELONG_TO_THIS_NODE" => Xphp::$_lang['WEB_LOG_TASK_STORAGE_NOT_BELONG_TO_THIS_NODE'],
    'BD_TASKLOG_DESC_KEY_HAVE_NO_STORAGE_IN_NODE' => Xphp::$_lang['WEB_LOG_TASK_HAVE_NO_STORAGE_IN_NODE'],
    'BD_TASKLOG_DESC_KEY_STORAGE_NOT_AVAILABLE_IN_NODE' => Xphp::$_lang['WEB_LOG_TASK_STORAGE_NOT_AVAILABLE_IN_NODE'],
    'BD_TASKLOG_DESC_KEY_CHANGE_STORAGE' => Xphp::$_lang['WEB_LOG_TASK_CHANGE_STORAGE'],
    'BD_TASKLOG_DESC_KEY_REACH_QUOTA_ERROR' => Xphp::$_lang['WEB_LOG_TASK_REACH_QUOTA_ERROR'],
    'BD_TASKLOG_DESC_KEY_START_EXPORT' => Xphp::$_lang['WEB_LOG_TASK_START_EXPORT'],
    'BD_TASKLOG_DESC_KEY_STORAGE_IS_NOT_ENOUGH_ERROR' => Xphp::$_lang['WEB_LOG_TASK_STORAGE_IS_NOT_ENOUGH_ERROR'],
    "BD_TASKLOG_DESC_KEY_DELETE_SNAPSHOT" => Xphp::$_lang['WEB_LOG_TASK_DELETE_SNAPSHOT'],
    "BD_TASKLOG_DESC_KEY_DELETE_SNAPSHOT_FAULURE" => Xphp::$_lang['WEB_LOG_TASK_DELETE_SNAPSHOT_FAULURE'],
    
    
    //**************FILE******************//
    "FS_TASKLOG_DESC_KEY_RECOVERY_MK_DIR_FAILURE" => Xphp::$_lang['WEB_LOG_TASK_RECOVERY_MK_DIR_FAILURE'],
    "FS_TASKLOG_DESC_KEY_RECOVERY_OPEN_FILE_TO_WRITE_FAILURE" => Xphp::$_lang['WEB_LOG_TASK_RECOVERY_OPEN_FILE_TO_WRITE_FAILURE'],
    "FS_TASKLOG_DESC_KEY_FILE_TOO_LONG" => Xphp::$_lang['WEB_LOG_TASK_FILE_TOO_LONG'],
    "FS_TASKLOG_DESC_KEY_SCAN_BACKUP_PATH" => Xphp::$_lang['WEB_LOG_TASK_SCAN_BACKUP_PATH'],
    "FS_TASKLOG_DESC_KEY_SCAN_BACKUP_PATH_FAILURE" => Xphp::$_lang['WEB_LOG_TASK_SCAN_BACKUP_PATH_FAILURE'],
    "FS_TASKLOG_DESC_KEY_BACKUP_OPEN_FILE_TO_READ_FAILURE" => Xphp::$_lang['WEB_LOG_TASK_BACKUP_OPEN_FILE_TO_READ_FAILURE'],
    "FS_TASKLOG_DESC_KEY_SCAN_FINISH" => Xphp::$_lang['WEB_LOG_TASK_FS_TASKLOG_DESC_KEY_SCAN_FINISH'],
    "FS_TASKLOG_DESC_KEY_START_AGENT_BACKUP" => Xphp::$_lang['WEB_LOG_TASK_FS_TASKLOG_DESC_KEY_START_AGENT_BACKUP'],
    "FS_TASKLOG_DESC_KEY_PASS_FILE_EXIST" => Xphp::$_lang['WEB_LOG_TASK_FS_TASKLOG_DESC_KEY_PASS_FILE_EXIST'],
    "FS_TASKLOG_DESC_KEY_LEVEL_DOWN_STORAGE" => Xphp::$_lang['WEB_LOG_TASK_FS_TASKLOG_DESC_KEY_LEVEL_DOWN_STORAGE'],
    "FS_TASKLOG_DESC_KEY_LEVEL_DOWN_NODE" => Xphp::$_lang['WEB_LOG_TASK_FS_TASKLOG_DESC_KEY_LEVEL_DOWN_NODE'],
    "FS_TASKLOG_DESC_KEY_LEVEL_DOWN_PASSWORD" => Xphp::$_lang['WEB_LOG_TASK_FS_TASKLOG_DESC_KEY_LEVEL_DOWN_PASSWORD'],
    "FS_TASKLOG_DESC_KEY_LEVEL_DOWN_DEPEND" => Xphp::$_lang['WEB_LOG_TASK_FS_TASKLOG_DESC_KEY_LEVEL_DOWN_DEPEND'],
    "FS_TASKLOG_DESC_KEY_BACKUP_AGENT_SUCCESS" => Xphp::$_lang['WEB_LOG_TASK_FS_TASKLOG_DESC_KEY_BACKUP_AGENT_SUCCESS'],
    "FS_TASKLOG_DESC_KEY_BACKUP_AGENT_ERROR" => Xphp::$_lang['WEB_LOG_TASK_FS_TASKLOG_DESC_KEY_BACKUP_AGENT_ERROR'],
    "FS_TASKLOG_DESC_KEY_START_BACKUP_AGENT" => Xphp::$_lang['WEB_LOG_TASK_FS_TASKLOG_DESC_KEY_START_BACKUP_AGENT'],
    "FS_TASKLOG_DESC_KEY_WRITE_FILE_WARNNIG" => Xphp::$_lang['WEB_LOG_TASK_FS_TASKLOG_DESC_KEY_WRITE_FILE_WARNNIG'],
    "FS_TASKLOG_DESC_KEY_LOAD_TASK_ERROR" => Xphp::$_lang['WEB_LOG_TASK_FS_TASKLOG_DESC_KEY_LOAD_TASK_ERROR'],
    "FS_TASKLOG_DESC_KEY_LOAD_CREATE_HEAD_FOLDER_ERROR" => Xphp::$_lang['WEB_LOG_TASK_FS_TASKLOG_DESC_KEY_LOAD_CREATE_HEAD_FOLDER_ERROR'],
    "FS_TASKLOG_DESC_KEY_SCAN_RECOVERY_TOTAL_SIZE_FINISH" => Xphp::$_lang['WEB_LOG_TASK_FS_TASKLOG_DESC_KEY_SCAN_RECOVERY_TOTAL_SIZE_FINISH'],
    "FS_TASKLOG_DESC_KEY_TIMEPOINT_RESERVED" => Xphp::$_lang['WEB_LOG_TASK_FS_TASKLOG_DESC_KEY_TIMEPOINT_RESERVED'],
    "FS_TASKLOG_DESC_KEY_TIMEPOINT_USED" => Xphp::$_lang['WEB_LOG_TASK_FS_TASKLOG_DESC_KEY_TIMEPOINT_USED'],

    //**************NAS******************//
    "NAS_TASKLOG_DESC_KEY_NAS_NOT_MOUNT" => Xphp::$_lang['WEB_LOG_TASK_NAS_TASKLOG_DESC_KEY_NAS_NOT_MOUNT'],


    //***************VM*******************//
    "VM_TASK_DESC_KEY_GET_BACKUP_VM_LIST" => Xphp::$_lang['WEB_LOG_TASK_GET_BACKUP_VM_LIST'],
    "VM_TASK_DESC_KEY_CHECKING_VM_BACKUP_ENVIRONMENT" => Xphp::$_lang['WEB_LOG_TASK_CHECKING_VM_BACKUP_ENVIRONMENT'],
    "VM_TASK_DESC_KEY_CONNECT_TO_VCENTER_HOST" => Xphp::$_lang['WEB_LOG_TASK_CONNECT_TO_VCENTER_HOST'],
    "VM_TASK_DESC_KEY_TAKING_SNAPSHOT_FROM_BACKUP_VM" => Xphp::$_lang['WEB_LOG_TASK_TAKING_SNAPSHOT_FROM_BACKUP_VM'],
    "VM_TASK_DESC_KEY_GET_RECOVERY_VM_LIST" => Xphp::$_lang['WEB_LOG_TASK_GET_RECOVERY_VM_LIST'],
    "VM_TASK_DESC_KEY_SELECT_RECOVERY_DATASTORE" => Xphp::$_lang['WEB_LOG_TASK_SELECT_RECOVERY_DATASTORE'],
    "VM_TASK_DESC_KEY_START_BACKUP_VM" => Xphp::$_lang['WEB_LOG_TASK_START_BACKUP_VM'],
    "VM_TASK_DESC_KEY_START_RECOVERY_VM" => Xphp::$_lang['WEB_LOG_TASK_START_RECOVERY_VM'],
    "VM_TASK_DESC_KEY_BACKUP_VM_CONFIG" => Xphp::$_lang['WEB_LOG_TASK_BACKUP_VM_CONFIG'],
    "VM_TASK_DESC_KEY_DELETE_BACKUP_SNAPSHOT" => Xphp::$_lang['WEB_LOG_TASK_DELETE_BACKUP_SNAPSHOT'],
    "VM_TASK_DESC_KEY_DELETE_LATEST_BACKUP_SNAPSHOT" => Xphp::$_lang['WEB_LOG_TASK_DELETE_LATEST_BACKUP_SNAPSHOT'],
    "VM_TASK_DESC_KEY_NETWORK_FAULT" => Xphp::$_lang['WEB_LOG_TASK_NETWORK_FAULT'],
    "VM_TASK_DESC_KEY_NETWORK_RECONNECT" => Xphp::$_lang['WEB_LOG_TASK_NETWORK_RECONNECT'],
    "VM_TASK_DESC_KEY_NETWORK_RECONNECT_SUCCESS" => Xphp::$_lang['WEB_LOG_TASK_NETWORK_RECONNECT_SUCCESS'],
    "VM_TASK_DESC_KEY_REBUILD_VM" => Xphp::$_lang['WEB_LOG_TASK_REBUILD_VM'],
    "VM_TASK_DESC_KEY_BACKUP_VM_ERROR" => Xphp::$_lang['WEB_LOG_TASK_BACKUP_VM_ERROR'],
    "VM_TASK_DESC_KEY_RECOVERY_VM_ERROR" => Xphp::$_lang['WEB_LOG_TASK_RECOVERY_VM_ERROR'],
    "VM_TASK_DESC_KEY_CONNECT_TO_DISKLIB" => Xphp::$_lang['WEB_LOG_TASK_CONNECT_TO_DISKLIB'],
    "VM_TASK_DESC_KEY_CONNECT_TO_DISKLIB_ERROR" => Xphp::$_lang['WEB_LOG_TASK_CONNECT_TO_DISKLIB_ERROR'],
    "VM_TASK_DESC_KEY_OPEN_REMOTE_DISK_ERROR" => Xphp::$_lang['WEB_LOG_TASK_OPEN_REMOTE_DISK_ERROR'],
    "VM_TASK_DESC_KEY_VM_DEGRADE_TO_FULL_BACKUP" => Xphp::$_lang['WEB_LOG_TASK_VM_DEGRADE_TO_FULL_BACKUP'],
    "VM_TASK_DESC_KEY_VM_DEGRADE_TO_NON_VALID_FULL_BACKUP" => Xphp::$_lang['WEB_LOG_TASK_VM_DEGRADE_TO_NON_VALID_FULL_BACKUP'],
    "VM_TASK_DESC_KEY_OPEN_REMOTE_DISK" => Xphp::$_lang['WEB_LOG_TASK_OPEN_REMOTE_DISK'],
    "VM_TASK_DESC_KEY_REBUILD_VM_ERROR" => Xphp::$_lang['WEB_LOG_TASK_REBUILD_VM_ERROR'],
    "VM_TASK_DESC_KEY_VM_UNSURPPORTED_BACKUP" => Xphp::$_lang['WEB_LOG_TASK_VM_UNSURPPORTED_BACKUP'],
	"VM_TASK_DESC_KEY_VM_UNSURPPORTED_RECOVERY" => Xphp::$_lang['WEB_LOG_TASK_VM_UNSURPPORTED_RECOVERY'],
    "VM_TASK_DESC_KEY_VM_BACKUP_SPACE_MAY_NOT_ENOUGH" => Xphp::$_lang['WEB_LOG_TASK_VM_BACKUP_SPACE_MAY_NOT_ENOUGH'],
    "VM_TASK_DESC_KEY_HOST_IS_NOT_AUTH_ERROR" => Xphp::$_lang['WEB_LOG_TASK_VM_DESC_KEY_HOST_IS_NOT_AUTH_ERROR'],
    "VM_TASK_DESC_KEY_STORAGE_CHANGE_WARN" => Xphp::$_lang['WEB_LOG_TASK_VM_DESC_KEY_STORAGE_CHANGE_WARN'],
    "VM_TASK_DESC_KEY_VM_IS_NOT_EXIST_ERROR" => Xphp::$_lang['WEB_LOG_TASK_VM_DESC_KEY_VM_IS_NOT_EXIST_ERROR'],
    "VM_TASK_DESC_KEY_VM_CONF_CHANGE" => Xphp::$_lang['WEB_LOG_TASK_VM_DESC_KEY_VM_CONF_CHANGE'],
    
    'VM_TASK_DESC_KEY_CREATE_INSTANT_RECOVERY_TASK' => Xphp::$_lang['WEB_LOG_TASK_CREATE_INSTANT_RECOVERY_TASK'],
    'VM_TASK_DESC_KEY_MOUNT_NFS_DATASTORE' => Xphp::$_lang['WEB_LOG_TASK_MOUNT_NFS_DATASTORE'],
    'VM_TASK_DESC_KEY_SEND_START_INSTANT_RECOVERY_MESSAGE' => Xphp::$_lang['WEB_LOG_TASK_SEND_START_INSTANT_RECOVERY_MESSAGE'],
    'VM_TASK_DESC_KEY_REBUILD_INSTANT_RECOVERY_VM' => Xphp::$_lang['WEB_LOG_TASK_REBUILD_INSTANT_RECOVERY_VM'],
    'VM_TASK_DESC_KEY_START_INSTANT_REBUILD_VM' => Xphp::$_lang['WEB_LOG_TASK_START_INSTANT_REBUILD_VM'],
    'VM_TASK_DESC_KEY_START_INSTANT_RECOVERY_SUCCESS' => Xphp::$_lang['WEB_LOG_TASK_START_INSTANT_RECOVERY_SUCCESS'],
    'VM_TASK_DESC_KEY_START_INSTANT_RECOVERY_FAILED' => Xphp::$_lang['WEB_LOG_TASK_START_INSTANT_RECOVERY_FAILED'],
    'VM_TASK_DESC_KEY_STOP_INSTANT_RECOVERY_SUCCESS' => Xphp::$_lang['WEB_LOG_TASK_STOP_INSTANT_RECOVERY_SUCCESS'],
    'VM_TASK_DESC_KEY_STOP_INSTANT_RECOVERY_FAILED' => Xphp::$_lang['WEB_LOG_TASK_STOP_INSTANT_RECOVERY_FAILED'],
    'VM_TASK_DESC_KEY_POWEROFF_INSTANT_RECOVERY_VM' => Xphp::$_lang['WEB_LOG_TASK_POWEROFF_INSTANT_RECOVERY_VM'],
    'VM_TASK_DESC_KEY_DELETE_INSTANT_RECOVERY_VM' => Xphp::$_lang['WEB_LOG_TASK_DELETE_INSTANT_RECOVERY_VM'],
    'VM_TASK_DESC_KEY_ONLINE_MOTION_SUCCESS' => Xphp::$_lang['WEB_LOG_TASK_ONLINE_MOTION_SUCCESS'],
    'VM_TASK_DESC_KEY_ONLINE_MOTION_FAILED' => Xphp::$_lang['WEB_LOG_TASK_ONLINE_MOTION_FAILED'],
    'VM_TASK_DESC_KEY_RECOVERY_BACKUP_DATA' => Xphp::$_lang['WEB_LOG_TASK_RECOVERY_BACKUP_DATA'],
    'VM_TASK_DESC_KEY_RECOVERY_CACHE_DATA' => Xphp::$_lang['WEB_LOG_TASK_RECOVERY_CACHE_DATA'],
    'VM_TASK_DESC_KEY_POWERON_MOTION_VM' => Xphp::$_lang['WEB_LOG_TASK_POWERON_MOTION_VM'],
    'VM_TASK_DESC_KEY_CLEANUP_INVALID_RESOURCE' => Xphp::$_lang['WEB_LOG_TASK_CLEANUP_INVALID_RESOURCE'],
	'VM_TASK_DESC_KEY_PREPARE_VM_BACKUP_ENVIRONMENT' => Xphp::$_lang['WEB_LOG_TASK_PREPARE_VM_BACKUP_ENVIRONMENT'],
	'VM_TASKLOG_DESC_KEY_BACKUP_VM_SUCCESS' => Xphp::$_lang['WEB_LOG_TASK_BACKUP_VM_SUCCESS'],
	'VM_TASK_DESC_KEY_GET_BACKUP_VM_LIST' => Xphp::$_lang['WEB_LOG_TASK_GET_BACKUP_VM_LIST'],
	
	//2018.8.10 new_log
	'VM_TASKLOG_DESC_KEY_VSERVER_NOT_SUPPORT_HIGH_SPEED_MODE' => Xphp::$_lang['WEB_LOG_TASK_VSERVER_NOT_SUPPORT_HIGH_SPEED_MODE'],
	'VM_TASKLOG_DESC_KEY_VSERVER_VDISKS_NOT_IN_SAME_TYPE_SR' => Xphp::$_lang['WEB_LOG_TASK_VSERVER_VDISKS_NOT_IN_SAME_TYPE_SR'],
	
	'FC_TASK_DESC_KEY_REMOVE_INSTANT_VM_ERROR' => Xphp::$_lang['WEB_LOG_TASK_FC_REMOVE_INSTANT_VM_ERROR'],
	'FC_TASK_DESC_KEY_REMOVE_INSTANT_DATASTORE_ERROR' => Xphp::$_lang['WEB_LOG_TASK_FC_TASK_REMOVE_INSTANT_DATASTORE_ERROR'],
	
	
	//export
	'VM_TASK_DESC_KEY_GET_EXPORT_VM_TIMEPOINT_LIST' => Xphp::$_lang['WEB_LOG_TASK_GET_EXPORT_VM_TIMEPOINT_LIST'],
	'VM_TASK_DESC_KEY_START_EXPORT_VM_TIMEPOINT' => Xphp::$_lang['WEB_LOG_TASK_START_EXPORT_VM_TIMEPOINT'],
	'VM_TASK_DESC_KEY_EXPORT_VM_TIMEPOINT_ERROR' => Xphp::$_lang['WEB_LOG_TASK_EXPORT_VM_TIMEPOINT_ERROR'],
	'VM_TASK_DESC_KEY_CURRENT_TRANSPORT_MODE' => Xphp::$_lang['WEB_LOG_TASK_CURRENT_TRANSPORT_MODE'],
	'VM_TASK_DESC_KEY_TRANSPORTING_DISK_DATA' => Xphp::$_lang['WEB_LOG_TASK_TRANSPORTING_DISK_DATA'],
	'VM_TASK_DESC_KEY_TRANSPORTING_DISK_DATA_WITHOUT_VCBT' => Xphp::$_lang['WEB_LOG_TASK_TRANSPORTING_DISK_DATA_WITHOUT_VCBT'],
	
	//new XS
	'XS_TASK_DESC_KEY_CAL_VM_BACKUP_SIZE_ERROR' => Xphp::$_lang['WEB_LOG_TASK_XS_CAL_VM_BACKUP_SIZE_ERROR'],
	'XS_TASK_DESC_KEY_TRANSFER_BACKUP_DATA_FOR_VM_ERROR' => Xphp::$_lang['WEB_LOG_TASK_XS_TRANSFER_BACKUP_DATA_FOR_VM_ERROR'],
	'XS_TASK_DESC_KEY_CREATE_CONTROL_CONNECTION_ERROR' => Xphp::$_lang['WEB_LOG_TASK_XS_CREATE_CONTROL_CONNECTION_ERROR'],
	'XS_TASK_DESC_KEY_ADD_CONTROL_CONNECTION_TO_POOL_ERROR' => Xphp::$_lang['WEB_LOG_TASK_XS_ADD_CONTROL_CONNECTION_TO_POOL_ERROR'],
	'XS_TASK_DESC_KEY_VDI_IS_NOT_AVAILABLE_ERROR' => Xphp::$_lang['WEB_LOG_TASK_XS_VDI_IS_NOT_AVAILABLE_ERROR'],
	'XS_TASK_DESC_KEY_GET_DEPEND_TIMEPOINT_CHAINS_ERROR' => Xphp::$_lang['WEB_LOG_TASK_XS_GET_DEPEND_TIMEPOINT_CHAINS_ERROR'],
	'XS_TASK_DESC_KEY_CHECK_DEPEND_DISK_VALIDITY_WARN' => Xphp::$_lang['WEB_LOG_TASK_XS_CHECK_DEPEND_DISK_VALIDITY_WARN'],
	'XS_TASK_DESC_KEY_CREATE_VM_SNAPSHOT' => Xphp::$_lang['WEB_LOG_TASK_XS_CREATE_VM_SNAPSHOT'],
	'XS_TASK_DESC_KEY_LANFREE_FAILED_CHANGE_TRANS_MODE' => Xphp::$_lang['WEB_LOG_TASK_XS_LANFREE_FAILED_CHANGE_TRANS_MODE'],
	'XS_TASK_DESC_KEY_CONNECT_TO_TARGET_IP_HOST_ERROR' => Xphp::$_lang['WEB_LOG_TASK_XS_CONNECT_TO_TARGET_IP_HOST_ERROR'],
	'XS_TASK_DESC_KEY_TEST_OPEN_VM_DISK_BY_NETWORK_ERROR' => Xphp::$_lang['WEB_LOG_TASK_XS_TEST_OPEN_VM_DISK_BY_NETWORK_ERROR'],
	'XS_TASK_DESC_KEY_TRY_TO_CONNECT_AND_TEST_VM_DISK_ERROR' => Xphp::$_lang['WEB_LOG_TASK_XS_TRY_TO_CONNECT_AND_TEST_VM_DISK_ERROR'],
	'XS_TASK_DESC_KEY_UPDATE_CONN_TIMEOUT_ERROR' => Xphp::$_lang['WEB_LOG_TASK_XS_UPDATE_CONN_TIMEOUT_ERROR'],
	'XS_TASK_DESC_KEY_TRANSFER_DISK_DATA_ERROR' => Xphp::$_lang['WEB_LOG_TASK_XS_TRANSFER_DISK_DATA_ERROR'],
	'XS_TASK_DESC_KEY_PREPARE_RECOVERY_TASK_FOR_VM_ERROR' => Xphp::$_lang['WEB_LOG_TASK_XS_PREPARE_RECOVERY_TASK_FOR_VM_ERROR'],
	'XS_TASK_DESC_KEY_CAL_RECOVERY_TASK_SIZE_ERROR' => Xphp::$_lang['WEB_LOG_TASK_XS_CAL_RECOVERY_TASK_SIZE_ERROR'],
	'XS_TASK_DESC_KEY_TRANSFER_RECOVERY_DATA_ERROR' => Xphp::$_lang['WEB_LOG_TASK_XS_TRANSFER_RECOVERY_DATA_ERROR'],
	'VM_TASK_DESC_KEY_VM_VALID_DATA_SIZE' => Xphp::$_lang['WEB_LOG_TASK_VM_VM_VALID_DATA_SIZE'],
	'OPENSTACK_TASK_DESC_KEY_ISO_ROOT_DISK_ERROR' => Xphp::$_lang['WEB_LOG_TASK_OPENSTACK_ISO_ROOT_DISK_ERROR'],
    'VM_TASK_DESC_KEY_DELETE_VM_SNAPSHOT' => Xphp::$_lang['WEB_LOG_TASK_VM_KEY_DELETE_VM_SNAPSHOT'],
	'OPENSTACK_TASK_DESC_KEY_MODIFY_PORT_MACADDR_ERROR' => Xphp::$_lang['WEB_LOG_TASK_OPENSTACK_MODIFY_PORT_MACADDR_ERROR'],
		
		

    //orch task
    'VM_TASK_DESC_KEY_BUILD_ORCH_VM_LIST' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_BUILD_ORCH_VM_LIST'],
    'VM_TASK_DESC_KEY_START_ORCH_TASK_SUCCESS' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_START_ORCH_TASK_SUCCESS'],
    'VM_TASK_DESC_KEY_START_ORCH_TASK_FAILED' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_START_ORCH_TASK_FAILED'],
    'VM_TASK_DESC_KEY_START_ORCH_VM' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_START_ORCH_VM'],
    'VM_TASK_DESC_KEY_START_ORCH_BUILD_INSTANT_RECOVERY_DATA' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_START_ORCH_BUILD_INSTANT_RECOVERY_DATA'],
    'VM_TASK_DESC_KEY_START_ORCH_VM_SUCCESS' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_START_ORCH_VM_SUCCESS'],
    'VM_TASK_DESC_KEY_START_ORCH_VM_FAILED' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_START_ORCH_VM_FAILED'],
    'VM_TASK_DESC_KEY_START_ORCH_TASK' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_START_ORCH_TASK'],
    'VM_TASK_DESC_KEY_CHECK_ORCH_ENVIRONMENT' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_CHECK_ORCH_ENVIRONMENT'],
    'VM_TASK_DESC_KEY_TOTAL_ORCH_VM_NUM' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_TOTAL_ORCH_VM_NUM'],
    'VM_TASK_DESC_KEY_ORCH_INSTANT_VM_SUCCESS' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_ORCH_INSTANT_VM_SUCCESS'],
    'VM_TASK_DESC_KEY_ORCH_VM_INSTANT_FAIL' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_ORCH_VM_INSTANT_FAIL'],
    
    
    //----------------------------xenserver backup task-------------------------------------------------------
    'XENSERVER_TASK_DESC_KEY_LOAD_BACKUP_TASK_INFO' => Xphp::$_lang['WEB_LOG_TASK_XENSERVER_LOAD_BACKUP_TASK_INFO'],
    'XENSERVER_TASK_DESC_KEY_LOAD_BACKUP_TASK_INFO_ERROR' => Xphp::$_lang['WEB_LOG_TASK_XENSERVER_LOAD_BACKUP_TASK_INFO_ERROR'],
    'XENSERVER_TASK_DESC_KEY_GET_VM_CONFIGURATION' => Xphp::$_lang['WEB_LOG_TASK_XENSERVER_GET_VM_CONFIGURATION'],
    'XENSERVER_TASK_DESC_KEY_GET_VM_CONFIGURATION_ERROR' => Xphp::$_lang['WEB_LOG_TASK_XENSERVER_GET_VM_CONFIGURATION_ERROR'],
    'XENSERVER_TASK_DESC_KEY_CREATE_QUESCE_SNAP_FAILURE' => Xphp::$_lang['WEB_LOG_TASK_XENSERVER_CREATE_QUESCE_SNAP_FAILURE'],
    'XENSERVER_TASK_DESC_KEY_CREATE_SNAP_ERROR' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_CREATE_SNAP_ERROR'],
    'XENSERVER_TASK_DESC_KEY_BEGIN_SCAN_VM_DISK' => Xphp::$_lang['WEB_LOG_TASK_XENSERVER_BEGIN_SCAN_VM_DISK'],
    'XENSERVER_TASK_DESC_KEY_BEGIN_CAL_DIFF' => Xphp::$_lang['WEB_LOG_TASK_XENSERVER_BEGIN_CAL_DIFF'],
    'XENSERVER_TASK_DESC_KEY_PRINT_VM_DISK_INFO' => Xphp::$_lang['WEB_LOG_TASK_XENSERVER_PRINT_VM_DISK_INFO'],
    'XENSERVER_TASK_DESC_KEY_SCAN_DISK_PROGRESS' => Xphp::$_lang['WEB_LOG_TASK_XENSERVER_SCAN_DISK_PROGRESS'],
    'XENSERVER_TASK_DESC_KEY_SCAN_DISK_DONE' => Xphp::$_lang['WEB_LOG_TASK_XENSERVER_SCAN_DISK_DONE'],
    'XENSERVER_TASK_DESC_KEY_SCAN_DISK_ERROR' => Xphp::$_lang['WEB_LOG_TASK_XENSERVER_SCAN_DISK_ERROR'],
    'XENSERVER_TASK_DESC_KEY_BEGIN_BACKUP_VM' => Xphp::$_lang['WEB_LOG_TASK_XENSERVER_BEGIN_BACKUP_VM'],
    'XENSERVER_TASK_DESC_KEY_OPEN_VM_DISK' => Xphp::$_lang['WEB_LOG_TASK_XENSERVER_OPEN_VM_DISK'],
    'XENSERVER_TASK_DESC_KEY_OPEN_VM_DISK_ERROR' => Xphp::$_lang['WEB_LOG_TASK_XENSERVER_OPEN_VM_DISK_ERROR'],
    'XENSERVER_TASK_DESC_KEY_BACKUP_VM_ERROR' => Xphp::$_lang['WEB_LOG_TASK_XENSERVER_BACKUP_VM_ERROR'],
    'XENSERVER_TASK_DESC_KEY_BACKUP_VM_SUCCESS' => Xphp::$_lang['WEB_LOG_TASK_XENSERVER_BACKUP_VM_SUCCESS'],
    'XENSERVER_TASK_DESC_KEY_DELETE_VM_SNAP' => Xphp::$_lang['WEB_LOG_TASK_XENSERVER_DELETE_VM_SNAP'],
    'XENSERVER_TASK_DESC_KEY_CLEANUP_TMP_RESOURCE' => Xphp::$_lang['WEB_LOG_TASK_XENSERVER_CLEANUP_TMP_RESOURCE'],
    'XENSERVER_TASK_DESC_KEY_COMPARE_VDI_IS_NOT_FOUND' => Xphp::$_lang["WEB_LOG_TASK_XENSERVER_COMPARE_VDI_IS_NOT_FOUND"],
    'XENSERVER_TASK_DESC_KEY_DISK_LEVEL_DOWN' => Xphp::$_lang["WEB_LOG_TASK_XENSERVER_DISK_LEVEL_DOWN"],
    'XENSERVER_TASK_DESC_KEY_MACHINE_LEVEL_DOWN' => Xphp::$_lang["WEB_LOG_TASK_XENSERVER_MACHINE_LEVEL_DOWN"],
    'XENSERVER_TASK_DESC_KEY_NOT_SUPPORT_QUIECESE_SNAP' => Xphp::$_lang["WEB_LOG_TASK_XENSERVER_NOT_SUPPORT_QUIECESE_SNAP"],
    'XENSERVER_TASK_DESC_KEY_NOT_SUPPORT_QUIECESE_SNAP_OP' => Xphp::$_lang["WEB_LOG_TASK_XENSERVER_NOT_SUPPORT_QUIECESE_SNAP_OP"],
    
    //----------------------------xenserver recovery task-------------------------------------------------------
    
    'XENSERVER_TASK_DESC_KEY_LOAD_RECOVERY_TASK_INFO' => Xphp::$_lang['WEB_LOG_TASK_XENSERVER_LOAD_RECOVERY_TASK_INFO'],
    'XENSERVER_TASK_DESC_KEY_LOAD_RECOVERY_TASK_INFO_ERROR' => Xphp::$_lang['WEB_LOG_TASK_XENSERVER_LOAD_RECOVERY_TASK_INFO_ERROR'],
    'XENSERVER_TASK_DESC_KEY_CAL_RECOVERY_TASK' => Xphp::$_lang['WEB_LOG_TASK_XENSERVER_CAL_RECOVERY_TASK'],
    'XENSERVER_TASK_DESC_KEY_DETECT_RECOVERY_ENV' => Xphp::$_lang['WEB_LOG_TASK_XENSERVER_DETECT_RECOVERY_ENV'],
    'XENSERVER_TASK_DESC_KEY_DETECT_RECOVERY_ENV_ERROR' => Xphp::$_lang['WEB_LOG_TASK_XENSERVER_DETECT_RECOVERY_ENV_ERROR'],
    'XENSERVER_TASK_DESC_KEY_TARGET_DISK_SMALL_ERROR' => Xphp::$_lang['WEB_LOG_TASK_XENSERVER_TARGET_DISK_SMALL_ERROR'],
    'XENSERVER_TASK_DESC_KEY_TARGET_VDI_NOT_EXIST_ERROR' => Xphp::$_lang['WEB_LOG_TASK_XENSERVER_TARGET_VDI_NOT_EXIST_ERROR'],
    'XENSERVER_TASK_DESC_KEY_CREATE_NEW_VM' => Xphp::$_lang['WEB_LOG_TASK_XENSERVER_CREATE_NEW_VM'],
    'XENSERVER_TASK_DESC_KEY_CREATE_NEW_VM_ERROR' => Xphp::$_lang['WEB_LOG_TASK_XENSERVER_CREATE_NEW_VM_ERROR'],
    'XENSERVER_TASK_DESC_KEY_POWEROFF_VM' => Xphp::$_lang['WEB_LOG_TASK_XENSERVER_POWEROFF_VM'],
    'XENSERVER_TASK_DESC_KEY_GET_TARGET_SR_INFO_ERROR' => Xphp::$_lang['WEB_LOG_TASK_XENSERVER_GET_TARGET_SR_INFO_ERROR'],
    'XENSERVER_TASK_DESC_KEY_SR_SPACE_IS_NOT_ENOUGH_ERROR' => Xphp::$_lang['WEB_LOG_TASK_XENSERVER_SR_SPACE_IS_NOT_ENOUGH_ERROR'],
    'XENSERVER_TASK_DESC_KEY_CAN_NOT_FOUND_MATCH_SR_ERROR' => Xphp::$_lang['WEB_LOG_TASK_XENSERVER_CAN_NOT_FOUND_MATCH_SR_ERROR'],
    'XENSERVER_TASK_DESC_KEY_CONNECT_TO_RPC_SERVER_WARN' => Xphp::$_lang['WEB_LOG_TASK_XENSERVER_CONNECT_TO_RPC_SERVER_WARN'],
    'XENSERVER_TASK_DESC_KEY_RPC_ERROR' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_RPC_ERROR'],
    
    'XENSERVER_TASK_DESC_KEY_CONNECT_TO_HOST' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_CONNECT_TO_HOST'],
    'XENSERVER_TASK_DESC_KEY_CONNECT_TO_HOST_ERROR' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_CONNECT_TO_HOST_ERROR'],
    'XENSERVER_TASK_DESC_KEY_CREATE_XENSERVER_SR' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_CREATE_XENSERVER_SR'],
    'XENSERVER_TASK_DESC_KEY_CREATE_XENSERVER_SR_ERROR' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_CREATE_XENSERVER_SR_ERROR'],
    'XENSERVER_TASK_DESC_KEY_DETECTED_INVALID_SR_ERROR' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_DETECTED_INVALID_SR_ERROR'],
    'XENSERVER_TASK_DESC_KEY_CONN_TO_VXEFS' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_CONN_TO_VXEFS'],
    'XENSERVER_TASK_DESC_KEY_CONN_TO_VXEFS_ERROR' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_CONN_TO_VXEFS_ERROR'],
    'XENSERVER_TASK_DESC_KEY_POWER_ON_VM' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_POWER_ON_VM'],
    'XENSERVER_TASK_DESC_KEY_POWER_ON_VM_ERROR' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_POWER_ON_VM_ERROR'],
    'XENSERVER_TASK_DESC_KEY_INSTANT_VM' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_INSTANT_VM'],
    'XENSERVER_TASK_DESC_KEY_LOAD_MIGRATION_INFO' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_LOAD_MIGRATION_INFO'],
    'XENSERVER_TASK_DESC_KEY_LOAD_MIGRATION_INFO_ERROR' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_LOAD_MIGRATION_INFO_ERROR'],
    'XENSERVER_TASK_DESC_KEY_CAL_MIGRATION_SIZE' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_CAL_MIGRATION_SIZE'],
    'XENSERVER_TASK_DESC_KEY_CAL_MIGRATION_SIZE_ERROR' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_CAL_MIGRATION_SIZE_ERROR'],
    'XENSERVER_TASK_DESC_KEY_TRANSFER_TIMEPOINT_DATA' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_TRANSFER_TIMEPOINT_DATA'],
    'XENSERVER_TASK_DESC_KEY_TRANSFER_TIMEPOINT_DATA_ERROR' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_TRANSFER_TIMEPOINT_DATA_ERROR'],
    'XENSERVER_TASK_DESC_KEY_TRANSFER_CACHE_DATA' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_TRANSFER_CACHE_DATA'],
    'XENSERVER_TASK_DESC_KEY_TRANSFER_CACHE_DATA_ERROR' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_TRANSFER_CACHE_DATA_ERROR'],
    'XENSERVER_TASK_DESC_KEY_TRANSFER_CACHE_DATA_PROGRESS' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_TRANSFER_CACHE_DATA_PROGRESS'],
    'XENSERVER_TASK_DESC_KEY_FREEZE_VM_DATA' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_FREEZE_VM_DATA'],
    'XENSERVER_TASK_DESC_KEY_FREEZE_VM_DATA_ERROR' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_FREEZE_VM_DATA_ERROR'],
    'XENSERVER_TASK_DESC_KEY_TRANSFER_DIRTY_DATA' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_TRANSFER_DIRTY_DATA'],
    'XENSERVER_TASK_DESC_KEY_TRANSFER_DIRTY_DATA_ERROR' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_TRANSFER_DIRTY_DATA_ERROR'],
    'XENSERVER_TASK_DESC_KEY_TRANSFER_META_DATA' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_TRANSFER_META_DATA'],
    'XENSERVER_TASK_DESC_KEY_TRANSFER_META_DATA_ERROR' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_TRANSFER_META_DATA_ERROR'],
    'XENSERVER_TASK_DESC_KEY_CLEANUP_MIGRATION_TEMP' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_CLEANUP_MIGRATION_TEMP'],
    'XENSERVER_TASK_DESC_KEY_MIGRATION_TASK_DONE' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_MIGRATION_TASK_DONE'],
    'XENSERVER_TASK_DESC_KEY_MIGRATION_TASK_ERROR' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_MIGRATION_TASK_ERROR'],
    'XENSERVER_TASK_DESC_KEY_BACKUP_LEVEL_CHANGE_WARN' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_BACKUP_LEVEL_CHANGE_WARN'],
    'XENSERVER_TASK_DESC_KEY_DEPEND_SNAPSHOT_NOT_EXIST' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_DEPEND_SNAPSHOT_NOT_EXIST'],
    'XENSERVER_TASK_DESC_KEY_DETECTED_OLD_VDI_UUID_ERROR' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_DETECTED_OLD_VDI_UUID_ERROR'],
    'XENSERVER_TASK_DESC_KEY_CHECK_VM_RUNNING_SNAPSHOT_MERGE' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_CHECK_VM_RUNNING_SNAPSHOT_MERGE'],
    'XENSERVER_TASK_DESC_KEY_CHECK_VM_RUNNING_SNAPSHOT_MERGE_ERROR' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_CHECK_VM_RUNNING_SNAPSHOT_MERGE_ERROR'],
    'XENSERVER_TASK_DESC_KEY_HAS_VM_RUNNING_SNAPSHOT_MERGE_ERROR' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_HAS_VM_RUNNING_SNAPSHOT_MERGE_ERROR'],
	'XENSERVER_TASK_DESC_KEY_CONNECT_TO_POOL_OR_SERVER_ERROR' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_CONNECT_TO_POOL_OR_SERVER_ERROR'],
    
    //--------------------------------------------------- KVM -----------------------------------------------------
    
    'KVM_TASK_DESC_KEY_PREPARE_BACKUP_TASK_FOR_VM_ERROR' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_PREPARE_BACKUP_TASK_FOR_VM_ERROR'],
    'KVM_TASK_DESC_KEY_CREATE_SNAPSHOT_ERROR' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_CREATE_SNAPSHOT_ERROR'],
    'KVM_TASK_DESC_KEY_CAL_BACKUP_VM_SIZE_ERROR' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_CAL_BACKUP_VM_SIZE_ERROR'],
    'KVM_TASK_DESC_KEY_TRANSFER_BACKUP_DATA_FOR_VM_ERROR' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_TRANSFER_BACKUP_DATA_FOR_VM_ERROR'],
    'KVM_TASK_DESC_KEY_CREATE_TIMEPOINT_AND_CLEANUP_ERROR' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_CREATE_TIMEPOINT_AND_CLEANUP_ERROR'],
    'KVM_TASK_DESC_KEY_CREATE_CONTROL_CONNECTION_ERROR' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_CREATE_CONTROL_CONNECTION_ERROR'],
    'KVM_TASK_DESC_KEY_ADD_CONTROL_CONNECTION_TO_POOL_ERROR' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_ADD_CONTROL_CONNECTION_TO_POOL_ERROR'],
    'KVM_TASK_DESC_KEY_GET_VM_CONF_ERROR' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_GET_VM_CONF_ERROR'],
    'KVM_TASK_DESC_KEY_GET_VERSION_ERROR' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_GET_VERSION_ERROR'],
    'KVM_TASK_DESC_KEY_NOT_SUPPORT_HIGH_SPEED_MODE_WARN' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_NOT_SUPPORT_HIGH_SPEED_MODE_WARN'],
    'KVM_TASK_DESC_KEY_BACKUP_LEVEL_DOWN_WARN' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_BACKUP_LEVEL_DOWN_WARN'],
    'KVM_TASK_DESC_KEY_DISK_IS_NOT_QCOW2_ERROR' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_DISK_IS_NOT_QCOW2_ERROR'],
    'KVM_TASK_DESC_KEY_INC_DEPEND_TIMEPOINT_NOT_EXIST_ERROR' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_INC_DEPEND_TIMEPOINT_NOT_EXIST_ERROR'],
    'KVM_TASK_DESC_KEY_DIFF_DEPEND_TIMEPOINT_NOT_EXIST_ERROR' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_DIFF_DEPEND_TIMEPOINT_NOT_EXIST_ERROR'],
    'KVM_TASK_DESC_KEY_GET_DEPEND_TIMEPOINT_CHAINS_ERROR' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_GET_DEPEND_TIMEPOINT_CHAINS_ERROR'],
    'KVM_TASK_DESC_KEY_BACKUP_LEVEL_CHANGE_WARN' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_KVM_BACKUP_LEVEL_CHANGE_WARN'],
    'KVM_TASK_DESC_KEY_BACKUP_VM_DISK_NUM_CHANGE_WARN' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_BACKUP_VM_DISK_NUM_CHANGE_WARN'],
    'KVM_TASK_DESC_KEY_GET_DISK_BACKING_STORE_ERROR' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_GET_DISK_BACKING_STORE_ERROR'],
    'KVM_TASK_DESC_KEY_CHECK_DEPEND_TIMEPOINT_VALIDITY_WARN' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_CHECK_DEPEND_TIMEPOINT_VALIDITY_WARN'],
    'KVM_TASK_DESC_KEY_CHECK_DEPEND_DISK_VALIDITY_WARN' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_CHECK_DEPEND_DISK_VALIDITY_WARN'],
    'KVM_TASK_DESC_KEY_ALLOCATE_BACKUP_FILE_ID_ERROR' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_ALLOCATE_BACKUP_FILE_ID_ERROR'],
    'KVM_TASK_DESC_KEY_CREATE_SNAPSHOT' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_CREATE_SNAPSHOT'],
    'KVM_TASK_DESC_KEY_CREATE_FAKE_TIMEPOINT_INFO_ERROR' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_CREATE_FAKE_TIMEPOINT_INFO_ERROR'],
    'KVM_TASK_DESC_KEY_TRANSFER_DISK_DATA' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_TRANSFER_DISK_DATA'],
    'KVM_TASK_DESC_KEY_DELETE_BACKUP_SNAPSHOT' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_KVM_DELETE_BACKUP_SNAPSHOT'],
    'KVM_TASK_DESC_KEY_BEGIN_MERGE_SNAPSHOT_DISK' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_BEGIN_MERGE_SNAPSHOT_DISK'],
    'KVM_TASK_DESC_KEY_MERGE_SNAPSHOT_DISK_PROGRESS' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_MERGE_SNAPSHOT_DISK_PROGRESS'],
    'KVM_TASK_DESC_KEY_PIVOT_ACTIVE_DISK' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_PIVOT_ACTIVE_DISK'],
    'KVM_TASK_DESC_KEY_PIVOT_ACTIVE_DISK_ERROR' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_PIVOT_ACTIVE_DISK_ERROR'],
    'KVM_TASK_DESC_KEY_DEPEND_SNAPSHOT_NOT_EXIST_ERROR' =>Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_DEPEND_SNAPSHOT_NOT_EXIST_ERROR'],
    
    //------------------------------------------ KVM Recovery Procedure ----------------------------------------
    
    'KVM_TASK_DESC_KEY_PREPARE_RECOVERY_TASK_FOR_VM_ERROR' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_PREPARE_RECOVERY_TASK_FOR_VM_ERROR'],
    'KVM_TASK_DESC_KEY_CAL_RECOVERY_TASK_SIZE_ERROR' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_CAL_RECOVERY_TASK_SIZE_ERROR'],
    'KVM_TASK_DESC_KEY_TRANSFER_RECOVERY_DATA_ERROR' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_TRANSFER_RECOVERY_DATA_ERROR'],
    'KVM_TASK_DESC_KEY_LOAD_LIMITED_OPEN_FILE_ERROR' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_LOAD_LIMITED_OPEN_FILE_ERROR'],
    'KVM_TASK_DESC_KEY_COULD_NOT_FOUND_MATCH_SR_ERROR' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_COULD_NOT_FOUND_MATCH_SR_ERROR'],
    'KVM_TASK_DESC_KEY_CREATE_VM' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_CREATE_VM'],
    'KVM_TASK_DESC_KEY_CREATE_VM_ERROR' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_CREATE_VM_ERROR'],
    'KVM_TASK_DESC_KEY_POWER_ON_VM_ERROR' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_KVM_POWER_ON_VM_ERROR'],
    'KVM_TASK_DESC_KEY_CREATE_INSTANT_RECOVERY_NFS' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_CREATE_INSTANT_RECOVERY_NFS'],
    'KVM_TASK_DESC_KEY_CREATE_INSTANT_RECOVERY_NFS_ERROR' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_CREATE_INSTANT_RECOVERY_NFS_ERROR'],
    'KVM_TASK_DESC_KEY_CONNECT_TO_KVINFS' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_CONNECT_TO_KVINFS'],
    'KVM_TASK_DESC_KEY_CONNECT_TO_KVINFS_ERROR' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_CONNECT_TO_KVINFS_ERROR'],
    'KVM_TASK_DESC_KEY_START_FILTER_DISK' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_START_FILTER_DISK'],
    'KVM_TASK_DESC_KEY_START_FILTER_DISK_ERROR' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_START_FILTER_DISK_ERROR'],
    'KVM_TASK_DESC_KEY_START_INSTANT_RECOVERY_TASK_SUCCESS' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_START_INSTANT_RECOVERY_TASK_SUCCESS'],
    'KVM_TASK_DESC_KEY_START_INSTANT_RECOVERY_TASK_ERROR' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_START_INSTANT_RECOVERY_TASK_ERROR'],
    'KVM_TASK_DESC_KEY_DELETE_INSTANT_RECOVERY_VM' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_DELETE_INSTANT_RECOVERY_VM'],
    'KVM_TASK_DESC_KEY_DELETE_INSTANT_RECOVERY_VM_ERROR' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_DELETE_INSTANT_RECOVERY_VM_ERROR'],
    'KVM_TASK_DESC_KEY_DELETE_INSTANT_RECOVERY_CACHE' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_DELETE_INSTANT_RECOVERY_CACHE'],
    'KVM_TASK_DESC_KEY_DELETE_INSTANT_RECOVERY_STORAGE' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_DELETE_INSTANT_RECOVERY_STORAGE'],
    'KVM_TASK_DESC_KEY_DELETE_INSTANT_RECOVERY_STORAGE_ERROR' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_DELETE_INSTANT_RECOVERY_STORAGE_ERROR'],
    'KVM_TASK_DESC_KEY_STOP_FILTER_DISK' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_STOP_FILTER_DISK'],
    'KVM_TASK_DESC_KEY_STOP_FILTER_DISK_ERROR' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_STOP_FILTER_DISK_ERROR'],
    'KVM_TASK_DESC_KEY_LOAD_MIGRATION_TASK_INFO' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_LOAD_MIGRATION_TASK_INFO'],
    'KVM_TASK_DESC_KEY_LOAD_MIGRATION_TASK_INFO_ERROR' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_LOAD_MIGRATION_TASK_INFO_ERROR'],
    'KVM_TASK_DESC_KEY_PREPARE_MIGRATION_TASK_INFO' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_PREPARE_MIGRATION_TASK_INFO'],
    'KVM_TASK_DESC_KEY_PREPARE_MIGRATION_TASK_INFO_ERROR' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_PREPARE_MIGRATION_TASK_INFO_ERROR'],
    'KVM_TASK_DESC_KEY_TRANSFER_BACKUP_TIMEPOINT_DISK_DATA' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_TRANSFER_BACKUP_TIMEPOINT_DISK_DATA'],
    'KVM_TASK_DESC_KEY_TRANSFER_BACKUP_TIMEPOINT_DISK_DATA_ERROR' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_TRANSFER_BACKUP_TIMEPOINT_DISK_DATA_ERROR'],
    'KVM_TASK_DESC_KEY_BEGIN_TRANSFER_CACHE_DISK_DATA' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_BEGIN_TRANSFER_CACHE_DISK_DATA'],
    'KVM_TASK_DESC_KEY_TRANSFER_CACHE_DISK_DATA_PROGRESS' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_TRANSFER_CACHE_DISK_DATA_PROGRESS'],
    'KVM_TASK_DESC_KEY_TRANSFER_CACHE_DISK_DATA_ERROR' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_TRANSFER_CACHE_DISK_DATA_ERROR'],
    'KVM_TASK_DESC_KEY_TRANSFER_CACHE_DISK_META' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_TRANSFER_CACHE_DISK_META'],
    'KVM_TASK_DESC_KEY_TRANSFER_CACHE_DISK_META_ERROR' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_TRANSFER_CACHE_DISK_META_ERROR'],
    'KVM_TASK_DESC_KEY_FREEZE_VM_DATA' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_KVM_FREEZE_VM_DATA'],
    'KVM_TASK_DESC_KEY_FREEZE_VM_DATA_ERROR' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_KVM_FREEZE_VM_DATA_ERROR'],
    'KVM_TASK_DESC_KEY_BEGIN_TRANSFER_FROZEN_CACHE_DATA' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_BEGIN_TRANSFER_FROZEN_CACHE_DATA'],
    'KVM_TASK_DESC_KEY_TRANSFER_FROZEN_CACHE_DATA_ERROR' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_TRANSFER_FROZEN_CACHE_DATA_ERROR'],
    'KVM_TASK_DESC_KEY_TRANSFER_FROZEN_CACHE_DATA_PROGRESS' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_TRANSFER_FROZEN_CACHE_DATA_PROGRESS'],
    'KVM_TASK_DESC_KEY_MIGRATION_FINISHED' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_MIGRATION_FINISHED'],
    'KVM_TASK_DESC_KEY_MIGRATION_ERROR' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_MIGRATION_ERROR'],
    'KVM_TASK_DESC_KEY_MIGRATION_STOP' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_MIGRATION_STOP'],
    'KVM_TASK_DESC_KEY_CREATE_CONN_TO_CENTER' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_CREATE_CONN_TO_CENTER'],
	'KVM_TASK_DESC_KEY_TRY_TO_HARD_POWEROFF_VM' =>Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_TRY_TO_HARD_POWEROFF_VM'],
	'KVM_TASK_DESC_KEY_CAL_DISK_BITMAP_PROGRESS' =>Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_CAL_DISK_BITMAP_PROGRESS'],
    'KVM_TASK_DESC_KEY_NOT_SUPPORT_QUIECESE_SNAP' => Xphp::$_lang['WEB_LOG_TASK_DESC_NOT_SUPPORT_QUIECESE_SNAP'],
    "KVM_TASK_DESC_KEY_ICS_NOT_SUPPORT_LANFREE_RECOVERY" => Xphp::$_lang['WEB_LOG_TASK_DESC_ICS_NOT_SUPPORT_LANFREE_RECOVERYP'],
    
    'VM_TASK_LOAD_GRAIN_RECOVERY_INFO' => Xphp::$_lang['WEB_LOG_TASK_LOAD_GRAIN_RECOVERY_INFO'],
    'VM_TASK_LOAD_GRAIN_RECOVERY_INFO_ERROR' => Xphp::$_lang['WEB_LOG_TASK_LOAD_GRAIN_RECOVERY_INFO_ERROR'],
    'VM_TASK_LAUNCH_GUEST_HANDLER' => Xphp::$_lang['WEB_LOG_TASK_LAUNCH_GUEST_HANDLER'],
    'VM_TASK_LAUNCH_GUEST_HANDLER_ERROR' => Xphp::$_lang['WEB_LOG_TASK_LAUNCH_GUEST_HANDLER_ERROR'],
    'VM_TASK_GET_TIMEPOINT_VM_INFO' => Xphp::$_lang['WEB_LOG_TASK_GET_TIMEPOINT_VM_INFO'],
    'VM_TASK_GET_TIMEPOINT_VM_INFO_ERROR' => Xphp::$_lang['WEB_LOG_TASK_GET_TIMEPOINT_VM_INFO_ERROR'],
    'VM_TASK_START_GRAIN_RECOVERY_TASK_DONE' => Xphp::$_lang['WEB_LOG_TASK_START_GRAIN_RECOVERY_TASK_DONE'],
    'VM_TASK_SHUTDOWN_GUEST_HANDLER' => Xphp::$_lang['WEB_LOG_TASK_SHUTDOWN_GUEST_HANDLER'],
    'VM_TASK_SHUTDOWN_GUEST_HANDLER_BUSSY_ERROR' => Xphp::$_lang['WEB_LOG_TASK_SHUTDOWN_GUEST_HANDLER_BUSSY_ERROR'],
    'VM_TASK_DELETE_GRAIN_TMP' => Xphp::$_lang['WEB_LOG_TASK_DELETE_GRAIN_TMP'],
    'VM_TASK_STOP_GRAIN_RECOVERY_DONE' => Xphp::$_lang['WEB_LOG_TASK_STOP_GRAIN_RECOVERY_DONE'],
	
	'BACKUP_COPY_DESC_KEY_TASK_ALREADY_EXIST' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_BACKUP_COPY_TASK_ALREADY_EXIST'],
	'BACKUP_COPY_DESC_KEY_START' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_BACKUP_COPY_START'],
	'BACKUP_COPY_DESC_KEY_GET_BACKUP_COPY_VM_LIST' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_BACKUP_COPY_GET_BACKUP_COPY_VM_LIST'],
	'BACKUP_COPY_DESC_KEY_GET_TASK_INFO' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_BACKUP_COPY_GET_TASK_INFO'],
	'BACKUP_COPY_DESC_KEY_GET_VM_INFO' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_BACKUP_COPY_GET_VM_INFO'],
	'BACKUP_COPY_DESC_KEY_NO_NEW_RESTORE_POINT_FOUND' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_BACKUP_COPY_NO_NEW_RESTORE_POINT_FOUND'],
	'BACKUP_COPY_DESC_KEY_GET_NEW_RESTORE_TIMEPOINT' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_BACKUP_COPY_GET_NEW_RESTORE_TIMEPOINT'],
	'BACKUP_COPY_DESC_KEY_TIMEPOINT_NOT_EXIST' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_BACKUP_COPY_TIMEPOINT_NOT_EXIST'],
	'BACKUP_COPY_DESC_KEY_TIMEPOINT_NOT_AVAILABLE' => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_BACKUP_COPY_TIMEPOINT_NOT_AVAILABLE'],
    'BD_SYSTEMLOG_DESC_KEY_REMOTE_STORAGE_ADD' => Xphp::$_lang['WEB_LOG_SYSTEM_REMOTE_STORAGE_ADD'],
    
	"BACKUP_COPY_DESC_KEY_VM_COPY" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_BACKUP_COPY_VM_COPY'],
	"BACKUP_COPY_DESC_KEY_TIMEPOINT_COPY" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_BACKUP_COPY_TIMEPOINT_COPY'],
	"BACKUP_COPY_DESC_KEY_COPY_TIMEPOINT_COUNT" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_BACKUP_COPY_COPY_TIMEPOINT_COUNT'],
	
	"BACKUP_COPY_FETCH_DESC_KEY_START" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_BACKUP_COPY_FETCH_START'],
	"BACKUP_COPY_FETCH_DESC_KEY_GET_VM_LIST" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_BACKUP_COPY_FETCH_GET_VM_LIST'],
	"BACKUP_COPY_FETCH_DESC_KEY_GET_TASK_INFO" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_BACKUP_COPY_FETCH_GET_TASK_INFO'],
	"BACKUP_COPY_FETCH_DESC_KEY_GET_VM_INFO" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_BACKUP_COPY_FETCH_GET_VM_INFO'],
	"BACKUP_COPY_FETCH_DESC_KEY_VM_FETCH" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_BACKUP_COPY_FETCH_VM_FETCH'],
	"BACKUP_COPY_FETCH_DESC_KEY_TIMEPOINT_FETCH" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_BACKUP_COPY_FETCH_TIMEPOINT_FETCH'],
	
    "BACKUP_COPY_DESC_KEY_DO_RETENTION" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_BACKUP_COPY_DO_RETENTION'],
    "BACKUP_COPY_DESC_KEY_MERGE_TIMEPOINT" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_BACKUP_COPY_MERGE_TIMEPOINT'],
    "BACKUP_COPY_DESC_KEY_MERGE_TIMEPOINT_ERROR" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_BACKUP_COPY_MERGE_TIMEPOINT_ERROR'],
    "BACKUP_COPY_DESC_KEY_TIMEPOINT_IS_MERGING" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_BACKUP_COPY_TIMEPOINT_IS_MERGING'],
	
	"BACKUP_COPY_DESC_KEY_PAUSE_TASK_SUCCESS" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_BACKUP_COPY_PAUSE_TASK_SUCCESS'],
	"BACKUP_COPY_FETCH_DESC_KEY_PAUSE_TASK_SUCCESS" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_BACKUP_COPY_FETCH_PAUSE_TASK_SUCCESS'],
	"BACKUP_COPY_DESC_KEY_CONTINUE_TASK" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_BACKUP_COPY_CONTINUE_TASK'],
	"BACKUP_COPY_FETCH_DESC_KEY_CONTINUE_TASK" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_BACKUP_COPY_FETCH_CONTINUE_TASK'],
	
	"BACKUP_COPY_DESC_KEY_PAUSE_TIMEPOINT" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_BACKUP_COPY_PAUSE_TIMEPOINT'],
	"BACKUP_COPY_DESC_KEY_PAUSE_VM" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_BACKUP_COPY_PAUSE_VM'],
	"BACKUP_COPY_FETCH_DESC_KEY_PAUSE_VM" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_BACKUP_COPY_FETCH_PAUSE_VM'],
	"BACKUP_COPY_FETCH_DESC_KEY_PAUSE_TIMEPOINT" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_BACKUP_COPY_FETCH_PAUSE_TIMEPOINT'],
	"BACKUP_COPY_FETCH_DESC_KEY_TIMEPOINT_ALREADY_EXIST" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_BACKUP_COPY_FETCH_TIMEPOINT_ALREADY_EXIST'],
	"BACKUP_COPY_DESC_KEY_SOURCE_BACKUP_COPY_TASK_NOT_EXIST" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_SOURCE_BACKUP_COPY_TASK_NOT_EXIST'],
	"BACKUP_COPY_DESC_KEY_TIMEPOINT_OF_TASK_NO_LONGER_EXIST" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_BACKUP_COPY_TIMEPOINT_OF_TASK_NO_LONGER_EXIST'],
    "VM_TASKLOG_DESC_KEY_DEPEND_VM_TIMEPOINT_IS_BUSY" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_DEPEND_VM_TIMEPOINT_IS_BUSY'],
	
	"BACKUP_COPY_DESC_KEY_ARCHIVE_START" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_ARCHIVE_START'],
	"BACKUP_COPY_DESC_KEY_GET_ARCHIVE_VM_LIST" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_GET_ARCHIVE_VM_LIST'],
	"BACKUP_COPY_DESC_KEY_ARCHIVE_TIMEPOINT_FOR_VM" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_ARCHIVE_TIMEPOINT_FOR_VM'],
	"BACKUP_COPY_DESC_KEY_ARCHIVE_TIMEPOINT" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_ARCHIVE_TIMEPOINT'],
	"BACKUP_COPY_DESC_KEY_ARCHIVE_PAUSE_TIMEPOINT" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_ARCHIVE_PAUSE_TIMEPOINT'],
	"BACKUP_COPY_DESC_KEY_ARCHIVE_GET_METADATA" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_ARCHIVE_GET_METADATA'],
    
    "BACKUP_COPY_DESC_KEY_ARCHIVE_TRANSFER_DATA" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_ARCHIVE_TRANSFER_DATA'],
    "BACKUP_COPY_DESC_KEY_ARCHIVE_TRANSFER_DATA_DONE" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_ARCHIVE_TRANSFER_DATA_DONE'],
    "BACKUP_COPY_DESK_KEY_ARCHIVE_TASK_STOP" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_ARCHIVE_TASK_STOP'],
    "BACKUP_COPY_DESC_KEY_ARCHIVE_FETCH_START" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_ARCHIVE_FETCH_START'],
    
    "BACKUP_COPY_DESC_KEY_ARCHIVE_FETCH_FOR_VM" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_ARCHIVE_FETCH_FOR_VM'],
    
    "BACKUP_COPY_DESC_KEY_ARCHIVE_FETCH_TIMEPOINT" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_ARCHIVE_FETCH_TIMEPOINT'],
    
    "VM_TASK_CHECK_AND_DO_RESERVED_STRATEGY" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_CHECK_AND_DO_RESERVED_STRATEGY'],
    "VM_TASK_DO_RESERVED_STRATEGY_SUCCESS" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_DO_RESERVED_STRATEGY_SUCCESS'],
    "VM_TASK_DO_RESERVED_STRATEGY_ERROR" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_DO_RESERVED_STRATEGY_ERROR'],
    
    "VM_TASK_DESC_KEY_DELETE_BACKUP_SNAPSHOT" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_DELETE_BACKUP_SNAPSHOT'],
    
    "VM_TASK_DESC_KEY_CURRENT_DISK_TRANSPORT_MODE2" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_CURRENT_DISK_TRANSPORT_MODE2'],
    "VM_TASK_DESC_KEY_CURRENT_DISK_TRANSPORT_CHANGE" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_CURRENT_DISK_TRANSPORT_CHANGE'],

    "BACKUP_COPY_DESC_KEY_GET_BACKUP_COPY_FILE_LIST" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_GET_BACKUP_COPY_FILE_LIST'],
    "BACKUP_COPY_DESC_KEY_DO_COPY_FOR_TASK" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_DO_COPY_FOR_TASK'],
    "BACKUP_COPY_DESC_KEY_GET_FETCH_FILE_LIST" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_GET_FETCH_FILE_LIST'],
    "BACKUP_COPY_FETCH_DESC_KEY_FILE_FETCH" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_FILE_FETCH'],
	
	"BACKUP_COPY_DESC_KEY_GET_ARCHIVE_TASK_INFO" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_GET_ARCHIVE_TASK_INFO'],
	"BACKUP_COPY_DESC_KEY_ARCHIVE_PREPARE_INFO" => Xphp::$_lang['WEB_LOG_TASK_DESC_ARCHIVE_PREPARE_INFO'],
	
    "KVM_TASK_DESC_KEY_CONNECT_TO_CNA_BACKUP_SERVER_IP_INFO" => Xphp::$_lang['WEB_LOG_TASK_DESC_KVM_CONNECT_TO_CNA_BACKUP_SERVER_IP_INFO'],
	
    "VM_TASK_DESC_KEY_SAVE_MACADDR_ERROR" => Xphp::$_lang['WEB_LOG_TASK_DESC_SAVE_MACADDR_ERROR'],
   
	// template: Ovirt version should be larger than 4.4.7 to enable CBT feature
	"KVM_TASK_DESC_KEY_OVIRT_CBT_NEED_VERSION_OVER_4_4_7" => Xphp::$_lang['WEB_LOG_TASK_DESC_KVM_OVIRT_CBT_NEED_VERSION_OVER_4_4_7'],
	// template: detected raw disk exist, create snapshot for vm '%s'
	"KVM_TASK_DESC_KEY_CREATE_DUMMY_SNAPSHOT_FOR_CBT" => Xphp::$_lang['WEB_LOG_TASK_DESC_KVM_CREATE_DUMMY_SNAPSHOT_FOR_CBT'],
    
	/*
	 * for new features, add by sky huang, 2021-08-18
	 */
    // template: create backup for vm '%s'
    "KVM_TASK_DESC_KEY_CREATE_OVIRT_BACKUP" => Xphp::$_lang['WEB_LOG_TASK_DESC_KVM_CREATE_OVIRT_BACKUP'],
    // template: finalize backup for vm '%s'
    "KVM_TASK_DESC_KEY_FINALIZE_OVIRT_BACKUP" => Xphp::$_lang['WEB_LOG_TASK_DESC_KVM_FINALIZE_OVIRT_BACKUP'],
    // template: create transfer for vm %s's disk '%s(%s)'
    "KVM_TASK_DESC_KEY_CREATE_OVIRT_IMAGE_TRANSFER" => Xphp::$_lang['WEB_LOG_TASK_DESC_KVM_CREATE_OVIRT_IMAGE_TRANSFER'],
    // template: finalize transfer for vm %s's disk '%s(%s)', transfer id: %s
    "KVM_TASK_DESC_KEY_FINALIZE_OVIRT_IMAGE_TRANSFER" => Xphp::$_lang['WEB_LOG_TASK_DESC_KVM_FINALIZE_OVIRT_IMAGE_TRANSFER'],
    
    // template: calculate chnage data block for '%s', method: %s
    "KVM_TASK_DESC_KEY_PRINT_KVM_BACKUP_LEVEL" => Xphp::$_lang['WEB_LOG_TASK_DESC_PRINT_KVM_BACKUP_LEVEL'],
    
    // template: vm convert license is exhaust, current job vm number is '%s', already converted vm number before is '%s', total auth license number is '%s'
    "VM_TASK_DESC_KEY_CONVERT_LIC_EXHAUST" => Xphp::$_lang['WEB_LOG_TASK_DESC_VM_CONVERT_LIC_EXHAUST'],
    
	/*------------------------------------ sure backup recovery ------------------------------------------*/
	// template: build orch vm list
	"VM_TASK_DESC_KEY_BUILD_SURE_BACKUP_VM_LIST" => Xphp::$_lang['WEB_LOG_TASK_DESC_BUILD_SURE_BACKUP_VM_LIST'],
	// template: start orch task success
	"VM_TASK_DESC_KEY_START_SURE_BACKUP_TASK_SUCCESS" => Xphp::$_lang['WEB_LOG_TASK_DESC_START_SURE_BACKUP_TASK_SUCCESS'],
	// template: start orch task failed
	"VM_TASK_DESC_KEY_START_SURE_BACKUP_TASK_FAILED" => Xphp::$_lang['WEB_LOG_TASK_DESC_START_SURE_BACKUP_TASK_FAILED'],
	// template: start orch the '%d' vm '%s'
	"VM_TASK_DESC_KEY_START_SURE_BACKUP_VM" => Xphp::$_lang['WEB_LOG_TASK_DESC_START_SURE_BACKUP_VM'],
	// template: build instant recovery data
	"VM_TASK_DESC_KEY_START_SURE_BACKUP_BUILD_INSTANT_RECOVERY_DATA" => Xphp::$_lang['WEB_LOG_TASK_DESC_START_SURE_BACKUP_BUILD_INSTANT_RECOVERY_DATA'],
	// template: start orch vm success
	"VM_TASK_DESC_KEY_START_SURE_BACKUP_VM_SUCCESS" => Xphp::$_lang['WEB_LOG_TASK_DESC_START_SURE_BACKUP_VM_SUCCESS'],
	// template: start orch vm failed
	"VM_TASK_DESC_KEY_START_SURE_BACKUP_VM_FAILED" => Xphp::$_lang['WEB_LOG_TASK_DESC_START_SURE_BACKUP_VM_FAILED'],
	// template: start orch task
	"VM_TASK_DESC_KEY_START_SURE_BACKUP_TASK" => Xphp::$_lang['WEB_LOG_TASK_DESC_START_SURE_BACKUP_TASK'],
	// template: check orch environment
	"VM_TASK_DESC_KEY_CHECK_SURE_BACKUP_ENVIRONMENT" => Xphp::$_lang['WEB_LOG_TASK_DESC_CHECK_SURE_BACKUP_ENVIRONMENT'],
	// template: the total orch vm number is '%s'
	"VM_TASK_DESC_KEY_TOTAL_SURE_BACKUP_VM_NUM" => Xphp::$_lang['WEB_LOG_TASK_DESC_TOTAL_SURE_BACKUP_VM_NUM'],
	// template: orch intant recovery  vm '%s' success 
	"VM_TASK_DESC_KEY_SURE_BACKUP_INSTANT_VM_SUCCESS" => Xphp::$_lang['WEB_LOG_TASK_DESC_SURE_BACKUP_INSTANT_VM_SUCCESS'],
	// template: orch instant recovery  vm '%s' fail
	"VM_TASK_DESC_KEY_SURE_BACKUP_VM_INSTANT_FAIL" => Xphp::$_lang['WEB_LOG_TASK_DESC_SURE_BACKUP_VM_INSTANT_FAIL'],
	"VM_TASK_DESC_KEY_POWER_ON_SURE_BACKUP_VM" => Xphp::$_lang['WEB_LOG_TASK_DESC_POWER_ON_SURE_BACKUP_VM'],
	//template:start doing ping test 
	"VM_TASK_DESC_KEY_START_PING_TEST" => Xphp::$_lang['WEB_LOG_TASK_DESC_START_PING_TEST'],
	"VM_TASK_DESC_KEY_DOING_PING_TEST" => Xphp::$_lang['WEB_LOG_TASK_DESC_DOING_PING_TEST'],
	"VM_TASK_DESC_KEY_PING_TEST_SKIP" => Xphp::$_lang['WEB_LOG_TASK_DESC_PING_TEST_SKIP'],
	"VM_TASK_DESC_KEY_PING_TEST_ERROR" => Xphp::$_lang['WEB_LOG_TASK_DESC_PING_TEST_ERROR'],
	"VM_TASK_DESC_KEY_START_SURE_BACKUP_VERIFICATION_TEST" => Xphp::$_lang['WEB_LOG_TASK_DESC_START_SURE_BACKUP_VERIFICATION_TEST'],
	"VM_TASK_DESC_KEY_SURE_BACKUP_VERIFICATION_TEST_FINISHED" => Xphp::$_lang['WEB_LOG_TASK_DESC_SURE_BACKUP_VERIFICATION_TEST_FINISHED'],
	"VM_TASK_DESC_KEY_PARAMETER_NULL" => Xphp::$_lang['WEB_LOG_TASK_DESC_PARAMETER_NULL'],
	"VM_TASK_DESC_KEY_POWER_ON_VIRTUAL_LAB" => Xphp::$_lang['WEB_LOG_TASK_DESC_POWER_ON_VIRTUAL_LAB'],
	"VM_TASK_DESC_KEY_START_SCREENSHOT_TEST" => Xphp::$_lang['WEB_LOG_TASK_DESC_START_SCREENSHOT_TEST'],
	"VM_TASK_DESC_KEY_DOING_SCREENSHOT_TEST" => Xphp::$_lang['WEB_LOG_TASK_DESC_DOING_SCREENSHOT_TEST'],
	"VM_TASK_DESC_KEY_SCREENSHOT_TEST_SKIP" => Xphp::$_lang['WEB_LOG_TASK_DESC_SCREENSHOT_TEST_SKIP'],
	"VM_TASK_DESC_KEY_SCREENSHOT_TEST_ERROR" => Xphp::$_lang['WEB_LOG_TASK_DESC_SCREENSHOT_TEST_ERROR'],
	"VM_TASK_DESC_KEY_REBUILD_INSTANT_SURE_BACKUP_RECOVERY_VM" => Xphp::$_lang['WEB_LOG_TASK_DESC_REBUILD_INSTANT_SURE_BACKUP_RECOVERY_VM'],
	
    "VM_TASK_DESC_KEY_GET_INSTANT_INFO_FOR_SURE_BACKUP" => Xphp::$_lang['WEB_LOG_TASK_DESC_GET_INSTANT_INFO_FOR_SURE_BACKUP'],
    "VM_TASK_DESC_KEY_GET_SURE_BACKUP_VM_INFO" => Xphp::$_lang['WEB_LOG_TASK_DESC_GET_SURE_BACKUP_VM_INFO'],
    "VM_TASK_DESC_KEY_CONNECT_TO_VCENTER_HOST" => Xphp::$_lang['WEB_LOG_TASK_DESC_CONNECT_TO_VCENTER_HOST'],
    "VM_TASK_DESC_KEY_MOUNT_NFS_DATASTORE" => Xphp::$_lang['WEB_LOG_TASK_DESC_MOUNT_NFS_DATASTORE'],
    "VM_TASK_DESC_KEY_PING_TEST_SUCCESS" => Xphp::$_lang['WEB_LOG_TASK_DESC_PING_TEST_SUCCESS'],
    "VM_TASK_DESC_KEY_START_HEARTBEAT_TEST" => Xphp::$_lang['WEB_LOG_TASK_DESC_START_HEARTBEAT_TEST'],
    "VM_TASK_DESC_KEY_HEARTBEAT_TEST_SUCCESS" => Xphp::$_lang['WEB_LOG_TASK_DESC_HEARTBEAT_TEST_SUCCESS'],
    "VM_TASK_DESC_KEY_HEARTBEAT_TEST_ERROR" => Xphp::$_lang['WEB_LOG_TASK_DESC_HEARTBEAT_TEST_ERROR'],
    "VM_TASK_DESC_KEY_HEARTBEAT_TEST_SKIP" => Xphp::$_lang['WEB_LOG_TASK_DESC_HEARTBEAT_TEST_SKIP'],
    "VM_TASK_DESC_KEY_SCREENSHOT_TEST_SUCCESS" => Xphp::$_lang['WEB_LOG_TASK_DESC_SCREENSHOT_TEST_SUCCESS'],
    "VM_TASK_DESC_KEY_SURE_BACKUP_VM_FINISHED" => Xphp::$_lang['WEB_LOG_TASK_DESC_SURE_BACKUP_VM_FINISHED'],
    "VM_TASK_DESC_KEY_FINISHING_SURE_BACKUP_TASK" => Xphp::$_lang['WEB_LOG_TASK_DESC_FINISHING_SURE_BACKUP_TASK'],  
    "VM_TASK_DESC_KEY_SURE_BACKUP_TASK_DONE" => Xphp::$_lang['WEB_LOG_TASK_DESC_SURE_BACKUP_TASK_DONE'],
	
	//template sure backup ping test describe no ip address
	"VM_TASK_DESC_KEY_PING_TEST_ERROR_NO_IP_ADDRESS" => Xphp::$_lang['WEB_LOG_TASK_DESC_PING_TEST_ERROR_NO_IP_ADDRESS'],
	//template sure backup ping test describe cannot ping throught the ip 
	"VM_TASK_DESC_KEY_PING_TEST_ERROR_CANNOT_PING_THROUGH_ADDRESS" => Xphp::$_lang['WEB_LOG_TASK_DESC_PING_TEST_ERROR_CANNOT_PING_THROUGH_ADDRESS'],
	
	//template: start cross platform driver replacement
	"VM_TASKLOG_DESC_KEY_START_DRIVER_REPLACEMENT" => Xphp::$_lang['WEB_LOG_TASK_DESC_VM_START_DRIVER_REPLACEMENT'],
	//template: driver replacement appliance vm is '%s'( '%s')
	"VM_TASKLOG_DESC_KEY_CHOOSE_APPLIANCE" => Xphp::$_lang['WEB_LOG_TASK_DESC_VM_CHOOSE_APPLIANCE'],
	
	"VM_TASK_DESC_KEY_SURE_BACKUP_VM_START" => Xphp::$_lang['WEB_LOG_TASK_DESC_SURE_BACKUP_VM_START'],
	
	"VM_TASK_DESC_KEY_TURN_OFF_VIRTUAL_LAB" => Xphp::$_lang['WEB_LOG_TASK_DESC_TURN_OFF_VIRTUAL_LAB'],  //关闭虚拟实验室
	"VM_TASK_DESC_KEY_TURN_OFF_SURE_BACKUP_VM" => Xphp::$_lang['WEB_LOG_TASK_DESC_TURN_OFF_SURE_BACKUP_VM'], //关闭数据验证虚拟机{参数1：虚拟机名}
	"VM_TASK_DESC_KEY_DELETE_SURE_BACKUP_VM"  => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_DELETE_SURE_BACKUP_VM'],
    "VM_TASK_DESC_KEY_VIRTUAL_LAB_MODIFY_ERROR" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_VIRTUAL_LAB_MODIFY_ERROR'],
	
	
	//--------------------------------------------------- DB -----------------------------------------------------
	"DB_TASK_DESC_KEY_GET_BACKUP_DB_LIST" => Xphp::$_lang['WEB_LOG_TASK_DB_GET_BACKUP_DB_LIST'],
	"DB_TASK_DESC_KEY_PREPARE_DB_BACKUP_ENVIRONMENT" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_DB_PREPARE_DB_BACKUP_ENVIRONMENT'],
	"DB_TASK_DESC_KEY_GET_RECOVERY_DB_LIST" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_DB_GET_RECOVERY_DB_LIST'],
	"DB_TASK_DESC_KEY_START_BACKUP_DB" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_DB_START_BACKUP_DB'],
	"DB_TASK_DESC_KEY_START_RECOVERY_DB" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_DB_START_RECOVERY_DB'],
	"DB_TASK_DESC_KEY_BACKUP_DB_ERROR" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_DB_BACKUP_DB_ERROR'],
	"DB_TASK_DESC_KEY_RECOVERY_DB_ERROR" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_DB_RECOVERY_DB_ERROR'],
	"DB_TASK_CHECK_AND_DO_RESERVED_STRATEGY" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_DB_CHECK_AND_DO_RESERVED_STRATEGY'],
	"DB_TASK_DO_RESERVED_STRATEGY_ERROR" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_DB_DO_RESERVED_STRATEGY_ERROR'],
	"DB_TASK_DESC_KEY_CLIENT_IS_NOT_AUTH_ERROR" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_DB_CLIENT_IS_NOT_AUTH_ERROR'],
	"DB_TASK_DESC_KEY_DB_UNSURPPORTED_BACKUP" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_DB_UNSURPPORTED_BACKUP'],
	"DB_TASK_DESC_KEY_DB_DEGRADE_TO_FULL_BACKUP" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_DB_DEGRADE_TO_FULL_BACKUP'],
	"DB_TASKLOG_DESC_KEY_BACKUP_DB_SUCCESS" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_DB_BACKUP_DB_SUCCESS'],
	"DB_TASKLOG_DESC_KEY_RECOVERY_DB_SUCCESS" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_DB_RECOVERY_DB_SUCCESS'],
	"DB_TASK_DESC_KEY_CHECK_DATABASE" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_DB_CHECK_DATABASE'],
	"DB_TASK_DESC_KEY_SET_DATABASE_RECOVERY_MODE_AS_FULL" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_DB_SET_DATABASE_RECOVERY_MODE_AS_FULL'],
	"DB_TASK_DESC_KEY_BACKUP_DB_FILE_CONFIG" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_DB_BACKUP_DB_FILE_CONFIG'],
	"DB_TASK_DESC_KEY_CREATE_AND_OPEN_REMOTE_VIRTUAL_DEVICE" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_DB_CREATE_AND_OPEN_REMOTE_VIRTUAL_DEVICE'],
	"DB_TASK_DESC_KEY_RECOVERY_FULL_TIMEPOINT" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_DB_RECOVERY_FULL_TIMEPOINT'],
	"DB_TASK_DESC_KEY_RECOVERY_DIFF_TIMEPOINT" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_DB_RECOVERY_DIFF_TIMEPOINT'],
	"DB_TASK_DESC_KEY_RECOVERY_LOG_TIMEPOINT" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_DB_RECOVERY_LOG_TIMEPOINT'],
	"DB_TASK_DESC_KEY_TRANSPORTING_DATA" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_DB_TRANSPORTING_DATA'],
	"DB_TASK_DESC_KEY_SET_MULTI_USER_FOR_DATABASE" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_DB_SET_MULTI_USER_FOR_DATABASE'],
	"DB_TASK_DESC_KEY_SET_SINGLE_USER_FOR_DATABASE" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_DB_SET_SINGLE_USER_FOR_DATABASE'],
	"DB_TASK_DESC_KEY_NEW_DB_DATA_FILE_NAME" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_DB_NEW_DB_DATA_FILE_NAME'],
	"DB_TASK_DESC_KEY_NEW_DB_LOG_FILE_NAME" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_DB_NEW_DB_LOG_FILE_NAME'],
	"DB_TASK_DESC_KEY_DELETE_DATABASE" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_DB_DELETE_DATABASE'],
    //-------------------------------------------oracle add--------------------------------------------------//
    // template: check archive log mode
    "DB_TASK_DESC_KEY_CHECK_ARCHIVE_LOG_MODE_OPEN" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_DB_CHECK_ARCHIVE_LOG_MODE_OPEN'],
    // template: '%s' not open archive log mode error, error code: '%s'
    "DB_TASK_DESC_KEY_ARCHIVE_LOG_MODE_NOT_OPEN_ERROR" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_DB_ARCHIVE_LOG_MODE_NOT_OPEN_ERROR'],
    // template: open block change tracking
    "DB_TASK_DESC_KEY_OPEN_BLOCK_CHANGE_TRACKING" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_DB_OPEN_BLOCK_CHANGE_TRACKING'],
    // template: delete recently '%s' day's archive log
    "DB_TASK_DESC_KEY_DELETE_ARCHIVE_LOG" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_DB_DELETE_ARCHIVE_LOG'],
    // template: record archive log sequence num
    "DB_TASK_DESC_KEY_RECORD_ARCHIVE_LOG_SEQUENCE_NUM" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_DB_RECORD_ARCHIVE_LOG_SEQUENCE_NUM'],
    //-------------------------------------------mysql add---------------------------------------------------//
    // template: backup binlog file name '%s'
    "DB_TASK_DESC_KEY_MYSQL_BINLOG_NAME" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_DB_MYSQL_BINLOG_NAME'],
    // template: data has been already in base of tmp dir
    "DB_TASK_DESC_KEY_MYSQL_DATA_IS_ALREADY" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_DB_MYSQL_DATA_IS_ALREADY'],
    // template: trasfer and prepare timepoint '%s'
    "DB_TASK_DESC_KEY_RECOVERY_MYSQL_RECOVERY_TIMEPOINT" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_DB_RECOVERY_MYSQL_RECOVERY_TIMEPOINT'],//正在传输和准备备份点:%s
    // template: redirect dir tip
    "DB_TASK_DESC_KEY_RECOVERY_MYSQL_REDIRECT_DIR" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_DB_RECOVERY_MYSQL_REDIRECT_DIR'], //提示重定向目录后相关操作
    
    // template: exec backup cmd
    "DB_TASK_DESC_KEY_BACKUP_DM_EXEC_CMD" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_DB_BACKUP_DM_EXEC_CMD'],
    // template: init channel uuid success
    "DB_TASK_DESC_KEY_DM_INIT_CHAANEL_UUID_SUCCESS" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_DB_DM_INIT_CHAANEL_UUID_SUCCESS'],
    // template: restore start
    "DB_TASK_DESC_KEY_DM_RESTORE_START" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_DB_DM_RESTORE_START'],
    // template: recover start 
    "DB_TASK_DESC_KEY_DM_RECOVER_START" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_DB_DM_RECOVER_START'],
    // template: update db_mgic
    "DB_TASK_DESC_KEY_DM_UPDATE_DB_MGIC" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_DB_DM_UPDATE_DB_MGIC'],
    
    // template: backup data file
    "DB_TASK_DESC_KEY_BACKUP_DATA_FILE" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_DB_BACKUP_DATA_FILE'],
    // template: backup spfile
    "DB_TASK_DESC_KEY_BACKUP_SPFILE" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_DB_BACKUP_SPFILE'],
    // template: backup control file
    "DB_TASK_DESC_KEY_BACKUP_CONTROL_FILE" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_DB_BACKUP_CONTROL_FILE'],
    // template: recovery spfile
    "DB_TASK_DESC_KEY_RECOVERY_SPFILE" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_DB_RECOVERY_SPFILE'],
    // template: recovery control file
    "DB_TASK_DESC_KEY_RECOVERY_CONTROL_FILE" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_DB_RECOVERY_CONTROL_FILE'],
    // template: recovery data file
    "DB_TASK_DESC_KEY_RECOVERY_DATA_FILE" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_DB_RECOVERY_DATA_FILE'],
    
    // template: connect database '%s' error,error code:'%s'
    "DB_TASK_DESC_KEY_CONNECT_DATABASE_ERROR" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_DB_CONNECT_DATABASE_ERROR'],
    // template: open block change tracking error,bct_file_name:'%s', error code:'%s'
    "DB_TASK_DESC_KEY_OPEN_BLOCK_CHANGE_TRACKING_ERROR"  => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_DB_OPEN_BLOCK_CHANGE_TRACKING_ERROR'],
    // template: connect to agent error,agent ip:'%s', error code:'%s'
    "DB_TASK_DESC_KEY_CONNECT_AGENT_ERROR" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_DB_CONNECT_AGENT_ERRORR'],
    
    // template: trasfer and prepare timepoint
    "DB_TASK_DESC_KEY_RECOVERY_MYSQL_PREPARING" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_DB_RECOVERY_MYSQL_PREPARING'],          //准备数据中
    // template: write to log
    "DB_TASK_DESC_KEY_RECOVERY_MYSQL_WRITE_TO_LOG" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_DB_RECOVERY_MYSQL_WRITE_TO_LOG'],       //写入日志中
    
    "DB_TASK_DESC_KEY_DM_RESTORE_LOG_START"  => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_DB_DM_RESTORE_LOG_START'],       //开始还原日志文件
    
    // template: dir not empty : dir '%s'
    "DB_TASK_DESC_KEY_MYSQL_DIR_NOT_EMPTY"  => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_DB_MYSQL_DIR_NOT_EMPTY'],              //目录不为空
    
    // template: connect mysql db error
    "DB_TASK_DESC_KEY_CONNECT_MYSQL_ERROR" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_DB_CONNECT_MYSQL_ERROR'],            //连接mysql实例失败
    
    // template: database current recovery mode is '%s'
    "DB_TASK_DESC_KEY_RECOVERY_MODE" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_DB_RECOVERY_MODE'],
    
    // template: bulk logged recovery mode can't support recover to a certain point in time,need set recovery mode as full
    "DB_TASK_DESC_KEY_BULK_LOGGED_RECOVERY_MODE" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_DB_BULK_LOGGED_RECOVERY_MODE'],
        
    // template: simple recovery mode can't support log backup,need set recovery mode as full
    "DB_TASK_DESC_KEY_SIMPLE_RECOVERY_MODE" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_DB_SIMPLE_RECOVERY_MODE'],
        
    // template: set database recovery mode as '%s'
    "DB_TASK_DESC_KEY_SET_RECOVERY_MODE" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_DB_SET_RECOVERY_MODE'],
    
    
    //-------------------------------------------psql add---------------------------------------------------//
    // template: backup start
    "DB_TASK_DESC_KEY_PSQL_START_BACKUP" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_DB_PSQL_START_BACKUP'],
    // template: backup success
    "DB_TASK_DESC_KEY_PSQL_BACKUP_SUCCESS" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_DB_PSQL_BACKUP_SUCCESS'],
    
    // template: backup log start
    "DB_TASK_DESC_KEY_PSQL_BACKUP_LOG_START" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_DB_PSQL_BACKUP_LOG_START'],
    // template: backup log success
    "DB_TASK_DESC_KEY_PSQL_BACKUP_LOG_SUCCESS" =>  Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_DB_PSQL_BACKUP_LOG_SUCCESS'],
    // template: restore
    "DB_TASK_DESC_KEY_PSQL_RECOVERY_START" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_DB_PSQL_RECOVERY_START'],
    // template: restore success
    "DB_TASK_DESC_KEY_PSQL_RECOVERY_SUCCESS" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_DB_PSQL_RECOVERY_SUCCESS'],
    // template: restore log
    "DB_TASK_DESC_KEY_PSQL_RECOVERY_LOG_START" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_DB_PSQL_RECOVERY_LOG_START'],
    // template: restore log success
    "DB_TASK_DESC_KEY_PSQL_RECOVERY_LOG_SUCCESS" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_DB_PSQL_RECOVERY_LOG_SUCCESS'],
    
	// template: restore wal log 
	"DB_TASK_DESC_KEY_PSQL_RESTORE_WAL_LOG" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_PSQL_RESTORE_WAL_LOG'],
	// template: need delete wal log
	"DB_TASK_DESC_KEY_PSQL_NEED_DELETE_WAL_LOG" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_PSQL_NEED_DELETE_WAL_LOG'],

	// template: storage space alarm
	"DB_TASK_DESC_KEY_PSQL_STORAGE_ALARM_ERROR" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_PSQL_STORAGE_ALARM_ERROR'],
	
	"DB_TASK_DESC_KEY_PSQL_WAIT_FOR_ARCHIVING_SUCCESS" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_PSQL_WAIT_FOR_ARCHIVING_SUCCESS'],
	
	"DB_TASK_DESC_KEY_DM_UPDATE_DB_MAGIC" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_DM_UPDATE_DB_MAGIC'],
	
    //WEB
    'WEB_TASKLOG_DESC_KEY_MODIFY_TASK_SUCCESS' => Xphp::$_lang['WEB_LOG_TASK_MODIFY_TASK_SUCCESS'],
	
    
    //-------------------------------------------OS---------------------------------------------------//
    
    
    //backup
    'OS_TASK_DESC_KEY_GET_BACKUP_OS_LIST' => Xphp::$_lang['WEB_TASK_DESC_KEY_GET_BACKUP_OS_LIST'],
    'OS_TASK_DESC_KEY_START_BACKUP_OS' => Xphp::$_lang['WEB_TASK_DESC_KEY_START_BACKUP_OS'],
    'OS_TASK_DESC_KEY_PREPARE_OS_BACKUP_ENVIRONMENT' => Xphp::$_lang['WEB_TASK_DESC_KEY_PREPARE_OS_BACKUP_ENVIRONMENT'],
    'OS_TASK_CHECK_AND_DO_RESERVED_STRATEGY' => Xphp::$_lang['WEB_TASK_CHECK_AND_DO_RESERVED_STRATEGY'],
    'OS_TASK_DESC_KEY_OS_DEGRADE_TO_FULL_BACKUP' => Xphp::$_lang['WEB_TASK_DESC_KEY_OS_DEGRADE_TO_FULL_BACKUP'],
    'OS_TASK_DESC_KEY_START_BACKUP_DISK' => Xphp::$_lang['WEB_TASK_DESC_KEY_START_BACKUP_DISK'],
    'OS_TASK_DESC_KEY_BACKUP_DISK_END' => Xphp::$_lang['WEB_TASK_DESC_KEY_BACKUP_DISK_END'],
    'OS_TASK_DESC_KEY_CREATE_SNAPSHOT' => Xphp::$_lang['WEB_TASK_DESC_KEY_CREATE_SNAPSHOT'],
    'OS_TASK_DESC_KEY_START_BACKUP_PARTITION' => Xphp::$_lang['WEB_TASK_DESC_KEY_START_BACKUP_PARTITION'],
    'OS_TASKLOG_DESC_KEY_BACKUP_PARTITION_SUCCESS' => Xphp::$_lang['WEB_TASKLOG_DESC_KEY_BACKUP_PARTITION_SUCCESS'],
    'OS_TASKLOG_DESC_KEY_BACKUP_OS_SUCCES' => Xphp::$_lang['WEB_TASKLOG_DESC_KEY_BACKUP_OS_SUCCES'],
    'OS_TASK_DESC_KEY_DELETE_SNAPSHOT' => Xphp::$_lang['WEB_TASK_DESC_KEY_DELETE_SNAPSHOT'],
    'OS_TASK_DESC_KEY_BACKUP_OS_SUCCESS' => Xphp::$_lang['WEB_TASK_DESC_KEY_BACKUP_OS_SUCCESS'],
    'OS_TASK_DESC_KEY_BACKUP_PARTITION_SUCCESS' => Xphp::$_lang['WEB_TASK_DESC_KEY_BACKUP_PARTITION_SUCCESS'],
    'OS_TASK_DESC_KEY_REPARTED_PARTITION' => Xphp::$_lang['WEB_TASK_DESC_KEY_REPARTED_PARTITION'],
    'OS_TASK_DESC_KEY_CHECK_AND_CLEAN_SNAPSHOT' => Xphp::$_lang['WEB_TASK_DESC_KEY_CHECK_AND_CLEAN_SNAPSHOT'],
    'OS_TASK_DESC_KEY_GET_PARTITION_BITMAP' => Xphp::$_lang['WEB_TASK_DESC_KEY_GET_PARTITION_BITMAP'],
    'OS_TASK_DESC_KEY_LINUX_CAN_NOT_GET_VALID_DATA' => Xphp::$_lang['WEB_TASK_DESC_KEY_LINUX_CAN_NOT_GET_VALID_DATA'],
    
    //recovery
    'OS_TASK_DESC_KEY_GET_RECOVERY_OS_LIST' => Xphp::$_lang['WEB_TASK_DESC_KEY_GET_RECOVERY_OS_LIST'],
    'OS_TASK_DESC_KEY_START_RECOVERY_OS' => Xphp::$_lang['WEB_TASK_DESC_KEY_START_RECOVERY_OS'],
    'OS_TASK_DESC_KEY_OS_UNSURPPORTED_RECOVERY' => Xphp::$_lang['WEB_TASK_DESC_KEY_OS_UNSURPPORTED_RECOVERY'],
    'OS_TASK_DESC_KEY_RECOVERY_PARTITION' => Xphp::$_lang['WEB_TASK_DESC_KEY_RECOVERY_PARTITION'],
    'OS_TASK_DESC_KEY_RECOVERY_PARTITION_SUCCESS' => Xphp::$_lang['WEB_TASK_DESC_KEY_RECOVERY_PARTITION_SUCCESS'],
    'OS_TASK_DESC_KEY_RECOVERY_OS_SUCCESS' => Xphp::$_lang['WEB_TASK_DESC_KEY_RECOVERY_OS_SUCCESS'],
    'OS_TASK_DESC_KEY_REPAIR_MBR' => Xphp::$_lang['WEB_TASK_DESC_KEY_REPAIR_MBR'],
    'OS_TASK_DESC_KEY_REPAIR_GPT' => Xphp::$_lang['WEB_TASK_DESC_KEY_REPAIR_GPT'],
    'OS_TASK_DESC_KEY_REPAIR_FSTAB' => Xphp::$_lang['WEB_TASK_DESC_KEY_REPAIR_FSTAB'],
    'OS_TASK_DESC_KEY_REPAIR_GRUB_CFG' => Xphp::$_lang['WEB_TASK_DESC_KEY_REPAIR_GRUB_CFG'],
    'OS_TASK_DESC_KEY_REPAIR_GRUB_CFG_ERROR' => Xphp::$_lang['WEB_TASK_DESC_KEY_REPAIR_GRUB_CFG_ERROR'],
    'OS_TASK_DESC_KEY_REPAIR_FSTAB_ERROR' => Xphp::$_lang['WEB_TASK_DESC_KEY_REPAIR_FSTAB_ERROR'],
    'OS_TASK_DESC_KEY_CREATE_SWAP_VOLUME_ERROR' => Xphp::$_lang['WEB_TASK_DESC_KEY_CREATE_SWAP_VOLUME_ERROR'],
    
    //error
    'OS_TASK_DESC_KEY_BACKUP_OS_ERROR' => Xphp::$_lang['WEB_TASK_DESC_KEY_BACKUP_OS_ERROR'],
    'OS_TASK_DESC_KEY_RECOVERY_OS_ERROR' => Xphp::$_lang['WEB_TASK_DESC_KEY_RECOVERY_OS_ERROR'],
    'OS_TASK_DESC_KEY_DO_RESERVED_STRATEGY_ERROR' => Xphp::$_lang['WEB_TASK_DESC_KEY_DO_RESERVED_STRATEGY_ERROR'],
    
    //------------------------------------------volume CDP ---------------------------------------------//

    'VOL_CDP_LOG_DESC_KEY_START_BACKUP' => Xphp::$_lang['WEB_TASK_VOL_CDP_LOG_DESC_KEY_START_BACKUP'],
    'VOL_CDP_LOG_DESC_KEY_START_RESTORE' => Xphp::$_lang['WEB_TASK_VOL_CDP_LOG_DESC_KEY_START_RESTORE'],
    'VOL_CDP_LOG_DESC_KEY_START_TAKEOVER' => Xphp::$_lang['WEB_TASK_VOL_CDP_LOG_DESC_KEY_START_TAKEOVER'],
    'VOL_CDP_LOG_DESC_KEY_START_FAILBACK' => Xphp::$_lang['WEB_TASK_VOL_CDP_LOG_DESC_KEY_START_FAILBACK'],
    'VOL_CDP_LOG_DESC_KEY_STOP_BACKUP' => Xphp::$_lang['WEB_TASK_VOL_CDP_LOG_DESC_KEY_STOP_BACKUP'],
    'VOL_CDP_LOG_DESC_KEY_STOP_RESTORE' => Xphp::$_lang['WEB_TASK_VOL_CDP_LOG_DESC_KEY_STOP_RESTORE'],
    'VOL_CDP_LOG_DESC_KEY_STOP_TAKEOVER' => Xphp::$_lang['WEB_TASK_VOL_CDP_LOG_DESC_KEY_STOP_TAKEOVER'],
    'VOL_CDP_LOG_DESC_KEY_START_INIT_SYNC' => Xphp::$_lang['WEB_TASK_VOL_CDP_LOG_DESC_KEY_START_INIT_SYNC'],
    'VOL_CDP_LOG_DESC_KEY_START_REALTIME_SYNC' => Xphp::$_lang['WEB_TASK_VOL_CDP_LOG_DESC_KEY_START_REALTIME_SYNC'],
    'VOL_CDP_LOG_DESC_KEY_START_FAILBACK_INIT_SYNC' => Xphp::$_lang['WEB_TASK_VOL_CDP_LOG_DESC_KEY_START_FAILBACK_INIT_SYNC'],
    'VOL_CDP_LOG_DESC_KEY_START_FAILBACK_REALTIME_SYNC' => Xphp::$_lang['WEB_TASK_VOL_CDP_LOG_DESC_KEY_START_FAILBACK_REALTIME_SYNC'],
    'VOL_CDP_LOG_DESC_KEY_INIT_SYNC_SUCCESSED' => Xphp::$_lang['WEB_TASK_VOL_CDP_LOG_DESC_KEY_INIT_SYNC_SUCCESSED'],
    'VOL_CDP_LOG_DESC_KEY_INIT_SYNC_FAILED' => Xphp::$_lang['WEB_TASK_VOL_CDP_LOG_DESC_KEY_INIT_SYNC_FAILED'],
    'VOL_CDP_LOG_DESC_KEY_FAILBACK_INIT_SYNC_SUCCESSED' => Xphp::$_lang['WEB_TASK_VOL_CDP_LOG_DESC_KEY_FAILBACK_INIT_SYNC_SUCCESSED'],
    'VOL_CDP_LOG_DESC_KEY_FAILBACK_INIT_SYNC_FAILED' => Xphp::$_lang['WEB_TASK_VOL_CDP_LOG_DESC_KEY_FAILBACK_INIT_SYNC_FAILED'],
    'VOL_CDP_LOG_DESC_KEY_BACKUP_EXECUTION_FAILED' => Xphp::$_lang['WEB_TASK_VOL_CDP_LOG_DESC_KEY_BACKUP_EXECUTION_FAILED'],
    'VOL_CDP_LOG_DESC_KEY_RESTORE_EXECUTION_SUCCESSED' => Xphp::$_lang['WEB_TASK_VOL_CDP_LOG_DESC_KEY_RESTORE_EXECUTION_SUCCESSED'],
    'VOL_CDP_LOG_DESC_KEY_RESTORE_EXECUTION_FAILED' => Xphp::$_lang['WEB_TASK_VOL_CDP_LOG_DESC_KEY_RESTORE_EXECUTION_FAILED'],
    'VOL_CDP_LOG_DESC_KEY_TAKEOVER_EXECUTION_SUCCESSED' => Xphp::$_lang['WEB_TASK_VOL_CDP_LOG_DESC_KEY_TAKEOVER_EXECUTION_SUCCESSED'],
    'VOL_CDP_LOG_DESC_KEY_TAKEOVER_EXECUTION_FAILED' => Xphp::$_lang['WEB_TASK_VOL_CDP_LOG_DESC_KEY_TAKEOVER_EXECUTION_FAILED'],
    
    'VOL_CDP_LOG_DESC_KEY_NOTIFY_MASTER_PERFORM_INITIALIZATION' =>Xphp::$_lang['WEB_VOL_CDP_LOG_DESC_KEY_NOTIFY_MASTER_PERFORM_INITIALIZATION'],
    'VOL_CDP_LOG_DESC_KEY_NOTIFY_STANDBY_PERFORM_INITIALIZATION' =>Xphp::$_lang['WEB_VOL_CDP_LOG_DESC_KEY_NOTIFY_STANDBY_PERFORM_INITIALIZATION'],
    'VOL_CDP_LOG_DESC_KEY_MASTER_INITIALIZATIOIN_SUCCESSED' =>Xphp::$_lang['WEB_VOL_CDP_LOG_DESC_KEY_MASTER_INITIALIZATIOIN_SUCCESSED'],
    'VOL_CDP_LOG_DESC_KEY_MASTER_INITIALIZATIOIN_FAILED' =>Xphp::$_lang['WEB_VOL_CDP_LOG_DESC_KEY_MASTER_INITIALIZATIOIN_FAILED'],
    'VOL_CDP_LOG_DESC_KEY_STANDBY_INITIALIZATIOIN_SUCCESSED' =>Xphp::$_lang['WEB_VOL_CDP_LOG_DESC_KEY_STANDBY_INITIALIZATIOIN_SUCCESSED'],
    'VOL_CDP_LOG_DESC_KEY_STANDBY_INITIALIZATIOIN_FAILED' =>Xphp::$_lang['WEB_VOL_CDP_LOG_DESC_KEY_STANDBY_INITIALIZATIOIN_FAILED'],
    
    'VOL_CDP_LOG_DESC_KEY_NOTIFY_MASTER_PERFORM_INITIALIZATION' => Xphp::$_lang['WEB_TASK_VOL_CDP_LOG_DESC_KEY_NOTIFY_MASTER_PERFORM_INITIALIZATION'],
    'VOL_CDP_LOG_DESC_KEY_NOTIFY_STANDBY_PERFORM_INITIALIZATION' =>  Xphp::$_lang['WEB_TASK_VOL_CDP_LOG_DESC_KEY_NOTIFY_STANDBY_PERFORM_INITIALIZATION'],
    'VOL_CDP_LOG_DESC_KEY_MASTER_INITIALIZATIOIN_SUCCESSED' => Xphp::$_lang['WEB_TASK_VOL_CDP_LOG_DESC_KEY_MASTER_INITIALIZATIOIN_SUCCESSED'],
    'VOL_CDP_LOG_DESC_KEY_MASTER_INITIALIZATIOIN_FAILED' => Xphp::$_lang['WEB_TASK_VOL_CDP_LOG_DESC_KEY_MASTER_INITIALIZATIOIN_FAILED'],
    'VOL_CDP_LOG_DESC_KEY_STANDBY_INITIALIZATIOIN_SUCCESSED' => Xphp::$_lang['WEB_TASK_VOL_CDP_LOG_DESC_KEY_STANDBY_INITIALIZATIOIN_SUCCESSED'],
    
    'VOL_CDP_LOG_DESC_KEY_BACKUP_STOPPED_COMPLETE' => Xphp::$_lang['WEB_TASK_VOL_CDP_LOG_DESC_KEY_BACKUP_STOPPED_COMPLETE'],
    'VOL_CDP_LOG_DESC_KEY_RESTORE_STOPPED_COMPLETE' => Xphp::$_lang['WEB_TASK_VOL_CDP_LOG_DESC_KEY_RESTORE_STOPPED_COMPLETE'],
    'VOL_CDP_LOG_DESC_KEY_TAKEOVER_STOPPED_COMPLETE' => Xphp::$_lang['WEB_TASK_VOL_CDP_LOG_DESC_KEY_TAKEOVER_STOPPED_COMPLETE'],
    'VOL_CDP_LOG_DESC_KEY_TASK_TYPE_IS_NOT_BACKUP_OR_TAKEOVER' => Xphp::$_lang['WEB_TASK_VOL_CDP_LOG_DESC_KEY_TASK_TYPE_IS_NOT_BACKUP_OR_TAKEOVER'],
    'VOL_CDP_LOG_DESC_KEY_TASK_IS_NOT_IN_TAKEOVER_STAGE' => Xphp::$_lang['WEB_TASK_VOL_CDP_LOG_DESC_KEY_TASK_IS_NOT_IN_TAKEOVER_STAGE'],
    'VOL_CDP_LOG_DESC_KEY_TASK_IS_NOT_IN_SUCCESSED_STATUS' => Xphp::$_lang['WEB_TASK_VOL_CDP_LOG_DESC_KEY_TASK_IS_NOT_IN_SUCCESSED_STATUS'],
    'VOL_CDP_LOG_DESC_KEY_TASK_READ_CONFIG_INFO_SUCCESSED' => Xphp::$_lang['WEB_TASK_VOL_CDP_LOG_DESC_KEY_TASK_READ_CONFIG_INFO_SUCCESSED'],
    'VOL_CDP_LOG_DESC_KEY_TASK_READ_CONFIG_INFO_FAILED' => Xphp::$_lang['WEB_TASK_VOL_CDP_LOG_DESC_KEY_TASK_READ_CONFIG_INFO_FAILED'],
    'VOL_CDP_LOG_DESC_KEY_TASK_CREATE_EXECUTE_CHILD_PROCESS_SUCCESSED' => Xphp::$_lang['WEB_TASK_VOL_CDP_LOG_DESC_KEY_TASK_CREATE_EXECUTE_CHILD_PROCESS_SUCCESSED'],
    'VOL_CDP_LOG_DESC_KEY_TASK_CREATE_EXECUTE_CHILD_PROCESS_FAILED' => Xphp::$_lang['WEB_TASK_VOL_CDP_LOG_DESC_KEY_TASK_CREATE_EXECUTE_CHILD_PROCESS_FAILED'],
    'CONFIGUR_CDP_TAKEOVER_FAILBACK_TASK_SUCCESSED' => Xphp::$_lang['WEB_TASK_CONFIGUR_CDP_TAKEOVER_FAILBACK_TASK_SUCCESSED'],
    'VOL_CDP_LOG_DESC_KEY_AGENT_TO_HANDSHAKE' => Xphp::$_lang['WEB_TASK_VOL_CDP_LOG_DESC_KEY_AGENT_TO_HANDSHAKE'],
    'VOL_CDP_LOG_DESC_KEY_AGENT_HANDSHAKE_SUCCESSED' => Xphp::$_lang['WEB_TASK_VOL_CDP_LOG_DESC_KEY_AGENT_HANDSHAKE_SUCCESSED'],
    'VOL_CDP_LOG_DESC_KEY_AGENT_HANDSHAKE_FAILED' => Xphp::$_lang['WEB_TASK_VOL_CDP_LOG_DESC_KEY_AGENT_HANDSHAKE_FAILED'],
    'VOL_CDP_LOG_DESC_KEY_AGENT_TO_CREATE_SNAPSHOT' => Xphp::$_lang['WEB_TASK_VOL_CDP_LOG_DESC_KEY_AGENT_TO_CREATE_SNAPSHOT'],
    'VOL_CDP_LOG_DESC_KEY_AGENT_CREATE_SNAPSHOT_SUCCESSED' => Xphp::$_lang['WEB_TASK_VOL_CDP_LOG_DESC_KEY_AGENT_CREATE_SNAPSHOT_SUCCESSED'],
    'VOL_CDP_LOG_DESC_KEY_AGENT_CREATE_SNAPSHOT_FAILED' => Xphp::$_lang['WEB_TASK_VOL_CDP_LOG_DESC_KEY_AGENT_CREATE_SNAPSHOT_FAILED'],
    'VOL_CDP_LOG_DESC_KEY_AGENT_DELETE_SNAPSHOT_SUCCESSED' => Xphp::$_lang['WEB_TASK_VOL_CDP_LOG_DESC_KEY_AGENT_DELETE_SNAPSHOT_SUCCESSED'],
    'VOL_CDP_LOG_DESC_KEY_AGENT_DELETE_SNAPSHOT_FAILED' => Xphp::$_lang['WEB_TASK_VOL_CDP_LOG_DESC_KEY_AGENT_DELETE_SNAPSHOT_FAILED'],
    'VOL_CDP_LOG_DESC_KEY_AGENT_TO_INIT_CACHE' => Xphp::$_lang['WEB_TASK_VOL_CDP_LOG_DESC_KEY_AGENT_TO_INIT_CACHE'],
    'VOL_CDP_LOG_DESC_KEY_AGENT_INIT_CACHE_SUCCESSED' => Xphp::$_lang['WEB_TASK_VOL_CDP_LOG_DESC_KEY_AGENT_INIT_CACHE_SUCCESSED'],
    'VOL_CDP_LOG_DESC_KEY_AGENT_INIT_CACHE_FAILED' => Xphp::$_lang['WEB_TASK_VOL_CDP_LOG_DESC_KEY_AGENT_INIT_CACHE_FAILED'],
    'VOL_CDP_LOG_DESC_KEY_AGENT_TO_START_MONITOR' => Xphp::$_lang['WEB_TASK_VOL_CDP_LOG_DESC_KEY_AGENT_TO_START_MONITOR'],
    'VOL_CDP_LOG_DESC_KEY_AGENT_START_MONITOR_SUCCESS' => Xphp::$_lang['WEB_TASK_VOL_CDP_LOG_DESC_KEY_AGENT_START_MONITOR_SUCCESS'],
    'VOL_CDP_LOG_DESC_KEY_AGENT_START_MONITOR_FAILED' => Xphp::$_lang['WEB_TASK_VOL_CDP_LOG_DESC_KEY_AGENT_START_MONITOR_FAILED'],
    'VOL_CDP_LOG_DESC_KEY_AGENT_STOP_MONITOR_SUCCESSED' => Xphp::$_lang['WEB_TASK_VOL_CDP_LOG_DESC_KEY_AGENT_STOP_MONITOR_SUCCESSED'],
    'VOL_CDP_LOG_DESC_KEY_AGENT_STOP_MONITOR_FAILED' => Xphp::$_lang['WEB_TASK_VOL_CDP_LOG_DESC_KEY_AGENT_STOP_MONITOR_FAILED'],
    'VOL_CDP_LOG_DESC_KEY_INIT_STORAGE_RESOURCES_SUCCESSED' => Xphp::$_lang['WEB_TASK_VOL_CDP_LOG_DESC_KEY_INIT_STORAGE_RESOURCES_SUCCESSED'],
    'VOL_CDP_LOG_DESC_KEY_INIT_STORAGE_RESOURCES_FAILED' => Xphp::$_lang['WEB_TASK_VOL_CDP_LOG_DESC_KEY_INIT_STORAGE_RESOURCES_FAILED'],
    'VOL_CDP_LOG_DESC_DETECTED_AGENT_NET_FAULT' => Xphp::$_lang['WEB_TASK_VOL_CDP_LOG_DESC_DETECTED_AGENT_NET_FAULT'],
    'VOL_CDP_LOG_DESC_DETECTED_AGENT_NET_BACKUP_TO_NORMAL' => Xphp::$_lang['WEB_TASK_VOL_CDP_LOG_DESC_DETECTED_AGENT_NET_BACKUP_TO_NORMAL'],
    'VOL_CDP_LOG_DESC_TASK_CHANGE_STATUS_FROM_RUNNING_TO_NET_FAULT' => Xphp::$_lang['WEB_TASK_VOL_CDP_LOG_DESC_TASK_CHANGE_STATUS_FROM_RUNNING_TO_NET_FAULT'],
    'VOL_CDP_LOG_DESC_TASK_CHNAGE_STATUS_FROM_NET_FAULT_TO_RUNNING' => Xphp::$_lang['WEB_TASK_VOL_CDP_LOG_DESC_TASK_CHNAGE_STATUS_FROM_NET_FAULT_TO_RUNNING'],
    'VOL_CDP_LOG_DESC_KEY_AGENT_INIT_CONTROL_SENDER_THREAD_SUCCESSED' => Xphp::$_lang['WEB_TASK_VOL_CDP_LOG_DESC_KEY_AGENT_INIT_CONTROL_SENDER_THREAD_SUCCESSED'],
    'VOL_CDP_LOG_DESC_KEY_AGENT_INIT_DATA_SENDER_THREAD_SUCCESSED' => Xphp::$_lang['WEB_TASK_VOL_CDP_LOG_DESC_KEY_AGENT_INIT_DATA_SENDER_THREAD_SUCCESSED'],
    'VOL_CDP_LOG_DESC_KEY_AGENT_INIT_DATA_PACKET_THREAD_SUCCESSED' => Xphp::$_lang['WEB_TASK_VOL_CDP_LOG_DESC_KEY_AGENT_INIT_DATA_PACKET_THREAD_SUCCESSED'],
    'VOL_CDP_LOG_DESC_KEY_AGENT_INIT_DATA_READ_THREAD_SUCCESSED' => Xphp::$_lang['WEB_TASK_VOL_CDP_LOG_DESC_KEY_AGENT_INIT_DATA_READ_THREAD_SUCCESSED'],
    'VOL_CDP_LOG_DESC_KEY_AGENT_ERROR_OCCURS' => Xphp::$_lang['WEB_TASK_VOL_CDP_LOG_DESC_KEY_AGENT_ERROR_OCCURS'],
    'VOL_CDP_LOG_DESC_KEY_AGENT_NORMAL_REBOOT_TASK_RESUME' => Xphp::$_lang['WEB_TASK_VOL_CDP_LOG_DESC_KEY_AGENT_NORMAL_REBOOT_TASK_RESUME'],
    'VOL_CDP_LOG_DESC_KEY_AGENT_ABNORMAL_REBOOT_TASK_RESTART' => Xphp::$_lang['WEB_TASK_VOL_CDP_LOG_DESC_KEY_AGENT_ABNORMAL_REBOOT_TASK_RESTART'],
    'VOL_CDP_LOG_DESC_KEY_SERVER_REBOOT_TASK_RESUME' => Xphp::$_lang['WEB_TASK_VOL_CDP_LOG_DESC_KEY_SERVER_REBOOT_TASK_RESUME'],
    'VOL_CDP_LOG_DESC_KEY_SERVER_INIT_PARENT_PROCESS_NET_CONNECT_SUCCESSED' => Xphp::$_lang['WEB_TASK_VOL_CDP_LOG_DESC_KEY_SERVER_INIT_PARENT_PROCESS_NET_CONNECT_SUCCESSED'],
    'VOL_CDP_LOG_DESC_KEY_SERVER_INIT_CHILD_PROCESS_NET_LISTEN_CONNECT_SUCCESSED' => Xphp::$_lang['WEB_TASK_VOL_CDP_LOG_DESC_KEY_SERVER_INIT_CHILD_PROCESS_NET_LISTEN_CONNECT_SUCCESSED'],
    'VOL_CDP_LOG_DESC_KEY_AGENT_NET_CONNECT_SUCCESSED' => Xphp::$_lang['WEB_TASK_VOL_CDP_LOG_DESC_KEY_AGENT_NET_CONNECT_SUCCESSED'],
    'VOL_CDP_LOG_DESC_KEY_SERVER_START_NET_LISTEN_SUCCESSED' => Xphp::$_lang['WEB_TASK_VOL_CDP_LOG_DESC_KEY_SERVER_START_NET_LISTEN_SUCCESSED'],
    'VOL_CDP_LOG_DESC_KEY_START_IO_MAPPING' => Xphp::$_lang['WEB_TASK_VOL_CDP_LOG_DESC_KEY_START_IO_MAPPING'],
    'VOL_CDP_LOG_DESC_KEY_IO_MAPPING_SUCCESSED' => Xphp::$_lang['WEB_TASK_VOL_CDP_LOG_DESC_KEY_IO_MAPPING_SUCCESSED'],
    'VOL_CDP_LOG_DESC_KEY_IO_MAPPING_FAILED' => Xphp::$_lang['WEB_TASK_VOL_CDP_LOG_DESC_KEY_IO_MAPPING_FAILED'],
    'VOL_CDP_LOG_DESC_KEY_CREATE_TAKEOVER_TARGET' => Xphp::$_lang['WEB_TASK_VOL_CDP_LOG_DESC_KEY_CREATE_TAKEOVER_TARGET'],
    'VOL_CDP_LOG_DESC_CREATE_TAKEOVER_TARGET_SUCCESSED' => Xphp::$_lang['WEB_TASK_VOL_CDP_LOG_DESC_CREATE_TAKEOVER_TARGET_SUCCESSED'],
    'VOL_CDP_LOG_DESC_CREATE_TAKEOVER_TARGET_FAILED' => Xphp::$_lang['WEB_TASK_VOL_CDP_LOG_DESC_CREATE_TAKEOVER_TARGET_FAILED'],
    'VOL_CDP_LOG_DESC_CREATE_TAKEOVER_VOL_STORAGE_LUN_SUCCESSED' => Xphp::$_lang['WEB_TASK_VOL_CDP_LOG_DESC_CREATE_TAKEOVER_VOL_STORAGE_LUN_SUCCESSED'],
    'VOL_CDP_LOG_DESC_CREATE_TAKEOVER_VOL_STORAGE_LUN_FAILED' => Xphp::$_lang['WEB_TASK_VOL_CDP_LOG_DESC_CREATE_TAKEOVER_VOL_STORAGE_LUN_FAILED'],
    'VOL_CDP_LOG_DESC_DETECTED_AGENT_APP_STATUS_ABNORMAL' => Xphp::$_lang['WEB_TASK_VOL_CDP_LOG_DESC_DETECTED_AGENT_APP_STATUS_ABNORMAL'],
    'VOL_CDP_LOG_DESC_DETECTED_AGENT_SCRIPT_EXECUTE_FAILED' => Xphp::$_lang['WEB_TASK_VOL_CDP_LOG_DESC_DETECTED_AGENT_SCRIPT_EXECUTE_FAILED'],
    'VOL_CDP_LOG_DESC_AUTO_TAKEOVER_CONDITION_TRIGGER' => Xphp::$_lang['WEB_TASK_VOL_CDP_LOG_DESC_AUTO_TAKEOVER_CONDITION_TRIGGER'],
    'VOL_CDP_LOG_DESC_KEY_STOP_FAILBACK' => Xphp::$_lang['WEB_TASK_VOL_CDP_LOG_DESC_KEY_STOP_FAILBACK'],
    'VOL_CDP_LOG_DESC_KEY_FAILBACK_STOPPED_COMPLETE' => Xphp::$_lang['WEB_TASK_VOL_CDP_LOG_DESC_KEY_FAILBACK_STOPPED_COMPLETE'],
    'VOL_CDP_LOG_DESC_KEY_SWITCH_MASTER_IP_SUCCESSED' => Xphp::$_lang['WEB_TASK_VOL_CDP_LOG_DESC_KEY_SWITCH_MASTER_IP_SUCCESSED'],
    'VOL_CDP_LOG_DESC_KEY_SWITCH_MASTER_IP_FAILED' => Xphp::$_lang['WEB_TASK_VOL_CDP_LOG_DESC_KEY_SWITCH_MASTER_IP_FAILED'],
    'VOL_CDP_LOG_DESC_KEY_REMOVE_ADDITIONAL_IP_SUCCESSED' => Xphp::$_lang['WEB_TASK_VOL_CDP_LOG_DESC_KEY_REMOVE_ADDITIONAL_IP_SUCCESSED'],
    'VOL_CDP_LOG_DESC_KEY_REMOVE_ADDITIONAL_IP_FAILED' => Xphp::$_lang['WEB_TASK_VOL_CDP_LOG_DESC_KEY_REMOVE_ADDITIONAL_IP_FAILED'],
    
    'VOL_CDP_LOG_DESC_KEY_FAILBACK_STARTING' => Xphp::$_lang['WEB_TASK_VOL_CDP_LOG_DESC_KEY_FAILBACK_STARTING'],
    'VOL_CDP_LOG_DESC_KEY_CREATE_CONSISITENCY_LABEL_SUCCESSED' => Xphp::$_lang['WEB_TASK_VOL_CDP_LOG_DESC_KEY_CREATE_LABEL_SUCCESS'],
    'VOL_CDP_LOG_DESC_KEY_TRIGGER_AUTO_TAKEOVER' => Xphp::$_lang['WEB_TASK_VOL_CDP_LOG_DESC_KEY_TRIGGER_AUTO_TAKEOVER'],
    'VOL_CDP_LOG_DESC_KEY_AUTO_TAKEOVER_COMPLETED' => Xphp::$_lang['WEB_TASK_VOL_CDP_LOG_DESC_KEY_AUTO_TAKEOVER_COMPLETED'],
    'VOL_CDP_LOG_DESC_KEY_AUTO_TAKEOVER_FAILED' => Xphp::$_lang['WEB_TASK_VOL_CDP_LOG_DESC_KEY_AUTO_TAKEOVER_FAILED'],
    
    'VOL_CDP_LOG_DESC_KEY_EXECUTE_SCRIPT_SUCCESSED' => Xphp::$_lang['WEB_VOL_CDP_LOG_DESC_KEY_EXECUTE_SCRIPT_SUCCESSED'],
    'VOL_CDP_LOG_DESC_KEY_EXECUTE_SCRIPT_FAILED' => Xphp::$_lang['WEB_VOL_CDP_LOG_DESC_KEY_EXECUTE_SCRIPT_FAILED'],
    'VOL_CDP_LOG_DESC_KEY_UMOUNT_FILESYSTEM_FAILED' => Xphp::$_lang['WEB_VOL_CDP_LOG_DESC_KEY_UMOUNT_FILESYSTEM_FAILED'],
    'VOL_CDP_LOG_DESC_KEY_FORMAT_VOL_FAILED' => Xphp::$_lang['WEB_VOL_CDP_LOG_DESC_KEY_FORMAT_VOL_FAILED'],
    'VOL_CDP_LOG_DESC_KEY_OPEN_RESTORE_VOL_FAILED' => Xphp::$_lang['WEB_VOL_CDP_LOG_DESC_KEY_OPEN_RESTORE_VOL_FAILED'],
    'VOL_CDP_LOG_DESC_KEY_UMOUNT_VOL_FAILED' => Xphp::$_lang['WEB_VOL_CDP_LOG_DESC_KEY_UMOUNT_VOL_FAILED'],
    
    'VOL_CDP_LOG_DESC_KEY_TASK_OP_START_FAILBACK' => Xphp::$_lang['WEB_VOL_CDP_LOG_DESC_KEY_TASK_OP_START_FAILBACK'],

    
    'VOL_CDP_LOG_DESC_KEY_SWITCH_MASTER_IP_TO_TARGET_HOST_SUCCESSED' => Xphp::$_lang['WEB_VOL_CDP_LOG_DESC_KEY_SWITCH_MASTER_IP_TO_TARGET_HOST_SUCCESSED'],
    'VOL_CDP_LOG_DESC_KEY_START_VOL_FORMAT_OPERATION' => Xphp::$_lang['WEB_VOL_CDP_LOG_DESC_KEY_START_VOL_FORMAT_OPERATION'],
    'VOL_CDP_LOG_DESC_KEY_PERFORM_UNMOUNT_FILESYSTEM_OPERATION' => Xphp::$_lang['WEB_VOL_CDP_LOG_DESC_KEY_PERFORM_UNMOUNT_FILESYSTEM_OPERATION'],
    'VOL_CDP_LOG_DESC_KEY_PERFORM_UNMOUNT_VOL_OPERATION' => Xphp::$_lang['WEB_VOL_CDP_LOG_DESC_KEY_PERFORM_UNMOUNT_VOL_OPERATION'],
    'VOL_CDP_LOG_DESC_KEY_COMPLETE_VOL_FORMAT_OPERATION' => Xphp::$_lang['WEB_VOL_CDP_LOG_DESC_KEY_COMPLETE_VOL_FORMAT_OPERATION'],
    'VOL_CDP_LOG_DESC_KEY_PERFORM_FILESYSTEM_SCAN_AND_REPAIR' => Xphp::$_lang['WEB_VOL_CDP_LOG_DESC_KEY_PERFORM_FILESYSTEM_SCAN_AND_REPAIR'],
    'VOL_CDP_LOG_DESC_KEY_PERFORM_VOL_MOUNT_OPERATION' => Xphp::$_lang['WEB_VOL_CDP_LOG_DESC_KEY_PERFORM_VOL_MOUNT_OPERATION'],
    'VOL_CDP_LOG_DESC_KEY_START_REBUILD_PARTITION_INFO' => Xphp::$_lang['WEB_VOL_CDP_LOG_DESC_KEY_START_REBUILD_PARTITION_INFO'],
    'VOL_CDP_LOG_DESC_KEY_COMPLETE_FSTAB_REPAIR' => Xphp::$_lang['WEB_VOL_CDP_LOG_DESC_KEY_COMPLETE_FSTAB_REPAIR'],
    'VOL_CDP_LOG_DESC_KEY_COMPLETE_GRUB_REPAIR' => Xphp::$_lang['WEB_VOL_CDP_LOG_DESC_KEY_COMPLETE_GRUB_REPAIR'],
    'VOL_CDP_LOG_DESC_KEY_AGENT_START_OS_EVENT_MONITOR' => Xphp::$_lang['WEB_VOL_CDP_LOG_DESC_KEY_AGENT_START_OS_EVENT_MONITOR'],
    'VOL_CDP_LOG_DESC_KEY_AGENT_START_APP_MONITOR' => Xphp::$_lang['WEB_VOL_CDP_LOG_DESC_KEY_AGENT_START_APP_MONITOR'],
    'VOL_CDP_LOG_DESC_KEY_AGENT_START_CUSTOM_SCRIPT_MONITOR' => Xphp::$_lang['WEB_VOL_CDP_LOG_DESC_KEY_AGENT_START_CUSTOM_SCRIPT_MONITOR'],
    'VOL_CDP_LOG_DESC_KEY_AGENT_START_HEARTBEAT' => Xphp::$_lang['WEB_VOL_CDP_LOG_DESC_KEY_AGENT_START_HEARTBEAT'],
    'VOL_CDP_LOG_DESC_KEY_AGENT_START_VOL_INIT_SYNC' => Xphp::$_lang['WEB_VOL_CDP_LOG_DESC_KEY_AGENT_START_VOL_INIT_SYNC'],
    'VOL_CDP_LOG_DESC_KEY_AGENT_VOL_INIT_SYNC_COMPLETED' => Xphp::$_lang['WEB_VOL_CDP_LOG_DESC_KEY_AGENT_VOL_INIT_SYNC_COMPLETED'],
    
    'VOL_CDP_LOG_DESC_KEY_STANDBY_START_APP_TAKEOVER' => Xphp::$_lang['WEB_VOL_CDP_LOG_DESC_KEY_STANDBY_START_APP_TAKEOVER'],
    'VOL_CDP_LOG_DESC_KEY_STANDBY_APP_TAKEOVER_COMPLETED' => Xphp::$_lang['WEB_VOL_CDP_LOG_DESC_KEY_STANDBY_APP_TAKEOVER_COMPLETED'],
    'VOL_CDP_LOG_DESC_KEY_STANDBY_APP_TAKEOVER_ABNORMAL' => Xphp::$_lang['WEB_VOL_CDP_LOG_DESC_KEY_STANDBY_APP_TAKEOVER_ABNORMAL'],
    'VOL_CDP_LOG_DESC_KEY_STANDBY_STOP_APP_TAKEOVER' => Xphp::$_lang['WEB_VOL_CDP_LOG_DESC_KEY_STANDBY_STOP_APP_TAKEOVER'],
    'VOL_CDP_LOG_DESC_KEY_STANDBY_APP_TAKEOVER_STOPED' => Xphp::$_lang['WEB_VOL_CDP_LOG_DESC_KEY_STANDBY_APP_TAKEOVER_STOPED'],
    'VOL_CDP_LOG_DESC_KEY_START_APP_FAILBACK_OPERATION' => Xphp::$_lang['WEB_VOL_CDP_LOG_DESC_KEY_START_APP_FAILBACK_OPERATION'],
    'VOL_CDP_LOG_DESC_KEY_APP_FAILBACK_COMPLETED' => Xphp::$_lang['WEB_VOL_CDP_LOG_DESC_KEY_APP_FAILBACK_COMPLETED'],
    'VOL_CDP_LOG_DESC_KEY_APP_FAILBACK_ABNORMAL' => Xphp::$_lang['WEB_VOL_CDP_LOG_DESC_KEY_APP_FAILBACK_ABNORMAL'],
    
    'VOL_CDP_LOG_DESC_KEY_AGENT_START_BACKUP_REPLICATION_SUCCESSED' => Xphp::$_lang['WEB_VOL_CDP_LOG_DESC_KEY_AGENT_START_BACKUP_REPLICATION_SUCCESSED'],
    'VOL_CDP_LOG_DESC_KEY_AGENT_START_BACKUP_REPLICATION_FAILED' => Xphp::$_lang['WEB_VOL_CDP_LOG_DESC_KEY_AGENT_START_BACKUP_REPLICATION_FAILED'],
    'VOL_CDP_LOG_DESC_KEY_START_FAILBACK_FAILED' => Xphp::$_lang['WEB_VOL_CDP_LOG_DESC_KEY_START_FAILBACK_FAILED'],
    'VOL_CDP_LOG_DESC_KEY_START_VOL_DATA_RECOVERY_OPERATION' => Xphp::$_lang['WEB_VOL_CDP_LOG_DESC_KEY_START_VOL_DATA_RECOVERY_OPERATION'],
    'VOL_CDP_LOG_DESC_KEY_VOL_DATA_RECOVERY_COMPLETED' => Xphp::$_lang['WEB_VOL_CDP_LOG_DESC_KEY_VOL_DATA_RECOVERY_COMPLETED'],
    'VOL_CDP_LOG_DESC_KEY_VOL_DATA_RECOVERY_FAILED' => Xphp::$_lang['WEB_VOL_CDP_LOG_DESC_KEY_VOL_DATA_RECOVERY_FAILED'],
    
    'VOL_CDP_LOG_DESC_KEY_FIND_SOURCE_VOL_INFO_FAILED' => Xphp::$_lang['WEB_VOL_CDP_LOG_DESC_KEY_FIND_SOURCE_VOL_INFO_FAILED'],
    'VOL_CDP_LOG_DESC_KEY_FIND_TAEGET_DISK_INFO_FAILED' => Xphp::$_lang['WEB_VOL_CDP_LOG_DESC_KEY_FIND_TAEGET_DISK_INFO_FAILED'],
    'VOL_CDP_LOG_DESC_KEY_BUILD_VOL2DISK_MAP_SUCCESS' => Xphp::$_lang['WEB_VOL_CDP_LOG_DESC_KEY_BUILD_VOL2DISK_MAP_SUCCESS'],
    'VOL_CDP_LOG_DESC_KEY_UNKNOW_PARTED_TYPE' => Xphp::$_lang['WEB_VOL_CDP_LOG_DESC_KEY_UNKNOW_PARTED_TYPE'],
    'VOL_CDP_LOG_DESC_KEY_REPARTED_DISK_FAILED' => Xphp::$_lang['WEB_VOL_CDP_LOG_DESC_KEY_REPARTED_DISK_FAILED'],
    'VOL_CDP_LOG_DESC_KEY_REPAIR_MBR_FAILED' => Xphp::$_lang['WEB_VOL_CDP_LOG_DESC_KEY_REPAIR_MBR_FAILED'],
    'VOL_CDP_LOG_DESC_KEY_REPAIR_GPT_FAILED' => Xphp::$_lang['WEB_VOL_CDP_LOG_DESC_KEY_REPAIR_GPT_FAILED'],
    'VOL_CDP_LOG_DESC_KEY_REPARTED_DISK_AND_REPAIR_MBR_SUCCESS' => Xphp::$_lang['WEB_VOL_CDP_LOG_DESC_KEY_REPARTED_DISK_AND_REPAIR_MBR_SUCCESS'],
    'VOL_CDP_LOG_DESC_KEY_REPARTED_DISK_AND_REPAIR_GPT_SUCCESS' => Xphp::$_lang['WEB_VOL_CDP_LOG_DESC_KEY_REPARTED_DISK_AND_REPAIR_GPT_SUCCESS'],
    'VOL_CDP_LOG_DESC_KEY_BUILD_VOL2VOL_MAP_SUCCESS' => Xphp::$_lang['WEB_VOL_CDP_LOG_DESC_KEY_BUILD_VOL2VOL_MAP_SUCCESS'],
    
    'VOL_CDP_LOG_DESC_KEY_BACKUP_STORAGE_ROOT_PATH_INVAILD' => Xphp::$_lang['WEB_VOL_CDP_LOG_DESC_KEY_BACKUP_STORAGE_ROOT_PATH_INVAILD'],
    
    'VOL_CDP_LOG_DESC_KEY_START_VOL_VALID_DATA_SCAN_OPERATION' => Xphp::$_lang['WEB_VOL_CDP_LOG_DESC_KEY_START_VOL_VALID_DATA_SCAN_OPERATION'],
    'VOL_CDP_LOG_DESC_KEY_SCAN_VOL_VALID_DATA_COMPLETED' => Xphp::$_lang['WEB_VOL_CDP_LOG_DESC_KEY_SCAN_VOL_VALID_DATA_COMPLETED'],
    'VOL_CDP_LOG_DESC_KEY_SCAN_VOL_VALID_DATA_FAILED' => Xphp::$_lang['WEB_VOL_CDP_LOG_DESC_KEY_SCAN_VOL_VALID_DATA_FAILED'],
    
    'VOL_CDP_LOG_DESC_KEY_AGENT_HEARTBEAT_SYNCHRONIZATION_ANOMALY' => Xphp::$_lang['WEB_VOL_CDP_LOG_DESC_KEY_AGENT_HEARTBEAT_SYNCHRONIZATION_ANOMALY'],
    'VOL_CDP_LOG_DESC_KEY_AGENT_HEARTBEAT_SYNCHRONIZATION_NORMAL' => Xphp::$_lang['WEB_VOL_CDP_LOG_DESC_KEY_AGENT_HEARTBEAT_SYNCHRONIZATION_NORMAL'],
    'VOL_CDP_LOG_DESC_KEY_NOTIFY_AGENT_START_BACKUP_FAILED' => Xphp::$_lang['WEB_VOL_CDP_LOG_DESC_KEY_NOTIFY_AGENT_START_BACKUP_FAILED'],
    'VOL_CDP_LOG_DESC_KEY_NOTIFY_AGENT_START_FAILBACK_FAILED' => Xphp::$_lang['WEB_VOL_CDP_LOG_DESC_KEY_NOTIFY_AGENT_START_FAILBACK_FAILED'],
    
    'VOL_CDP_LOG_DESC_KEY_AUTHORIZED_CAPACITY_INSUFFICIENT' => Xphp::$_lang['WEB_VOL_CDP_LOG_DESC_KEY_AUTHORIZED_CAPACITY_INSUFFICIENT'],
    'VOL_CDP_LOG_DESC_KEY_AUTHORIZED_CAPACITY_INSUFFICIENT_TO_BACKUP' => Xphp::$_lang['WEB_VOL_CDP_LOG_DESC_KEY_AUTHORIZED_CAPACITY_INSUFFICIENT_TO_BACKUP'],
    'VOL_CDP_LOG_DESC_KEY_AUTHORIZED_CAPACITY_INSUFFICIENT_TO_CONTINUE_BACKUP' => Xphp::$_lang['WEB_VOL_CDP_LOG_DESC_KEY_AUTHORIZED_CAPACITY_INSUFFICIENT_TO_CONTINUE_BACKUP'],
    'VOL_CDP_LOG_DESC_KEY_AUTHORIZED_CAPACITY_NEAR_THRESHOLD' => Xphp::$_lang['WEB_VOL_CDP_LOG_DESC_KEY_AUTHORIZED_CAPACITY_NEAR_THRESHOLD'],
    
    'VOL_CDP_LOG_DESC_KEY_START_CACHE_DATA_EXPORT_OPERATION' => Xphp::$_lang['WEB_VOL_CDP_LOG_DESC_KEY_START_CACHE_DATA_EXPORT_OPERATION'],
    'VOL_CDP_LOG_DESC_KEY_EXPORT_CACHE_DATA_COMPLETED' => Xphp::$_lang['WEB_VOL_CDP_LOG_DESC_KEY_EXPORT_CACHE_DATA_COMPLETED'],
    'VOL_CDP_LOG_DESC_KEY_DETECT_SERVER_REBOOT_TO_STOP_TASK' => Xphp::$_lang['WEB_VOL_CDP_LOG_DESC_KEY_DETECT_SERVER_REBOOT_TO_STOP_TASK'],
    'VOL_CDP_LOG_DESC_KEY_DETECT_AGENT_REBOOT_TO_STOP_TASK' => Xphp::$_lang['WEB_VOL_CDP_LOG_DESC_KEY_DETECT_AGENT_REBOOT_TO_STOP_TASK'],

);

?>