<?php

/*******************************************
 ** 系统日志描述配置信息
 **
 ** @author       xiezhuowei@vinchin.com
 ** @date         2015-06-06 下午15:16:44
 ** @version      1.0.0
 ** @copyright    Copyright 2015 vinchin.com
 ********************************************/

return array(
    //***************WEB******************//
    'SYSTEM_USER_ADD_SUCCESS' => xphp_get_lang('WEB_LOG_SYSTEM_ADD_SUCCESS'),
    'SYSTEM_USER_LOGIN_SUCCESS' => xphp_get_lang('WEB_LOG_SYSTEM_LOGIN_SUCCESS'),
    'SYSTEM_USER_LOGIN_FAILURE' => xphp_get_lang('WEB_LOG_SYSTEM_LOGIN_FAILURE'),
    'SYSTEM_USER_LOCK_SUCCESS' => xphp_get_lang('WEB_LOG_SYSTEM_LOCK_SUCCESS'),
    'SYSTEM_USER_LOCK_FAILURE' => xphp_get_lang('WEB_LOG_SYSTEM_LOCK_FAILURE'),
    'SYSTEM_USER_UNLOCK_SUCCESS' => xphp_get_lang('WEB_LOG_SYSTEM_UNLOCK_SUCCESS'),
    'SYSTEM_USER_DELETE_SUCCESS' => xphp_get_lang('WEB_LOG_SYSTEM_DELETE_SUCCESS'),
    'SYSTEM_USER_DELETE_FIALURE' => xphp_get_lang('WEB_LOG_SYSTEM_DELETE_FIALURE'),
    'SYSTEM_USER_EDIT_PASSWORD_SUCCESS' => xphp_get_lang('WEB_LOG_SYSTEM_EDIT_PASSWORD_SUCCESS'),
    'SYSTEM_USER_EDIT_INFO_SUCCESS' => xphp_get_lang('WEB_LOG_SYSTEM_EDIT_INFO_SUCCESS'),
    'SYSTEM_USER_MODIFY_SUCCESS' => xphp_get_lang('WEB_LOG_SYSTEM_USER_MODIFY_SUCCESS'),

    'SYSTEM_SETTING_IP' => xphp_get_lang('WEB_LOG_SYSTEM_SETTING_IP'),
    'SYSTEM_SETTING_TIME' => xphp_get_lang('WEB_LOG_SYSTEM_SETTING_TIME'),
    'SYSTEM_SETTING_SYSTEM_NAME' => xphp_get_lang('WEB_LOG_SYSTEM_SETTING_SYSTEM_NAME'),
    'SYSTEM_SETTING_LOGO' => xphp_get_lang('WEB_LOG_SYSTEM_SETTING_LOGO'),
    'SYSTEM_SETTING_EXPORT_DATA' => xphp_get_lang('WEB_LOG_SYSTEM_SETTING_EXPORT_DATA'),
    'SYSTEM_SETTING_IMPORT_DATA' => xphp_get_lang('WEB_LOG_SYSTEM_SETTING_IMPORT_DATA'),
    'SYSTEM_SETTING_EMAIL_NOTICE' => xphp_get_lang('WEB_LOG_SYSTEM_SETTING_EMAIL_NOTICE'),
    'SYSTEM_SETTING_SMS_NOTICE' => xphp_get_lang('WEB_LOG_SYSTEM_SETTING_SMS_NOTICE'),

    'SYSTEM_SETTING_POWER_OFF' => xphp_get_lang('WEB_LOG_SYSTEM_PT_OP_POWEROFF_NODE'),
    'SYSTEM_SETTING_REBOOT' => xphp_get_lang('WEB_LOG_SYSTEM_PT_OP_RESTART_NODE'),

    //
    'SYSTEM_SETTING_CONFIG_MESSAGE_PUSH' => xphp_get_lang('WEB_LOG_SYSTEM_SETTING_CONFIG_MESSAGE_PUSH'),
    'SYSTEM_SETTING_CONFIG_VISUAL_NAME' => xphp_get_lang('WEB_LOG_SYSTEM_SETTING_CONFIG_VISUAL_NAME'),


    'SYSTEM_LOG_DESC_KEY_PROXY_ADD' => xphp_get_lang('WEB_LOG_SYSTEM_DESC_KEY_PROXY_ADD'),
    'SYSTEM_LOG_DESC_KEY_PROXY_EDIT' => xphp_get_lang('WEB_LOG_SYSTEM_DESC_KEY_PROXY_EDIT'),
    'SYSTEM_LOG_DESC_KEY_PROXY_DELETE' => xphp_get_lang('WEB_LOG_SYSTEM_DESC_KEY_PROXY_DELETE'),

    'SYSTEM_LOG_DESC_KEY_ADD_STRATEGY' => xphp_get_lang('WEB_LOG_SYSTEM_DESC_KEY_ADD_STRATEGY'),
    'SYSTEM_LOG_DESC_KEY_EDIT_STRATEGY' => xphp_get_lang('WEB_LOG_SYSTEM_DESC_KEY_EDIT_STRATEGY'),
    'SYSTEM_LOG_DESC_KEY_DELETE_STRATEGY' => xphp_get_lang('WEB_LOG_SYSTEM_DESC_KEY_DELETE_STRATEGY'),

    //副本
    'SYSTEM_LOG_DELETE_COPY_BATCH_TIMEPOINT' => xphp_get_lang('WEB_LOG_SYSTEM_DELETE_COPY_BATCH_TIMEPOINT'),
    'SYSTEM_LOG_DELETE_COPY_ONE_TIMEPOINT' => xphp_get_lang('WEB_LOG_SYSTEM_DELETE_COPY_ONE_TIMEPOINT'),

    //归档
    'SYSTEM_LOG_DELETE_ARCHIVE_BATCH_TIMEPOINT' => xphp_get_lang('WEB_LOG_SYSTEM_DELETE_ARCHIVE_BATCH_TIMEPOINT'),
    'SYSTEM_LOG_DELETE_ARCHIVE_ONE_TIMEPOINT' => xphp_get_lang('WEB_LOG_SYSTEM_DELETE_ARCHIVE_ONE_TIMEPOINT'),

    //文件
    'SYSTEM_LOG_DELETE_FILE_ONE_TIMEPOINT' => xphp_get_lang('WEB_LOG_SYSTEM_DELETE_FILE_ONE_TIMEPOINT'),
    'SYSTEM_LOG_ADD_FILE_AGENT_AUTH' => xphp_get_lang('WEB_LOG_SYSTEM_ADD_FILE_AGENT_AUTH'),
    'SYSTEM_LOG_EDIT_FILE_AGENT_AUTH' => xphp_get_lang('WEB_LOG_SYSTEM_EDIT_FILE_AGENT_AUTH'),
    'SYSTEM_LOG_DELETE_FILE_AGENT' => xphp_get_lang('WEB_LOG_SYSTEM_DELETE_FILE_AGENT'),
    'SYSTEM_LOG_DELETE_OFFLINE_FILE_AGENT' => xphp_get_lang('WEB_LOG_SYSTEM_DELETE_OFFLINE_FILE_AGENT'),

    //NAS
    'BD_SYSTEMLOG_DESC_KEY_NAS_ADD' => xphp_get_lang('WEB_LOG_SYSTEM_BD_SYSTEMLOG_DESC_KEY_NAS_ADD'),
    'BD_SYSTEMLOG_DESC_KEY_NAS_DELETE' => xphp_get_lang('WEB_LOG_SYSTEM_BD_SYSTEMLOG_DESC_KEY_NAS_DELETE'),
    'BD_SYSTEMLOG_DESC_KEY_NAS_UMOUNT' => xphp_get_lang('WEB_LOG_SYSTEM_BD_SYSTEMLOG_DESC_KEY_NAS_UMOUNT'),
    'BD_SYSTEMLOG_DESC_KEY_NAS_MOUNT' => xphp_get_lang('WEB_LOG_SYSTEM_BD_SYSTEMLOG_DESC_KEY_NAS_MOUNT'),
    'BD_SYSTEMLOG_DESC_KEY_NAS_MODIFY' => xphp_get_lang('WEB_LOG_SYSTEM_BD_SYSTEMLOG_DESC_KEY_NAS_MODIFY'),

    //日志
    'SYSTEM_LOG_DELETE_TASK_LOG' => xphp_get_lang('WEB_LOG_SYSTEM_DELETE_TASK_LOG'),
    'SYSTEM_LOG_DELETE_SYSTEM_LOG' => xphp_get_lang('WEB_LOG_SYSTEM_DELETE_SYSTEM_LOG'),

    //告警
    'SYSTEM_LOG_DELETE_TASK_ALARM' => xphp_get_lang('WEB_LOG_SYSTEM_DELETE_TASK_ALARM'),
    'SYSTEM_LOG_DELETE_SYSTEM_ALARM' => xphp_get_lang('WEB_LOG_SYSTEM_DELETE_SYSTEM_ALARM'),

    'SYSTEM_LOG_DELETE_BATCH_TIMEPOINT' => xphp_get_lang('WEB_LOG_SYSTEM_DELETE_BATCH_TIMEPOINT'),
    'SYSTEM_LOG_DELETE_ONE_TIMEPOINT' => xphp_get_lang('WEB_LOG_SYSTEM_DELETE_ONE_TIMEPOINT'),
    'SYSTEM_LOG_DELETE_ONE_OS_TIMEPOINT' => xphp_get_lang('WEB_LOG_SYSTEM_DELETE_ONE_OS_TIMEPOINT'),
    'SYSTEM_LOG_TIMEPOINT_REMARK' => xphp_get_lang('WEB_LOG_SYSTEM_TIMEPOINT_REMARK'),
    'SYSTEM_LOG_TIMEPOINT_STAR' => xphp_get_lang('WEB_LOG_SYSTEM_TIMEPOINT_STAR'),
    'SYSTEM_LOG_TIMEPOINT_UNSTAR' => xphp_get_lang('WEB_LOG_SYSTEM_TIMEPOINT_UNSTAR'),
    'SYSTEM_LOG_EXCEED_ALARM_VALUE_CPU' => xphp_get_lang('WEB_LOG_EXCEED_ALARM_VALUE_CPU'),
    'SYSTEM_LOG_EXCEED_ALARM_VALUE_RAM' => xphp_get_lang('WEB_LOG_EXCEED_ALARM_VALUE_RAM'),
    'SYSTEM_LOG_EXCEED_ALARM_VALUE_RPS' => xphp_get_lang('WEB_LOG_EXCEED_ALARM_VALUE_RPS'),

    //数据库
    'SYSTEM_LOG_ADD_DB_AGENT' => xphp_get_lang('WEB_LOG_SYSTEM_ADD_DB_AGENT'),
    'SYSTEM_LOG_MODIFY_DB_AGENT' => xphp_get_lang('WEB_LOG_SYSTEM_MODIFY_DB_AGENT'),
    'SYSTEM_LOG_DELETE_DB_AGENT' => xphp_get_lang('WEB_LOG_SYSTEM_DELETE_DB_AGENT'),
    'SYSTEM_LOG_ADD_DB_AGENT_AUTH' => xphp_get_lang('WEB_LOG_SYSTEM_ADD_DB_AGENT_AUTH'),
    'SYSTEM_LOG_EDIT_DB_AGENT_AUTH' => xphp_get_lang('WEB_LOG_SYSTEM_EDIT_DB_AGENT_AUTH'),
    'SYSTEM_LOG_CANCEL_DB_AGENT_AUTH' => xphp_get_lang('WEB_LOG_SYSTEM_CANCEL_DB_AGENT_AUTH'),
    'SYSTEM_LOG_DELETE_ONE_DB_TIMEPOINT' => xphp_get_lang('WEB_LOG_SYSTEM_DELETE_ONE_DB_TIMEPOINT'),
    'SYSTEM_LOG_DB_AUTH_INSTANCE' => xphp_get_lang('WEB_LOG_SYSTEM_DB_AUTH_INSTANCE'),


    //***************PF*******************//
    'BD_SYSTEMLOG_DESC_KEY_AGENT_ONLINE' => xphp_get_lang('WEB_LOG_SYSTEM_AGENT_ONLINE'),
    'BD_SYSTEMLOG_DESC_KEY_AGENT_OFFLINE' => xphp_get_lang('WEB_LOG_SYSTEM_AGENT_OFFLINE'),
    'BD_SYSTEMLOG_DESC_KEY_DEL_TIMEPOINT_SUCCESS' => xphp_get_lang('WEB_LOG_SYSTEM_DEL_TIMEPOINT_SUCCESS'),
    'BD_SYSTEMLOG_DESC_KEY_DELETE_TIMEPOINT' => xphp_get_lang('WEB_LOG_SYSTEM_BD_SYSTEMLOG_DESC_KEY_DELETE_TIMEPOINT'),
    'BD_SYSTEMLOG_DESC_KEY_DELETE_TIMEPOINT_IN_BATCH' => xphp_get_lang('WEB_LOG_SYSTEM_BD_SYSTEMLOG_DESC_KEY_DELETE_TIMEPOINT_IN_BATCH'),
    'BD_SYSTEMLOG_DESC_KEY_SET_TIMEPOINT_GFS_FLAG' => xphp_get_lang('WEB_SYSTEMLOG_DESC_KEY_SET_TIMEPOINT_GFS_FLAG'),
    'BD_SYSTEMLOG_DESC_KEY_UNSET_TIMEPOINT_GFS_FLAG' => xphp_get_lang('WEB_SYSTEMLOG_DESC_KEY_UNSET_TIMEPOINT_GFS_FLAG'),
    'BD_SYSTEMLOG_DESC_KEY_SET_TIMEPOINT_IMPORTANCE_FLAG' => xphp_get_lang('WEB_SYSTEMLOG_DESC_KEY_SET_TIMEPOINT_IMPORTANCE_FLAG'),
    'BD_SYSTEMLOG_DESC_KEY_MARK_TIMEPOINT_SUCCESS' => xphp_get_lang('WEB_LOG_SYSTEM_MARK_TIMEPOINT_SUCCESS'),
    'BD_SYSTEMLOG_DESC_KEY_UNMARK_TIMEPOINT_SUCCESS' => xphp_get_lang('WEB_LOG_SYSTEM_UNMARK_TIMEPOINT_SUCCESS'),
    'BD_SYSTEMLOG_DESC_KEY_COMMENT_TIMEPOINT_SUCCESS' => xphp_get_lang('WEB_LOG_SYSTEM_COMMENT_TIMEPOINT_SUCCESS'),
    'BD_SYSTEMLOG_DESC_KEY_ADD_AUTHORIZE_SUCCESS' => xphp_get_lang('WEB_LOG_SYSTEM_ADD_AUTHORIZE_SUCCESS'),
    'BD_SYSTEMLOG_DESC_KEY_MODIFY_AUTHORIZE_SUCCESS' => xphp_get_lang('WEB_LOG_SYSTEM_MODIFY_AUTHORIZE_SUCCESS'),
    'BD_SYSTEMLOG_DESC_KEY_MODIFY_SYSTEM_TIME_SUCCESS' => xphp_get_lang('WEB_LOG_SYSTEM_MODIFY_SYSTEM_TIME_SUCCESS'),
    'BD_SYSTEMLOG_DESC_KEY_UPDATE_SYSTEM_SUCCESS' => xphp_get_lang('WEB_LOG_SYSTEM_UPDATE_SYSTEM_SUCCESS'),
    'BD_SYSTEMLOG_DESC_KEY_SYS_AUTH_ABNORMAL_BY_ENV_CHANGE' =>
        xphp_get_lang('WEB_LOG_SYSTEM_SYS_AUTH_ABNORMAL_BY_ENV_CHANGE'),
    'BD_SYSTEMLOG_DESC_KEY_SYS_AUTH_ABNORMAL_KEY_IS_INVALID' =>
        xphp_get_lang('WEB_LOG_SYSTEM_SYS_AUTH_ABNORMAL_KEY_IS_INVALID'),
    'BD_SYSTEMLOG_DESC_KEY_SYS_AUTH_ABNORMAL' => xphp_get_lang('WEB_LOG_SYSTEM_SYS_AUTH_ABNORMAL'),
    'BD_SYSTEMLOG_DESC_KEY_SYS_AUTH_EXHAUST' => xphp_get_lang('WEB_LOG_SYSTEM_SYS_AUTH_EXHAUST'),

    //节点名字[IP)
    'BD_SYSTEMLOG_DESC_KEY_NODE_CONNECT' => xphp_get_lang('WEB_LOG_SYSTEM_NODE_CONNECT'),
    'BD_SYSTEMLOG_DESC_KEY_NODE_ABNORMAL' => xphp_get_lang('WEB_LOG_SYSTEM_NODE_ABNORMAL'),
    'BD_SYSTEMLOG_DESC_KEY_NODE_OFFLINE' => xphp_get_lang('WEB_LOG_SYSTEM_NODE_OFFLINE'),
    'BD_SYSTEMLOG_DESC_KEY_NODE_MODIFY' => xphp_get_lang('WEB_LOG_SYSTEM_NODE_MODIFY'),
    'BD_SYSTEMLOG_DESC_KEY_NODE_DELETE' => xphp_get_lang('WEB_LOG_SYSTEM_NODE_DELETE'),
    /*------------------------------------for agent op-----------------------------------------*/
    'BD_SYSTEMLOG_DESC_KEY_AGENT_ADD' => xphp_get_lang('WEB_LOG_SYSTEM_AGENT_ADD'),
    'BD_SYSTEMLOG_DESC_KEY_AGENT_REFRESH' => xphp_get_lang('WEB_LOG_SYSTEM_AGENT_REFRESH'),
    'BD_SYSTEMLOG_DESC_KEY_AGENT_DELETE' => xphp_get_lang('WEB_LOG_SYSTEM_AGENT_DELETE'),
    'BD_SYSTEMLOG_DESC_KEY_AGENT_MODIFY' => xphp_get_lang('WEB_LOG_SYSTEM_AGENT_MODIFY'),

    //存储名[存储类型)  节点名[节点IP)
    'BD_SYSTEMLOG_DESC_KEY_STORAGE_ADD' => xphp_get_lang('WEB_LOG_SYSTEM_STORAGE_ADD'),
    'BD_SYSTEMLOG_DESC_KEY_STORAGE_EDIT' => xphp_get_lang('WEB_LOG_SYSTEM_STORAGE_EDIT'),
    'BD_SYSTEMLOG_DESC_KEY_STORAGE_DELETE' => xphp_get_lang('WEB_LOG_SYSTEM_STORAGE_DELETE'),
    'BD_SYSTEMLOG_DESC_KEY_STORAGE_IMPORT_DATA' => xphp_get_lang('WEB_LOG_SYSTEM_STORAGE_IMPORT_DATA'),
    'BD_SYSTEMLOG_DESC_KEY_STORAGE_ABNORMAL' => xphp_get_lang('WEB_LOG_SYSTEM_STORAGE_ABNORMAL'),
    'BD_SYSTEMLOG_DESC_KEY_STORAGE_OFFLINE' => xphp_get_lang('WEB_LOG_SYSTEM_STORAGE_OFFLINE'),
    'BD_SYSTEMLOG_DESC_KEY_STORAGE_SPACE_LACK' => xphp_get_lang('WEB_LOG_SYSTEM_STORAGE_SPACE_LACK'),
    'BD_SYSTEMLOG_DESC_KEY_STORAGE_DISTRIBUTION_IMPORT_DATA' =>
        xphp_get_lang('WEB_LOG_SYSTEM_STORAGE_DISTRIBUTION_IMPORT_DATA'),
    'BD_SYSTEMLOG_DESC_KEY_STORAGE_DELETE_IMPORT_DATA' => xphp_get_lang('WEB_LOG_SYSTEM_STORAGE_DELETE_IMPORT_DATA'),
    'BD_SYSTEMLOG_DESC_KEY_STORAGE_NOT_MOUNTED' => xphp_get_lang('WEB_LOG_SYSTEM_STORAGE_NOT_MOUNTED'),
    'BD_SYSTEMLOG_DESC_KEY_STORAGE_BACK_ONLINE' => xphp_get_lang('WEB_LOG_SYSTEM_STORAGE_BACK_ONLINE'),

    //时间点管理
    'BD_SYSTEMLOG_DESC_KEY_TIMEPOINT_REMARK' => xphp_get_lang('WEB_LOG_SYSTEM_TIMEPOINT_REMARK'),
    'BD_SYSTEMLOG_DESC_KEY_TIMEPOINT_STAR' => xphp_get_lang('WEB_LOG_SYSTEM_TIMEPOINT_STAR'),
    'BD_SYSTEMLOG_DESC_KEY_TIMEPOINT_UNSTAR' => xphp_get_lang('WEB_LOG_SYSTEM_TIMEPOINT_UNSTAR'),
    'BD_SYSTEMLOG_DESC_KEY_TIMEPOINT_DELETE' => xphp_get_lang('WEB_LOG_SYSTEM_TIMEPOINT_DELETE'),
    'BD_SYSTEMLOG_DESC_KEY_TIMEPOINT_DELETE_BATCH' => xphp_get_lang('WEB_LOG_SYSTEM_TIMEPOINT_DELETE_BATCH'),

    //授权       别名[IP)
    'BD_SYSTEMLOG_DESC_KEY_LISENCE_HOST' => xphp_get_lang('WEB_LOG_SYSTEM_LISENCE_HOST'),
    'BD_SYSTEMLOG_DESC_KEY_LISENCE_UNHOST' => xphp_get_lang('WEB_LOG_SYSTEM_LISENCE_UNHOST'),
    'BD_SYSTEMLOG_DESC_KEY_LISENCE_HOST_BATCH' => xphp_get_lang('WEB_LOG_SYSTEM_LISENCE_HOST_BATCH'),


    //***************PT*******************//
    'PT_SYSTEMLOG_DESC_KEY_ADD_LICENSE' => xphp_get_lang('WEB_LOG_SYSTEM_ADD_LICENSE'),
    'PT_SYSTEMLOG_DESC_KEY_UPDATE_LICENSE' => xphp_get_lang('WEB_LOG_SYSTEM_UPDATE_LICENSE'),

    //***************VM*******************//
    'VM_SYSTEMLOG_DESC_KEY_ADD_VCENTER_SUCCESS' => xphp_get_lang('WEB_LOG_SYSTEM_ADD_VCENTER_SUCCESS'),
    'VM_SYSTEMLOG_DESC_KEY_ADD_HOST_SUCCESS' => xphp_get_lang('WEB_LOG_SYSTEM_ADD_HOST_SUCCESS'),
    'VM_SYSTEMLOG_DESC_KEY_MODIFY_VCENTER_SUCCESS' => xphp_get_lang('WEB_LOG_SYSTEM_MODIFY_VCENTER_SUCCESS'),
    'VM_SYSTEMLOG_DESC_KEY_DELETE_VCENTER_SUCCESS' => xphp_get_lang('WEB_LOG_SYSTEM_DELETE_VCENTER_SUCCESS'),

    'VM_SYSTEM_LOG_PLATFORM_BACKUP_DONE' => xphp_get_lang('WEB_LOG_SYSTEM_PLATFORM_BACKUP_DONE'),
    'VM_SYSTEM_LOG_PLATFORM_BACKUP_FAILED' => xphp_get_lang('WEB_LOG_SYSTEM_PLATFORM_BACKUP_FAILED'),

    'VM_SYSTEMLOG_DESC_KEY_DEPLOY_VIRTUAL_LAB_SUCCESS' =>
        xphp_get_lang('WEB_LOG_SYSTEM_VM_DEPLOY_VIRTUAL_LAB_SUCCESS'),
    'VM_SYSTEMLOG_DESC_KEY_DEPLOY_VIRTUAL_LAB_ERROR' => xphp_get_lang('WEB_LOG_SYSTEM_VM_DEPLOY_VIRTUAL_LAB_ERROR'),

    'VM_SYSTEMLOG_DESC_KEY_DELETE_VIRTUAL_LAB_SUCCESS' =>
        xphp_get_lang('WEB_LOG_SYSTEM_VM_DELETE_VIRTUAL_LAB_SUCCESS'),
    'VM_SYSTEMLOG_DESC_KEY_DELETE_VIRTUAL_LAB_ERROR' => xphp_get_lang('WEB_LOG_SYSTEM_VM_DELETE_VIRTUAL_LAB_ERROR'),

    'VM_SYSTEMLOG_DESC_KEY_MODIFY_VIRTUAL_LAB_SUCCESS' =>
        xphp_get_lang('WEB_LOG_SYSTEM_VM_MODIFY_VIRTUAL_LAB_SUCCESS'),
    'VM_SYSTEMLOG_DESC_KEY_MODIFY_VIRTUAL_LAB_ERROR' => xphp_get_lang('WEB_LOG_SYSTEM_VM_MODIFY_VIRTUAL_LAB_ERROR'),

    'VM_SYSTEMLOG_DESC_KEY_REFRESH_VIRTUAL_LAB_SUCCESS' =>
        xphp_get_lang('WEB_LOG_SYSTEM_VM_REFRESH_VIRTUAL_LAB_SUCCESS'),
    'VM_SYSTEMLOG_DESC_KEY_REFRESH_VIRTUAL_LAB_ERROR' => xphp_get_lang('WEB_LOG_SYSTEM_VM_REFRESH_VIRTUAL_LAB_ERROR'),

    //***************副本*******************//
    'BD_SYSTEMLOG_DESC_KEY_REMOTE_STORAGE_ADD' => xphp_get_lang('WEB_LOG_SYSTEM_REMOTE_STORAGE_ADD'),
    'BACKUP_COPY_DESC_KEY_DO_RETENTION' => xphp_get_lang('WEB_LOG_TASK_DESC_KEY_BACKUP_COPY_DO_RETENTION'),
    'BACKUP_COPY_DESC_KEY_MERGE_TIMEPOINT' => xphp_get_lang('WEB_LOG_TASK_DESC_KEY_BACKUP_COPY_MERGE_TIMEPOINT'),
    'BACKUP_COPY_DESC_KEY_MERGE_TIMEPOINT_ERROR' =>
        xphp_get_lang('WEB_LOG_TASK_DESC_KEY_BACKUP_COPY_MERGE_TIMEPOINT_ERROR'),
    'BACKUP_COPY_DESC_KEY_TIMEPOINT_IS_MERGING' =>
        xphp_get_lang('WEB_LOG_TASK_DESC_KEY_BACKUP_COPY_TIMEPOINT_IS_MERGING'),

    'SYSTEMLOG_BACKUP_COPY_DESC_KEY_DO_RETENTION' => xphp_get_lang('WEB_LOG_SYSTEM_DESC_KEY_BACKUP_COPY_DO_RETENTION'),
    'SYSTEMLOG_BACKUP_COPY_DESC_KEY_MERGE_TIMEPOINT' =>
        xphp_get_lang('WEB_LOG_SYSTEM_DESC_KEY_BACKUP_COPY_MERGE_TIMEPOINT'),
    'SYSTEMLOG_BACKUP_COPY_DESC_KEY_MERGE_TIMEPOINT_ERROR' =>
        xphp_get_lang('WEB_LOG_SYSTEM_DESC_KEY_BACKUP_COPY_MERGE_TIMEPOINT_ERROR'),
    'SYSTEMLOG_BACKUP_COPY_DESC_KEY_TIMEPOINT_IS_MERGING' =>
        xphp_get_lang('WEB_LOG_SYSTEM_DESC_KEY_BACKUP_COPY_TIMEPOINT_IS_MERGING'),

    //***************CDP****没有开放到海外之前都使用中文,不用翻译***************//

    'SYSTEM_LOG_CDP_ADD_HOST' => xphp_get_lang('WEB_VOL_CDP_LOG_DESC_KEY_SYSTEM_LOG_CDP_ADD_HOST'),
    'SYSTEM_LOG_CDP_EDIT_HOST' => xphp_get_lang('WEB_VOL_CDP_LOG_DESC_KEY_SYSTEM_LOG_CDP_EDIT_HOST'),
    "SYSTEM_LOG_CDP_DELETE_HOST" => xphp_get_lang('WEB_VOL_CDP_LOG_DESC_KEY_SYSTEM_LOG_CDP_DELETE_HOST'),

    //多租户 (租户|用户组|角色|资源组|AD域)
    'SYSTEM_TENANT_ADD_SUCCESS' => xphp_get_lang('WEB_LOG_SYSTEM_TENANT_ADD_SUCCESS'),
    'SYSTEM_TENANT_DELETE_SUCCESS' => xphp_get_lang('WEB_LOG_SYSTEM_TENANT_DELETE_SUCCESS'),
    'SYSTEM_TENANT_UNLOCK_SUCCESS' => xphp_get_lang('WEB_LOG_SYSTEM_TENANT_UNLOCK_SUCCESS'),
    'SYSTEM_TENANT_LOCK_SUCCESS' => xphp_get_lang('WEB_LOG_SYSTEM_TENANT_LOCK_SUCCESS'),
    'SYSTEM_USER_GROUP_ADD_SUCCESS' => xphp_get_lang('WEB_LOG_SYSTEM_USER_GROUP_ADD_SUCCESS'),
    'SYSTEM_USER_GROUP_DELETE_SUCCESS' => xphp_get_lang('WEB_LOG_SYSTEM_USER_GROUP_DELETE_SUCCESS'),
    'SYSTEM_ROLE_ADD_SUCCESS' => xphp_get_lang('WEB_LOG_SYSTEM_ROLE_ADD_SUCCESS'),
    'SYSTEM_ROLE_DELETE_SUCCESS' => xphp_get_lang('WEB_LOG_SYSTEM_ROLE_DELETE_SUCCESS'),
    'SYSTEM_RESOURCE_GROUP_ADD_SUCCESS' => xphp_get_lang('WEB_LOG_SYSTEM_RESOURCE_GROUP_ADD_SUCCESS'),
    'SYSTEM_RESOURCE_GROUP_DELETE_SUCCESS' => xphp_get_lang('WEB_LOG_SYSTEM_RESOURCE_GROUP_DELETE_SUCCESS'),
    'SYSTEM_DOMAIN_ADD_SUCCESS' => xphp_get_lang('WEB_LOG_SYSTEM_DOMAIN_ADD_SUCCESS'),
    'SYSTEM_DOMAIN_DELETE_SUCCESS' => xphp_get_lang('WEB_LOG_SYSTEM_DOMAIN_DELETE_SUCCESS'),

    //系统备份恢复
    'SYSTEM_LOG_SYSBAKREC_AUTO_BACKUP_SYSTEM_SUCCESS' =>
        xphp_get_lang('WEB_LOG_SYSTEM_SYSBAKREC_AUTO_BACKUP_SYSTEM_SUCCESS'),
    'SYSTEM_LOG_SYSBAKREC_AUTO_BACKUP_SYSTEM_FAILURE1' =>
        xphp_get_lang('WEB_LOG_SYSTEM_SYSBAKREC_AUTO_BACKUP_SYSTEM_FAILURE1'),
    'SYSTEM_LOG_SYSBAKREC_AUTO_BACKUP_SYSTEM_FAILURE2' =>
        xphp_get_lang('WEB_LOG_SYSTEM_SYSBAKREC_AUTO_BACKUP_SYSTEM_FAILURE2'),
    'SYSTEM_LOG_SYSBAKREC_AUTO_BACKUP_SYSTEM_FAILURE3' =>
        xphp_get_lang('WEB_LOG_SYSTEM_SYSBAKREC_AUTO_BACKUP_SYSTEM_FAILURE3'),
    'SYSTEM_LOG_SYSBAKREC_AUTO_BACKUP_SYSTEM_FAILURE4' =>
        xphp_get_lang('WEB_LOG_SYSTEM_SYSBAKREC_AUTO_BACKUP_SYSTEM_FAILURE4'),
    'SYSTEM_LOG_SYSBAKREC_AUTO_BACKUP_SYSTEM_FAILURE5' =>
        xphp_get_lang('WEB_LOG_SYSTEM_SYSBAKREC_AUTO_BACKUP_SYSTEM_FAILURE5'),
    'SYSTEM_LOG_SYSBAKREC_USER_BACKUP_SYSTEM' => xphp_get_lang('WEB_LOG_SYSTEM_SYSBAKREC_USER_BACKUP_SYSTEM'),
    'SYSTEM_LOG_SYSBAKREC_RECOVERY_SYSTEM' => xphp_get_lang('WEB_LOG_SYSTEM_SYSBAKREC_RECOVERY_SYSTEM'),
    'SYSTEM_LOG_SYSBAKREC_SETTINGS' => xphp_get_lang('WEB_LOG_SYSTEM_SYSBAKREC_SETTINGS'),
    'SYSTEM_LOG_SYSBAKREC_DELETE_TIMEPOINT' => xphp_get_lang('WEB_LOG_SYSTEM_SYSBAKREC_DELETE_TIMEPOINT'),

    //系统配置-安全配置
    'SYSTEM_LOG_SETTINGS_ACCOUNT_SAFE' => xphp_get_lang('WEB_LOG_SYSTEM_SETTINGS_ACCOUNT_SAFE'),
    'SYSTEM_LOG_SETTINGS_STORAGE_SAFE_ON' => xphp_get_lang('WEB_LOG_SYSTEM_SETTINGS_STORAGE_SAFE_ON'),
    'SYSTEM_LOG_SETTINGS_STORAGE_SAFE_OFF' => xphp_get_lang('WEB_LOG_SYSTEM_SETTINGS_STORAGE_SAFE_OFF'),
    'SYSTEM_LOG_SETTINGS_OS_SAFE' => xphp_get_lang('WEB_LOG_SYSTEM_SETTINGS_OS_SAFE'),
    //系统配置-网络配置
    'SYSTEM_LOG_SETTINGS_DNS' => xphp_get_lang('WEB_LOG_SYSTEM_SETTINGS_DNS'),
    'SYSTEM_LOG_SETTINGS_NIC' => xphp_get_lang('WEB_LOG_SYSTEM_SETTINGS_NIC'),
    //GFS
    'VM_SYSTEMLOG_DESC_KEY_SET_TIMEPOINT_GFS_FLAG' => xphp_get_lang('WEB_SYSTEMLOG_DESC_KEY_SET_TIMEPOINT_GFS_FLAG'),
    'VM_SYSTEMLOG_DESC_KEY_UNSET_TIMEPOINT_GFS_FLAG' =>
        xphp_get_lang('WEB_SYSTEMLOG_DESC_KEY_UNSET_TIMEPOINT_GFS_FLAG'),

    //升级检测
    'SYSTEM_ALARM_UPDATE_ONLINE_SUCCESS' => xphp_get_lang('WEB_TIPS_SYSTEM_UPDATE_PACKAGE_TIP'),

    //卷cdp模块相关系统日志
    'VOL_CDP_LOG_DESC_KEY_SYSTEM_OP_DELETE_CONSISITENCY_LABEL' =>
        xphp_get_lang('WEB_VOL_CDP_LOG_DESC_KEY_SYSTEM_OP_DELETE_CONSISITENCY_LABEL'),
    'VOL_CDP_LOG_DESC_KEY_SYSTEM_OP_DELETE_ONE_BACKUPSET' =>
        xphp_get_lang('WEB_VOL_CDP_LOG_DESC_KEY_SYSTEM_OP_DELETE_ONE_BACKUPSET'),
    'VOL_CDP_LOG_DESC_KEY_SYSTEM_OP_DELETE_ONE_VOL_ALL_BACKUPSET' =>
        xphp_get_lang('WEB_VOL_CDP_LOG_DESC_KEY_SYSTEM_OP_DELETE_ONE_VOL_ALL_BACKUPSET'),
    'VOL_CDP_LOG_DESC_KEY_SYSTEM_OP_DELETE_ONE_AGENT_ALL_BACKUPSET' =>
        xphp_get_lang('WEB_VOL_CDP_LOG_DESC_KEY_SYSTEM_OP_DELETE_ONE_AGENT_ALL_BACKUPSET'),

    // 容灾演练平台
    'SYSTEM_LOG_EXERCISE_PLATFORM' => xphp_get_lang('UI_EXERCISE_PLATFORM_MSG'),

    // 任务编排计划
    'BD_SYSTEMLOG_DESC_KEY_ADD_TASK_ORCHESTRATION_PLAN' => xphp_get_lang('WEB_BD_SYSTEMLOG_DESC_KEY_ADD_TASK_ORCHESTRATION_PLAN'),
    'BD_SYSTEMLOG_DESC_KEY_MOD_TASK_ORCHESTRATION_PLAN' => xphp_get_lang('WEB_BD_SYSTEMLOG_DESC_KEY_MOD_TASK_ORCHESTRATION_PLAN'),
    'BD_SYSTEMLOG_DESC_KEY_DEL_TASK_ORCHESTRATION_PLAN' => xphp_get_lang('WEB_BD_SYSTEMLOG_DESC_KEY_DEL_TASK_ORCHESTRATION_PLAN'),
    'BD_SYSTEMLOG_DESC_KEY_START_TASK_ORCHESTRATION_PLAN' => xphp_get_lang('WEB_BD_SYSTEMLOG_DESC_KEY_START_TASK_ORCHESTRATION_PLAN'),
    'BD_SYSTEMLOG_DESC_KEY_STOP_TASK_ORCHESTRATION_PLAN' => xphp_get_lang('WEB_BD_SYSTEMLOG_DESC_KEY_STOP_TASK_ORCHESTRATION_PLAN'),
    'BD_SYSTEMLOG_DESC_KEY_ENABLE_TASK_ORCHESTRATION_PLAN' => xphp_get_lang('WEB_BD_SYSTEMLOG_DESC_KEY_ENABLE_TASK_ORCHESTRATION_PLAN'),

    //hadoop
    'PT_SYSTEMLOG_DESC_KEY_ADD_AUTH_TO_HADOOP_CLUSTER' => xphp_get_lang('WEB_PT_SYSTEMLOG_DESC_KEY_ADD_AUTH_TO_HADOOP_CLUSTER'),
    'PT_SYSTEMLOG_DESC_KEY_DEL_AUTH_FROM_HADOOP_CLUSTER' => xphp_get_lang('WEB_PT_SYSTEMLOG_DESC_KEY_DEL_AUTH_FROM_HADOOP_CLUSTER'),
    'FS_SYSTEMLOG_DESC_KEY_HADOOP_ADD_SUCCESS' => xphp_get_lang('WEB_LOG_HADOOP_FS_SYSTEMLOG_DESC_KEY_HADOOP_ADD_SUCCESS'),
    'FS_SYSTEMLOG_DESC_KEY_HADOOP_ADD_FAILED' => xphp_get_lang('WEB_LOG_HADOOP_FS_SYSTEMLOG_DESC_KEY_HADOOP_ADD_FAILED'),
    'FS_SYSTEMLOG_DESC_KEY_HADOOP_MODIFY_SUCCESS' => xphp_get_lang('WEB_LOG_HADOOP_FS_SYSTEMLOG_DESC_KEY_HADOOP_MODIFY_SUCCESS'),
    'FS_SYSTEMLOG_DESC_KEY_HADOOP_MODIFY_FAILED' => xphp_get_lang('WEB_LOG_HADOOP_FS_SYSTEMLOG_DESC_KEY_HADOOP_MODIFY_FAILED'),
    'FS_SYSTEMLOG_DESC_KEY_HADOOP_DELETE_SUCCESS' => xphp_get_lang('WEB_LOG_HADOOP_FS_SYSTEMLOG_DESC_KEY_HADOOP_DELETE_SUCCESS'),
    'FS_SYSTEMLOG_DESC_KEY_HADOOP_DELETE_FAILED' => xphp_get_lang('WEB_LOG_HADOOP_FS_SYSTEMLOG_DESC_KEY_HADOOP_DELETE_FAILED'),
    'FS_SYSTEMLOG_DESC_KEY_HADOOP_REFRESH_SUCCESS' => xphp_get_lang('WEB_LOG_HADOOP_FS_SYSTEMLOG_DESC_KEY_HADOOP_REFRESH_SUCCESS'),
    'FS_SYSTEMLOG_DESC_KEY_HADOOP_REFRESH_FAILED' => xphp_get_lang('WEB_LOG_HADOOP_FS_SYSTEMLOG_DESC_KEY_HADOOP_REFRESH_FAILED'),

    // obs
    'FS_SYSTEMLOG_DESC_KEY_OBS_OP' => xphp_get_lang('WEB_FS_SYSTEMLOG_DESC_KEY_OBS_OP'),
    'FS_SYSTEMLOG_DESC_KEY_OBS_ADD' => xphp_get_lang('WEB_FS_SYSTEMLOG_DESC_KEY_OBS_ADD'),
    'FS_SYSTEMLOG_DESC_KEY_OBS_MODIFY' => xphp_get_lang('WEB_FS_SYSTEMLOG_DESC_KEY_OBS_MODIFY'),
    'FS_SYSTEMLOG_DESC_KEY_OBS_DELETE' => xphp_get_lang('WEB_FS_SYSTEMLOG_DESC_KEY_OBS_DELETE'),
    'FS_SYSTEMLOG_DESC_KEY_OBS_REFRESH' => xphp_get_lang('WEB_FS_SYSTEMLOG_DESC_KEY_OBS_REFRESH'),
    'PT_SYSTEMLOG_DESC_KEY_ADD_AUTH_TO_OBS' => xphp_get_lang('WEB_PT_SYSTEMLOG_DESC_KEY_ADD_AUTH_TO_OBS'),
    'PT_SYSTEMLOG_DESC_KEY_DEL_AUTH_FROM_OBS' => xphp_get_lang('WEB_PT_SYSTEMLOG_DESC_KEY_DEL_AUTH_FROM_OBS'),
);