<?php

return [
    'ClusterLog' => [
        'BD_CLUSTER_LOG_DESC_KEY_START_CLUSTER' => 'WEB_BD_CLUSTER_LOG_DESC_KEY_START_CLUSTER',
        'BD_CLUSTER_LOG_DESC_KEY_START_CLUSTER_SUCCESS' => 'WEB_BD_CLUSTER_LOG_DESC_KEY_START_CLUSTER_SUCCESS',
        'BD_CLUSTER_LOG_DESC_KEY_START_CLUSTER_FAILURE' => 'WEB_BD_CLUSTER_LOG_DESC_KEY_START_CLUSTER_FAILURE',
        'BD_CLUSTER_LOG_DESC_KEY_STOP_CLUSTER' => 'WEB_BD_CLUSTER_LOG_DESC_KEY_STOP_CLUSTER',
        'BD_CLUSTER_LOG_DESC_KEY_STOP_CLUSTER_SUCCESS' => 'WEB_BD_CLUSTER_LOG_DESC_KEY_STOP_CLUSTER_SUCCESS',
        'BD_CLUSTER_LOG_DESC_KEY_STOP_CLUSTER_FAILURE' => 'WEB_BD_CLUSTER_LOG_DESC_KEY_STOP_CLUSTER_FAILURE',
        'BD_CLUSTER_LOG_DESC_KEY_SWITCH_CLUSTER' => 'WEB_BD_CLUSTER_LOG_DESC_KEY_SWITCH_CLUSTER',
        'BD_CLUSTER_LOG_DESC_KEY_SWITCH_CLUSTER_SUCCESS' => 'WEB_BD_CLUSTER_LOG_DESC_KEY_SWITCH_CLUSTER_SUCCESS',
        'BD_CLUSTER_LOG_DESC_KEY_SWITCH_CLUSTER_FAILURE' => 'WEB_BD_CLUSTER_LOG_DESC_KEY_SWITCH_CLUSTER_FAILURE',
        'BD_CLUSTER_LOG_DESC_KEY_INSPECT_CLUSTER_START_CONDITION' => 'WEB_BD_CLUSTER_LOG_DESC_KEY_INSPECT_CLUSTER_START_CONDITION',
        'BD_CLUSTER_LOG_DESC_KEY_SYNC_LICENSE_INFO' => 'WEB_BD_CLUSTER_LOG_DESC_KEY_SYNC_LICENSE_INFO',
        'BD_CLUSTER_LOG_DESC_KEY_MODIFY_AGENT_CONFIG' => 'WEB_BD_CLUSTER_LOG_DESC_KEY_MODIFY_AGENT_CONFIG',

        //接管相关
        'BD_CLUSTER_LOG_DESC_KEY_TAKEOVER_CLUSTER' => 'WEB_BD_CLUSTER_LOG_DESC_KEY_TAKEOVER_CLUSTER',
        'BD_CLUSTER_LOG_DESC_KEY_TAKEOVER_CLUSTER_SUCCESS' => 'WEB_BD_CLUSTER_LOG_DESC_KEY_TAKEOVER_CLUSTER_SUCCESS',
        'BD_CLUSTER_LOG_DESC_KEY_TAKEOVER_CLUSTER_FAILURE' => 'WEB_BD_CLUSTER_LOG_DESC_KEY_TAKEOVER_CLUSTER_FAILURE',
        'BD_CLUSTER_LOG_DESC_KEY_START_ADD_NODE' => 'WEB_BD_CLUSTER_LOG_DESC_KEY_START_ADD_NODE',
        'BD_CLUSTER_LOG_DESC_KEY_ADD_NODE_SUCCESS' => 'WEB_BD_CLUSTER_LOG_DESC_KEY_ADD_NODE_SUCCESS',
        'BD_CLUSTER_LOG_DESC_KEY_ADD_NODE_FAILURE' => 'WEB_BD_CLUSTER_LOG_DESC_KEY_ADD_NODE_FAILURE',

        //操作数据库同步组件
        'BD_CLUSTER_LOG_DESC_KEY_START_DBPROXY_COMPONENT_SUCCESS' => 'WEB_BD_CLUSTER_LOG_DESC_KEY_START_DBPROXY_COMPONENT_SUCCESS',
        'BD_CLUSTER_LOG_DESC_KEY_START_DBPROXY_COMPONENT_FAILURE' => 'WEB_BD_CLUSTER_LOG_DESC_KEY_START_DBPROXY_COMPONENT_FAILURE',
        'BD_CLUSTER_LOG_DESC_KEY_STOP_DBPROXY_COMPONENT_SUCCESS' => 'WEB_BD_CLUSTER_LOG_DESC_KEY_STOP_DBPROXY_COMPONENT_SUCCESS',
        'BD_CLUSTER_LOG_DESC_KEY_STOP_DBPROXY_COMPONENT_FAILURE' => 'WEB_BD_CLUSTER_LOG_DESC_KEY_STOP_DBPROXY_COMPONENT_FAILURE',

        //操作高可用组件
        'BD_CLUSTER_LOG_DESC_KEY_START_HA_COMPONENT_SUCCESS' => 'WEB_BD_CLUSTER_LOG_DESC_KEY_START_HA_COMPONENT_SUCCESS',
        'BD_CLUSTER_LOG_DESC_KEY_START_HA_COMPONENT_FAILURE' => 'WEB_BD_CLUSTER_LOG_DESC_KEY_START_HA_COMPONENT_FAILURE',
        'BD_CLUSTER_LOG_DESC_KEY_STOP_HA_COMPONENT_SUCCESS' => 'WEB_BD_CLUSTER_LOG_DESC_KEY_STOP_HA_COMPONENT_SUCCESS',
        'BD_CLUSTER_LOG_DESC_KEY_STOP_HA_COMPONENT_FAILURE' => 'WEB_BD_CLUSTER_LOG_DESC_KEY_STOP_HA_COMPONENT_FAILURE',

        //操作web服务组件
        'BD_CLUSTER_LOG_DESC_KEY_START_WEB_COMPONENT_SUCCESS' => 'WEB_BD_CLUSTER_LOG_DESC_KEY_START_WEB_COMPONENT_SUCCESS',
        'BD_CLUSTER_LOG_DESC_KEY_START_WEB_COMPONENT_FAILURE' => 'WEB_BD_CLUSTER_LOG_DESC_KEY_START_WEB_COMPONENT_FAILURE',
        'BD_CLUSTER_LOG_DESC_KEY_STOP_WEB_COMPONENT_SUCCESS' => 'WEB_BD_CLUSTER_LOG_DESC_KEY_STOP_WEB_COMPONENT_SUCCESS',
        'BD_CLUSTER_LOG_DESC_KEY_STOP_WEB_COMPONENT_FAILURE' => 'WEB_BD_CLUSTER_LOG_DESC_KEY_STOP_WEB_COMPONENT_FAILURE',
        'BD_CLUSTER_LOG_DESC_KEY_RESTART_WEB_COMPONENT_SUCCESS' => 'WEB_BD_CLUSTER_LOG_DESC_KEY_RESTART_WEB_COMPONENT_SUCCESS',
        'BD_CLUSTER_LOG_DESC_KEY_RESTART_WEB_COMPONENT_FAILURE' => 'WEB_BD_CLUSTER_LOG_DESC_KEY_RESTART_WEB_COMPONENT_FAILURE',

        //操作备份服务组件
        'BD_CLUSTER_LOG_DESC_KEY_RESTART_BACKUP_COMPONENT_SUCCESS' => 'WEB_BD_CLUSTER_LOG_DESC_KEY_RESTART_BACKUP_COMPONENT_SUCCESS',
        'BD_CLUSTER_LOG_DESC_KEY_RESTART_BACKUP_COMPONENT_FAILURE' => 'WEB_BD_CLUSTER_LOG_DESC_KEY_RESTART_BACKUP_COMPONENT_FAILURE',

        // 数据库同步
        'BD_CLUSTER_LOG_DESC_KEY_START_DATABASE_FULL_SYNC' => 'WEB_BD_CLUSTER_LOG_DESC_KEY_START_DATABASE_FULL_SYNC',
        'BD_CLUSTER_LOG_DESC_KEY_START_DATABASE_FULL_SYNC_SUCCESS' => 'WEB_BD_CLUSTER_LOG_DESC_KEY_START_DATABASE_FULL_SYNC_SUCCESS',
        'BD_CLUSTER_LOG_DESC_KEY_START_DATABASE_FULL_SYNC_FAILURE' => 'WEB_BD_CLUSTER_LOG_DESC_KEY_START_DATABASE_FULL_SYNC_FAILURE',
        'BD_CLUSTER_LOG_DESC_KEY_START_DATABASE_REALTIME_SYNC' => 'WEB_BD_CLUSTER_LOG_DESC_KEY_START_DATABASE_REALTIME_SYNC',
        'BD_CLUSTER_LOG_DESC_KEY_START_DATABASE_REALTIME_SYNC_SUCCESS' => 'WEB_BD_CLUSTER_LOG_DESC_KEY_START_DATABASE_REALTIME_SYNC_SUCCESS',
        'BD_CLUSTER_LOG_DESC_KEY_START_DATABASE_REALTIME_SYNC_FAILURE' => 'WEB_BD_CLUSTER_LOG_DESC_KEY_START_DATABASE_REALTIME_SYNC_FAILURE',
    ],
];