<?php

/**
 *数据库实时模块描述定义
 *TODO 每一个定义都关联语言文件
 */

return array(
    //事件信息
    'DbCdpEventDes' => array(
        'DB_CDP_LOG_DESC_KEY_REPLAY_LOG' => xphp_get_lang('WEB_DB_CDP_LOG_DESC_KEY_REPLAY_LOG'),
        //1.10 事件信息说明
        'DB_CDP_LOG_DESC_KEY_LINUX_OS_SOFTWARE_INSTALL' => xphp_get_lang('WEB_DB_CDP_LOG_DESC_KEY_LINUX_OS_SOFTWARE_INSTALL'),
        'DB_CDP_LOG_DESC_KEY_LINUX_OS_SOFTWARE_UNINSTALL' => xphp_get_lang('WEB_DB_CDP_LOG_DESC_KEY_LINUX_OS_SOFTWARE_UNINSTALL'),
        'DB_CDP_LOG_DESC_KEY_LINUX_OS_SOFTWARE_UPDATE' => xphp_get_lang('WEB_DB_CDP_LOG_DESC_KEY_LINUX_OS_SOFTWARE_UPDATE'),
        'DB_CDP_LOG_DESC_KEY_LINUX_OS_SERVICE_START' => xphp_get_lang('WEB_DB_CDP_LOG_DESC_KEY_LINUX_OS_SERVICE_START'),
        'DB_CDP_LOG_DESC_KEY_LINUX_OS_SERVICE_STOP' => xphp_get_lang('WEB_DB_CDP_LOG_DESC_KEY_LINUX_OS_SERVICE_STOP'),
        'DB_CDP_LOG_DESC_KEY_LINUX_OS_ADD_USER' => xphp_get_lang('WEB_DB_CDP_LOG_DESC_KEY_LINUX_OS_ADD_USER'),
        'DB_CDP_LOG_DESC_KEY_LINUX_OS_DEL_USER' => xphp_get_lang('WEB_DB_CDP_LOG_DESC_KEY_LINUX_OS_DEL_USER'),
        'DB_CDP_LOG_DESC_KEY_LINUX_OS_ADD_GROUP' => xphp_get_lang('WEB_DB_CDP_LOG_DESC_KEY_LINUX_OS_ADD_GROUP'),
        'DB_CDP_LOG_DESC_KEY_LINUX_OS_DEL_GROUP' => xphp_get_lang('WEB_DB_CDP_LOG_DESC_KEY_LINUX_OS_DEL_GROUP'),
        'DB_CDP_LOG_DESC_KEY_LINUX_OS_MAC_STATUS' => xphp_get_lang('WEB_DB_CDP_LOG_DESC_KEY_LINUX_OS_MAC_STATUS'),
        'DB_CDP_LOG_DESC_KEY_LINUX_OS_SYSTEM_RUNLEVEL' => xphp_get_lang('WEB_DB_CDP_LOG_DESC_KEY_LINUX_OS_SYSTEM_RUNLEVEL'),
        'DB_CDP_LOG_DESC_KEY_LINUX_OS_CHUSER_ID' => xphp_get_lang('WEB_DB_CDP_LOG_DESC_KEY_LINUX_OS_CHUSER_ID'),
        'DB_CDP_LOG_DESC_KEY_LINUX_OS_CHGRP_ID' => xphp_get_lang('WEB_DB_CDP_LOG_DESC_KEY_LINUX_OS_CHGRP_ID'),
        'DB_CDP_LOG_DESC_KEY_LINUX_OS_SYSTEM_BOOT' => xphp_get_lang('WEB_DB_CDP_LOG_DESC_KEY_LINUX_OS_SYSTEM_BOOT'),
        'DB_CDP_LOG_DESC_KEY_LINUX_OS_SYSTEM_SHUTDOWN' => xphp_get_lang('WEB_DB_CDP_LOG_DESC_KEY_LINUX_OS_SYSTEM_SHUTDOWN'),
        'DB_CDP_LOG_DESC_KEY_LINUX_OS_USER_CHAUTHTOK' => xphp_get_lang('WEB_DB_CDP_LOG_DESC_KEY_LINUX_OS_USER_CHAUTHTOK'),
        'DB_CDP_LOG_DESC_KEY_DATABASE_ONLINE' => xphp_get_lang('WEB_DB_CDP_LOG_DESC_KEY_DATABASE_ONLINE'),
        'DB_CDP_LOG_DESC_KEY_DATABASE_OFFLINE' => xphp_get_lang('WEB_DB_CDP_LOG_DESC_KEY_DATABASE_OFFLINE'),
    )
);
