<?php
/******************************************* 
 ** 系统日志描述配置信息
 ** 
 ** @author       xiezhuowei@vinchin.com 
 ** @date         2015-06-06 下午15:16:44 
 ** @version      1.0.0 
 ** @copyright    Copyright 2015 vinchin.com 
 ********************************************/

return array(
    //***************WEB******************//
    'SYSTEM_USER_ADD_SUCCESS' => Xphp::$_lang['WEB_LOG_SYSTEM_ADD_SUCCESS'],
    'SYSTEM_USER_LOGIN_SUCCESS' => Xphp::$_lang['WEB_LOG_SYSTEM_LOGIN_SUCCESS'],
    'SYSTEM_USER_LOGIN_FAILURE' => Xphp::$_lang['WEB_LOG_SYSTEM_LOGIN_FAILURE'],
    'SYSTEM_USER_LOCK_SUCCESS' => Xphp::$_lang['WEB_LOG_SYSTEM_LOCK_SUCCESS'],
    'SYSTEM_USER_LOCK_FAILURE' => Xphp::$_lang['WEB_LOG_SYSTEM_LOCK_FAILURE'],
    'SYSTEM_USER_UNLOCK_SUCCESS' => Xphp::$_lang['WEB_LOG_SYSTEM_UNLOCK_SUCCESS'],
    'SYSTEM_USER_DELETE_SUCCESS' => Xphp::$_lang['WEB_LOG_SYSTEM_DELETE_SUCCESS'],
    'SYSTEM_USER_DELETE_FIALURE' => Xphp::$_lang['WEB_LOG_SYSTEM_DELETE_FIALURE'],
    'SYSTEM_USER_EDIT_PASSWORD_SUCCESS' => Xphp::$_lang['WEB_LOG_SYSTEM_EDIT_PASSWORD_SUCCESS'],
    'SYSTEM_USER_EDIT_INFO_SUCCESS' => Xphp::$_lang['WEB_LOG_SYSTEM_EDIT_INFO_SUCCESS'],
    'SYSTEM_USER_MODIFY_SUCCESS' => Xphp::$_lang['WEB_LOG_SYSTEM_USER_MODIFY_SUCCESS'],

    'SYSTEM_SETTING_IP' => Xphp::$_lang['WEB_LOG_SYSTEM_SETTING_IP'],
    'SYSTEM_SETTING_TIME' => Xphp::$_lang['WEB_LOG_SYSTEM_SETTING_TIME'],
    'SYSTEM_SETTING_SYSTEM_NAME' => Xphp::$_lang['WEB_LOG_SYSTEM_SETTING_SYSTEM_NAME'],
    'SYSTEM_SETTING_LOGO' => Xphp::$_lang['WEB_LOG_SYSTEM_SETTING_LOGO'],
    'SYSTEM_SETTING_EXPORT_DATA' => Xphp::$_lang['WEB_LOG_SYSTEM_SETTING_EXPORT_DATA'],
    'SYSTEM_SETTING_IMPORT_DATA' => Xphp::$_lang['WEB_LOG_SYSTEM_SETTING_IMPORT_DATA'],
    'SYSTEM_SETTING_EMAIL_NOTICE' => Xphp::$_lang['WEB_LOG_SYSTEM_SETTING_EMAIL_NOTICE'],
    'SYSTEM_SETTING_SMS_NOTICE' => Xphp::$_lang['WEB_LOG_SYSTEM_SETTING_SMS_NOTICE'],

    'SYSTEM_SETTING_POWER_OFF' => Xphp::$_lang['WEB_LOG_SYSTEM_PT_OP_POWEROFF_NODE'],
    'SYSTEM_SETTING_REBOOT' => Xphp::$_lang['WEB_LOG_SYSTEM_PT_OP_RESTART_NODE'],

    //
    'SYSTEM_SETTING_CONFIG_MESSAGE_PUSH' => Xphp::$_lang['WEB_LOG_SYSTEM_SETTING_CONFIG_MESSAGE_PUSH'],
    'SYSTEM_SETTING_CONFIG_VISUAL_NAME' => Xphp::$_lang['WEB_LOG_SYSTEM_SETTING_CONFIG_VISUAL_NAME'],


    'SYSTEM_LOG_DESC_KEY_PROXY_ADD' => Xphp::$_lang['WEB_LOG_SYSTEM_DESC_KEY_PROXY_ADD'],
    'SYSTEM_LOG_DESC_KEY_PROXY_EDIT' => Xphp::$_lang['WEB_LOG_SYSTEM_DESC_KEY_PROXY_EDIT'],
    'SYSTEM_LOG_DESC_KEY_PROXY_DELETE' => Xphp::$_lang['WEB_LOG_SYSTEM_DESC_KEY_PROXY_DELETE'],

    'SYSTEM_LOG_DESC_KEY_ADD_STRATEGY' => Xphp::$_lang['WEB_LOG_SYSTEM_DESC_KEY_ADD_STRATEGY'],
    'SYSTEM_LOG_DESC_KEY_EDIT_STRATEGY' => Xphp::$_lang['WEB_LOG_SYSTEM_DESC_KEY_EDIT_STRATEGY'],
    'SYSTEM_LOG_DESC_KEY_DELETE_STRATEGY' => Xphp::$_lang['WEB_LOG_SYSTEM_DESC_KEY_DELETE_STRATEGY'],

    //副本
    'SYSTEM_LOG_DELETE_COPY_BATCH_TIMEPOINT' => Xphp::$_lang['WEB_LOG_SYSTEM_DELETE_COPY_BATCH_TIMEPOINT'],
    'SYSTEM_LOG_DELETE_COPY_ONE_TIMEPOINT' => Xphp::$_lang['WEB_LOG_SYSTEM_DELETE_COPY_ONE_TIMEPOINT'],

    //归档
    'SYSTEM_LOG_DELETE_ARCHIVE_BATCH_TIMEPOINT' => Xphp::$_lang['WEB_LOG_SYSTEM_DELETE_ARCHIVE_BATCH_TIMEPOINT'],
    'SYSTEM_LOG_DELETE_ARCHIVE_ONE_TIMEPOINT' => Xphp::$_lang['WEB_LOG_SYSTEM_DELETE_ARCHIVE_ONE_TIMEPOINT'],

    //文件
    'SYSTEM_LOG_DELETE_FILE_ONE_TIMEPOINT' => Xphp::$_lang['WEB_LOG_SYSTEM_DELETE_FILE_ONE_TIMEPOINT'],
    'SYSTEM_LOG_ADD_FILE_AGENT_AUTH' => Xphp::$_lang['WEB_LOG_SYSTEM_ADD_FILE_AGENT_AUTH'],
    'SYSTEM_LOG_EDIT_FILE_AGENT_AUTH' => Xphp::$_lang['WEB_LOG_SYSTEM_EDIT_FILE_AGENT_AUTH'],
    'SYSTEM_LOG_DELETE_FILE_AGENT' => Xphp::$_lang['WEB_LOG_SYSTEM_DELETE_FILE_AGENT'],
    'SYSTEM_LOG_DELETE_OFFLINE_FILE_AGENT' => Xphp::$_lang['WEB_LOG_SYSTEM_DELETE_OFFLINE_FILE_AGENT'],

    //NAS
    'BD_SYSTEMLOG_DESC_KEY_NAS_ADD' => Xphp::$_lang['WEB_LOG_SYSTEM_BD_SYSTEMLOG_DESC_KEY_NAS_ADD'],
    'BD_SYSTEMLOG_DESC_KEY_NAS_DELETE' => Xphp::$_lang['WEB_LOG_SYSTEM_BD_SYSTEMLOG_DESC_KEY_NAS_DELETE'],
    'BD_SYSTEMLOG_DESC_KEY_NAS_UMOUNT' => Xphp::$_lang['WEB_LOG_SYSTEM_BD_SYSTEMLOG_DESC_KEY_NAS_UMOUNT'],
    'BD_SYSTEMLOG_DESC_KEY_NAS_MOUNT' => Xphp::$_lang['WEB_LOG_SYSTEM_BD_SYSTEMLOG_DESC_KEY_NAS_MOUNT'],
    'BD_SYSTEMLOG_DESC_KEY_NAS_MODIFY' => Xphp::$_lang['WEB_LOG_SYSTEM_BD_SYSTEMLOG_DESC_KEY_NAS_MODIFY'],

    //日志
    'SYSTEM_LOG_DELETE_TASK_LOG' => Xphp::$_lang['WEB_LOG_SYSTEM_DELETE_TASK_LOG'],
    'SYSTEM_LOG_DELETE_SYSTEM_LOG' => Xphp::$_lang['WEB_LOG_SYSTEM_DELETE_SYSTEM_LOG'],

    //告警
    'SYSTEM_LOG_DELETE_TASK_ALARM' => Xphp::$_lang['WEB_LOG_SYSTEM_DELETE_TASK_ALARM'],
    'SYSTEM_LOG_DELETE_SYSTEM_ALARM' => Xphp::$_lang['WEB_LOG_SYSTEM_DELETE_SYSTEM_ALARM'],

    'SYSTEM_LOG_DELETE_BATCH_TIMEPOINT' => Xphp::$_lang['WEB_LOG_SYSTEM_DELETE_BATCH_TIMEPOINT'],
    'SYSTEM_LOG_DELETE_ONE_TIMEPOINT' => Xphp::$_lang['WEB_LOG_SYSTEM_DELETE_ONE_TIMEPOINT'],
    'SYSTEM_LOG_DELETE_ONE_OS_TIMEPOINT' => Xphp::$_lang['WEB_LOG_SYSTEM_DELETE_ONE_OS_TIMEPOINT'],
    'SYSTEM_LOG_TIMEPOINT_REMARK' => Xphp::$_lang['WEB_LOG_SYSTEM_TIMEPOINT_REMARK'],
    'SYSTEM_LOG_TIMEPOINT_STAR' => Xphp::$_lang['WEB_LOG_SYSTEM_TIMEPOINT_STAR'],
    'SYSTEM_LOG_TIMEPOINT_UNSTAR' => Xphp::$_lang['WEB_LOG_SYSTEM_TIMEPOINT_UNSTAR'],
    'SYSTEM_LOG_EXCEED_ALARM_VALUE_CPU' => Xphp::$_lang['WEB_LOG_EXCEED_ALARM_VALUE_CPU'],
    'SYSTEM_LOG_EXCEED_ALARM_VALUE_RAM' => Xphp::$_lang['WEB_LOG_EXCEED_ALARM_VALUE_RAM'],
    'SYSTEM_LOG_EXCEED_ALARM_VALUE_RPS' => Xphp::$_lang['WEB_LOG_EXCEED_ALARM_VALUE_RPS'],

    //数据库
    'SYSTEM_LOG_ADD_DB_AGENT' => Xphp::$_lang['WEB_LOG_SYSTEM_ADD_DB_AGENT'],
    'SYSTEM_LOG_MODIFY_DB_AGENT' => Xphp::$_lang['WEB_LOG_SYSTEM_MODIFY_DB_AGENT'],
    'SYSTEM_LOG_DELETE_DB_AGENT' => Xphp::$_lang['WEB_LOG_SYSTEM_DELETE_DB_AGENT'],
    'SYSTEM_LOG_ADD_DB_AGENT_AUTH' => Xphp::$_lang['WEB_LOG_SYSTEM_ADD_DB_AGENT_AUTH'],
    'SYSTEM_LOG_EDIT_DB_AGENT_AUTH' => Xphp::$_lang['WEB_LOG_SYSTEM_EDIT_DB_AGENT_AUTH'],
    'SYSTEM_LOG_CANCEL_DB_AGENT_AUTH' => Xphp::$_lang['WEB_LOG_SYSTEM_CANCEL_DB_AGENT_AUTH'],
    'SYSTEM_LOG_DELETE_ONE_DB_TIMEPOINT' => Xphp::$_lang['WEB_LOG_SYSTEM_DELETE_ONE_DB_TIMEPOINT'],
    'SYSTEM_LOG_DB_AUTH_INSTANCE' => Xphp::$_lang['WEB_LOG_SYSTEM_DB_AUTH_INSTANCE'],


    //***************PF*******************//
    'BD_SYSTEMLOG_DESC_KEY_AGENT_ONLINE' => Xphp::$_lang['WEB_LOG_SYSTEM_AGENT_ONLINE'],
    'BD_SYSTEMLOG_DESC_KEY_AGENT_OFFLINE' => Xphp::$_lang['WEB_LOG_SYSTEM_AGENT_OFFLINE'],
    'BD_SYSTEMLOG_DESC_KEY_DEL_TIMEPOINT_SUCCESS' => Xphp::$_lang['WEB_LOG_SYSTEM_DEL_TIMEPOINT_SUCCESS'],
    'BD_SYSTEMLOG_DESC_KEY_DELETE_TIMEPOINT' => Xphp::$_lang['WEB_LOG_SYSTEM_BD_SYSTEMLOG_DESC_KEY_DELETE_TIMEPOINT'],
    'BD_SYSTEMLOG_DESC_KEY_DELETE_TIMEPOINT_IN_BATCH' => Xphp::$_lang['WEB_LOG_SYSTEM_BD_SYSTEMLOG_DESC_KEY_DELETE_TIMEPOINT_IN_BATCH'],
    'BD_SYSTEMLOG_DESC_KEY_MARK_TIMEPOINT_SUCCESS' => Xphp::$_lang['WEB_LOG_SYSTEM_MARK_TIMEPOINT_SUCCESS'],
    'BD_SYSTEMLOG_DESC_KEY_UNMARK_TIMEPOINT_SUCCESS' => Xphp::$_lang['WEB_LOG_SYSTEM_UNMARK_TIMEPOINT_SUCCESS'],
    'BD_SYSTEMLOG_DESC_KEY_COMMENT_TIMEPOINT_SUCCESS' => Xphp::$_lang['WEB_LOG_SYSTEM_COMMENT_TIMEPOINT_SUCCESS'],
    'BD_SYSTEMLOG_DESC_KEY_ADD_AUTHORIZE_SUCCESS' => Xphp::$_lang['WEB_LOG_SYSTEM_ADD_AUTHORIZE_SUCCESS'],
    'BD_SYSTEMLOG_DESC_KEY_MODIFY_AUTHORIZE_SUCCESS' => Xphp::$_lang['WEB_LOG_SYSTEM_MODIFY_AUTHORIZE_SUCCESS'],
    'BD_SYSTEMLOG_DESC_KEY_MODIFY_SYSTEM_TIME_SUCCESS' => Xphp::$_lang['WEB_LOG_SYSTEM_MODIFY_SYSTEM_TIME_SUCCESS'],
    'BD_SYSTEMLOG_DESC_KEY_UPDATE_SYSTEM_SUCCESS' => Xphp::$_lang['WEB_LOG_SYSTEM_UPDATE_SYSTEM_SUCCESS'],

    'BD_SYSTEMLOG_DESC_KEY_SYS_AUTH_ABNORMAL_BY_ENV_CHANGE' => Xphp::$_lang['WEB_LOG_SYSTEM_SYS_AUTH_ABNORMAL_BY_ENV_CHANGE'],
    'BD_SYSTEMLOG_DESC_KEY_SYS_AUTH_ABNORMAL_KEY_IS_INVALID' => Xphp::$_lang['WEB_LOG_SYSTEM_SYS_AUTH_ABNORMAL_KEY_IS_INVALID'],
    'BD_SYSTEMLOG_DESC_KEY_SYS_AUTH_ABNORMAL' => Xphp::$_lang['WEB_LOG_SYSTEM_SYS_AUTH_ABNORMAL'],
    'BD_SYSTEMLOG_DESC_KEY_SYS_AUTH_EXHAUST' => Xphp::$_lang['WEB_LOG_SYSTEM_SYS_AUTH_EXHAUST'],

    //节点名字[IP]
    'BD_SYSTEMLOG_DESC_KEY_NODE_CONNECT' => Xphp::$_lang['WEB_LOG_SYSTEM_NODE_CONNECT'],
    'BD_SYSTEMLOG_DESC_KEY_NODE_ABNORMAL' => Xphp::$_lang['WEB_LOG_SYSTEM_NODE_ABNORMAL'],
    'BD_SYSTEMLOG_DESC_KEY_NODE_OFFLINE' => Xphp::$_lang['WEB_LOG_SYSTEM_NODE_OFFLINE'],
    'BD_SYSTEMLOG_DESC_KEY_NODE_MODIFY' => Xphp::$_lang['WEB_LOG_SYSTEM_NODE_MODIFY'],
    'BD_SYSTEMLOG_DESC_KEY_NODE_DELETE' => Xphp::$_lang['WEB_LOG_SYSTEM_NODE_DELETE'],
    'BD_SYSTEMLOG_DESC_KEY_MASTER_NODE_ABNORMAL' => Xphp::$_lang['WEB_LOG_SYSTEM_MASTER_NODE_ABNORMAL'],
    /*-----------------------------------------------for agent op---------------------------------------------------------*/
    'BD_SYSTEMLOG_DESC_KEY_AGENT_ADD' => Xphp::$_lang['WEB_LOG_SYSTEM_AGENT_ADD'],
    'BD_SYSTEMLOG_DESC_KEY_AGENT_REFRESH' => Xphp::$_lang['WEB_LOG_SYSTEM_AGENT_REFRESH'],
    'BD_SYSTEMLOG_DESC_KEY_AGENT_DELETE' => Xphp::$_lang['WEB_LOG_SYSTEM_AGENT_DELETE'],
    'BD_SYSTEMLOG_DESC_KEY_AGENT_MODIFY' => Xphp::$_lang['WEB_LOG_SYSTEM_AGENT_MODIFY'],
    'BD_SYSTEMLOG_DESC_KEY_AGENT_UPGRADE' => Xphp::$_lang['WEB_LOG_SYSTEM_AGENT_UPGRADE'],
    // 代理
    'BD_SYSTEMLOG_DESC_KEY_AGENT_PROXY_ADD' => Xphp::$_lang['WEB_LOG_SYSTEM_AGENT_PROXY_ADD'],
    'BD_SYSTEMLOG_DESC_KEY_AGENT_PROXY_REFRESH' => Xphp::$_lang['WEB_LOG_SYSTEM_AGENT_PROXY_REFRESH'],
    'BD_SYSTEMLOG_DESC_KEY_AGENT_PROXY_DELETE' => Xphp::$_lang['WEB_LOG_SYSTEM_AGENT_PROXY_DELETE'],
    'BD_SYSTEMLOG_DESC_KEY_AGENT_PROXY_MODIFY' => Xphp::$_lang['WEB_LOG_SYSTEM_AGENT_PROXY_MODIFY'],
    'BD_SYSTEMLOG_DESC_KEY_AGENT_PROXY_UPGRADE' => Xphp::$_lang['WEB_LOG_SYSTEM_AGENT_PROXY_UPGRADE'],

    //存储名[存储类型]  节点名[节点IP]
    'BD_SYSTEMLOG_DESC_KEY_STORAGE_ADD' => Xphp::$_lang['WEB_LOG_SYSTEM_STORAGE_ADD'],
    'BD_SYSTEMLOG_DESC_KEY_STORAGE_EDIT' => Xphp::$_lang['WEB_LOG_SYSTEM_STORAGE_EDIT'],
    'BD_SYSTEMLOG_DESC_KEY_STORAGE_DELETE' => Xphp::$_lang['WEB_LOG_SYSTEM_STORAGE_DELETE'],
    'BD_SYSTEMLOG_DESC_KEY_STORAGE_IMPORT_DATA' => Xphp::$_lang['WEB_LOG_SYSTEM_STORAGE_IMPORT_DATA'],
    'BD_SYSTEMLOG_DESC_KEY_STORAGE_ABNORMAL' => Xphp::$_lang['WEB_LOG_SYSTEM_STORAGE_ABNORMAL'],
    'BD_SYSTEMLOG_DESC_KEY_STORAGE_OFFLINE' => Xphp::$_lang['WEB_LOG_SYSTEM_STORAGE_OFFLINE'],
    'BD_SYSTEMLOG_DESC_KEY_STORAGE_SPACE_LACK' => Xphp::$_lang['WEB_LOG_SYSTEM_STORAGE_SPACE_LACK'],
    'BD_SYSTEMLOG_DESC_KEY_STORAGE_DISTRIBUTION_IMPORT_DATA' => Xphp::$_lang['WEB_LOG_SYSTEM_STORAGE_DISTRIBUTION_IMPORT_DATA'],
    'BD_SYSTEMLOG_DESC_KEY_STORAGE_DELETE_IMPORT_DATA' => Xphp::$_lang['WEB_LOG_SYSTEM_STORAGE_DELETE_IMPORT_DATA'],
    'BD_SYSTEMLOG_DESC_KEY_STORAGE_NOT_MOUNTED' => Xphp::$_lang['WEB_LOG_SYSTEM_STORAGE_NOT_MOUNTED'],
    'BD_SYSTEMLOG_DESC_KEY_STORAGE_BACK_ONLINE' => Xphp::$_lang['WEB_LOG_SYSTEM_STORAGE_BACK_ONLINE'],
    'BD_SYSTEMLOG_DESC_KEY_ADD_NODE' => xphp::$_lang['WEB_BD_SYSTEMLOG_DESC_KEY_ADD_NODE'], //添加节点
    'BD_SYSTEMLOG_DESC_KEY_MOD_NODE' => xphp::$_lang['WEB_BD_SYSTEMLOG_DESC_KEY_MOD_NODE'], //修改节点
    'BD_SYSTEMLOG_DESC_KEY_DEL_NODE' => xphp::$_lang['WEB_BD_SYSTEMLOG_DESC_KEY_DEL_NODE'], //删除节点
    'BD_SYSTEMLOG_DESC_KEY_IMPORT_BACKUP_TIMEPOINT_SUCCESS' => xphp::$_lang['WEB_BD_SYSTEMLOG_DESC_KEY_IMPORT_BACKUP_TIMEPOINT_SUCCESS'],
    'BD_SYSTEMLOG_DESC_KEY_IMPORT_BACKUP_TIMEPOINT_FAILURE' => xphp::$_lang['WEB_BD_SYSTEMLOG_DESC_KEY_IMPORT_BACKUP_TIMEPOINT_FAILURE'],

    //时间点管理
    'BD_SYSTEMLOG_DESC_KEY_TIMEPOINT_REMARK' => Xphp::$_lang['WEB_LOG_SYSTEM_TIMEPOINT_REMARK'],
    'BD_SYSTEMLOG_DESC_KEY_TIMEPOINT_STAR' => Xphp::$_lang['WEB_LOG_SYSTEM_TIMEPOINT_STAR'],
    'BD_SYSTEMLOG_DESC_KEY_TIMEPOINT_UNSTAR' => Xphp::$_lang['WEB_LOG_SYSTEM_TIMEPOINT_UNSTAR'],
    'BD_SYSTEMLOG_DESC_KEY_TIMEPOINT_DELETE' => Xphp::$_lang['WEB_LOG_SYSTEM_TIMEPOINT_DELETE'],
    'BD_SYSTEMLOG_DESC_KEY_TIMEPOINT_DELETE_BATCH' => Xphp::$_lang['WEB_LOG_SYSTEM_TIMEPOINT_DELETE_BATCH'],

    //授权       别名[IP]
    'BD_SYSTEMLOG_DESC_KEY_LISENCE_HOST' => Xphp::$_lang['WEB_LOG_SYSTEM_LISENCE_HOST'],
    'BD_SYSTEMLOG_DESC_KEY_LISENCE_UNHOST' => Xphp::$_lang['WEB_LOG_SYSTEM_LISENCE_UNHOST'],
    'BD_SYSTEMLOG_DESC_KEY_LISENCE_HOST_BATCH' => Xphp::$_lang['WEB_LOG_SYSTEM_LISENCE_HOST_BATCH'],

    //限速策略
    'BD_SYSTEMLOG_DESC_KEY_ADD_SPEED_LIMIT_STRATEGY' => Xphp::$_lang['WEB_LOG_SYSTEM_ADD_SPEED_LIMIT_STRATEGY'],
    'BD_SYSTEMLOG_DESC_KEY_MOD_SPEED_LIMIT_STRATEGY' => Xphp::$_lang['WEB_LOG_SYSTEM_MOD_SPEED_LIMIT_STRATEGY'],
    'BD_SYSTEMLOG_DESC_KEY_DEL_SPEED_LIMIT_STRATEGY' => Xphp::$_lang['WEB_LOG_SYSTEM_DEL_SPEED_LIMIT_STRATEGY'],

    //***************PT*******************//
    'PT_SYSTEMLOG_DESC_KEY_ADD_LICENSE' => Xphp::$_lang['WEB_LOG_SYSTEM_ADD_LICENSE'],
    'PT_SYSTEMLOG_DESC_KEY_UPDATE_LICENSE' => Xphp::$_lang['WEB_LOG_SYSTEM_UPDATE_LICENSE'],

    //***************VM*******************//
    'VM_SYSTEMLOG_DESC_KEY_ADD_VCENTER_SUCCESS' => Xphp::$_lang['WEB_LOG_SYSTEM_ADD_VCENTER_SUCCESS'],
    'VM_SYSTEMLOG_DESC_KEY_ADD_HOST_SUCCESS' => Xphp::$_lang['WEB_LOG_SYSTEM_ADD_HOST_SUCCESS'],
    'VM_SYSTEMLOG_DESC_KEY_MODIFY_VCENTER_SUCCESS' => Xphp::$_lang['WEB_LOG_SYSTEM_MODIFY_VCENTER_SUCCESS'],
    'VM_SYSTEMLOG_DESC_KEY_DELETE_VCENTER_SUCCESS' => Xphp::$_lang['WEB_LOG_SYSTEM_DELETE_VCENTER_SUCCESS'],

    'VM_SYSTEM_LOG_PLATFORM_BACKUP_DONE' => Xphp::$_lang['WEB_LOG_SYSTEM_PLATFORM_BACKUP_DONE'],
    'VM_SYSTEM_LOG_PLATFORM_BACKUP_FAILED' => Xphp::$_lang['WEB_LOG_SYSTEM_PLATFORM_BACKUP_FAILED'],

    'VM_SYSTEMLOG_DESC_KEY_DEPLOY_VIRTUAL_LAB_SUCCESS' => Xphp::$_lang['WEB_LOG_SYSTEM_VM_DEPLOY_VIRTUAL_LAB_SUCCESS'],
    'VM_SYSTEMLOG_DESC_KEY_DEPLOY_VIRTUAL_LAB_ERROR' => Xphp::$_lang['WEB_LOG_SYSTEM_VM_DEPLOY_VIRTUAL_LAB_ERROR'],

    'VM_SYSTEMLOG_DESC_KEY_DELETE_VIRTUAL_LAB_SUCCESS' => Xphp::$_lang['WEB_LOG_SYSTEM_VM_DELETE_VIRTUAL_LAB_SUCCESS'],
    'VM_SYSTEMLOG_DESC_KEY_DELETE_VIRTUAL_LAB_ERROR' => Xphp::$_lang['WEB_LOG_SYSTEM_VM_DELETE_VIRTUAL_LAB_ERROR'],

    'VM_SYSTEMLOG_DESC_KEY_MODIFY_VIRTUAL_LAB_SUCCESS' => Xphp::$_lang['WEB_LOG_SYSTEM_VM_MODIFY_VIRTUAL_LAB_SUCCESS'],
    'VM_SYSTEMLOG_DESC_KEY_MODIFY_VIRTUAL_LAB_ERROR' => Xphp::$_lang['WEB_LOG_SYSTEM_VM_MODIFY_VIRTUAL_LAB_ERROR'],

    'VM_SYSTEMLOG_DESC_KEY_REFRESH_VIRTUAL_LAB_SUCCESS' => Xphp::$_lang['WEB_LOG_SYSTEM_VM_REFRESH_VIRTUAL_LAB_SUCCESS'],
    'VM_SYSTEMLOG_DESC_KEY_REFRESH_VIRTUAL_LAB_ERROR' => Xphp::$_lang['WEB_LOG_SYSTEM_VM_REFRESH_VIRTUAL_LAB_ERROR'],

    //***************副本*******************//
    'BD_SYSTEMLOG_DESC_KEY_REMOTE_STORAGE_ADD' => Xphp::$_lang['WEB_LOG_SYSTEM_REMOTE_STORAGE_ADD'],
    "BACKUP_COPY_DESC_KEY_DO_RETENTION" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_BACKUP_COPY_DO_RETENTION'],
    "BACKUP_COPY_DESC_KEY_MERGE_TIMEPOINT" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_BACKUP_COPY_MERGE_TIMEPOINT'],
    "BACKUP_COPY_DESC_KEY_MERGE_TIMEPOINT_ERROR" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_BACKUP_COPY_MERGE_TIMEPOINT_ERROR'],
    "BACKUP_COPY_DESC_KEY_TIMEPOINT_IS_MERGING" => Xphp::$_lang['WEB_LOG_TASK_DESC_KEY_BACKUP_COPY_TIMEPOINT_IS_MERGING'],

    "SYSTEMLOG_BACKUP_COPY_DESC_KEY_DO_RETENTION" => Xphp::$_lang['WEB_LOG_SYSTEM_DESC_KEY_BACKUP_COPY_DO_RETENTION'],
    "SYSTEMLOG_BACKUP_COPY_DESC_KEY_MERGE_TIMEPOINT" => Xphp::$_lang['WEB_LOG_SYSTEM_DESC_KEY_BACKUP_COPY_MERGE_TIMEPOINT'],
    "SYSTEMLOG_BACKUP_COPY_DESC_KEY_MERGE_TIMEPOINT_ERROR" => Xphp::$_lang['WEB_LOG_SYSTEM_DESC_KEY_BACKUP_COPY_MERGE_TIMEPOINT_ERROR'],
    "SYSTEMLOG_BACKUP_COPY_DESC_KEY_TIMEPOINT_IS_MERGING" => Xphp::$_lang['WEB_LOG_SYSTEM_DESC_KEY_BACKUP_COPY_TIMEPOINT_IS_MERGING'],

    //***************CDP****没有开放到海外之前都使用中文,不用翻译***************//

    "SYSTEM_LOG_CDP_ADD_HOST" => Xphp::$_lang['WEB_VOL_CDP_LOG_DESC_KEY_SYSTEM_LOG_CDP_ADD_HOST'],
    "SYSTEM_LOG_CDP_EDIT_HOST" => Xphp::$_lang['WEB_VOL_CDP_LOG_DESC_KEY_SYSTEM_LOG_CDP_EDIT_HOST'],
    "SYSTEM_LOG_CDP_DELETE_HOST" => Xphp::$_lang['WEB_VOL_CDP_LOG_DESC_KEY_SYSTEM_LOG_CDP_DELETE_HOST'],

    //多租户 (租户|用户组|角色|资源组|AD域)
    'SYSTEM_TENANT_ADD_SUCCESS' => Xphp::$_lang['WEB_LOG_SYSTEM_TENANT_ADD_SUCCESS'],
    'SYSTEM_TENANT_DELETE_SUCCESS' => Xphp::$_lang['WEB_LOG_SYSTEM_TENANT_DELETE_SUCCESS'],
    'SYSTEM_TENANT_UNLOCK_SUCCESS' => Xphp::$_lang['WEB_LOG_SYSTEM_TENANT_UNLOCK_SUCCESS'],
    'SYSTEM_TENANT_LOCK_SUCCESS' => Xphp::$_lang['WEB_LOG_SYSTEM_TENANT_LOCK_SUCCESS'],
    'SYSTEM_USER_GROUP_ADD_SUCCESS' => Xphp::$_lang['WEB_LOG_SYSTEM_USER_GROUP_ADD_SUCCESS'],
    'SYSTEM_USER_GROUP_DELETE_SUCCESS' => Xphp::$_lang['WEB_LOG_SYSTEM_USER_GROUP_DELETE_SUCCESS'],
    'SYSTEM_ROLE_ADD_SUCCESS' => Xphp::$_lang['WEB_LOG_SYSTEM_ROLE_ADD_SUCCESS'],
    'SYSTEM_ROLE_DELETE_SUCCESS' => Xphp::$_lang['WEB_LOG_SYSTEM_ROLE_DELETE_SUCCESS'],
    'SYSTEM_RESOURCE_GROUP_ADD_SUCCESS' => Xphp::$_lang['WEB_LOG_SYSTEM_RESOURCE_GROUP_ADD_SUCCESS'],
    'SYSTEM_RESOURCE_GROUP_DELETE_SUCCESS' => Xphp::$_lang['WEB_LOG_SYSTEM_RESOURCE_GROUP_DELETE_SUCCESS'],
    'SYSTEM_DOMAIN_ADD_SUCCESS' => Xphp::$_lang['WEB_LOG_SYSTEM_DOMAIN_ADD_SUCCESS'],
    'SYSTEM_DOMAIN_DELETE_SUCCESS' => Xphp::$_lang['WEB_LOG_SYSTEM_DOMAIN_DELETE_SUCCESS'],

    //系统备份恢复
    'SYSTEM_LOG_SYSBAKREC_AUTO_BACKUP_SYSTEM_SUCCESS' => Xphp::$_lang['WEB_LOG_SYSTEM_SYSBAKREC_AUTO_BACKUP_SYSTEM_SUCCESS'],
    'SYSTEM_LOG_SYSBAKREC_AUTO_BACKUP_SYSTEM_FAILURE1' => Xphp::$_lang['WEB_LOG_SYSTEM_SYSBAKREC_AUTO_BACKUP_SYSTEM_FAILURE1'],
    'SYSTEM_LOG_SYSBAKREC_AUTO_BACKUP_SYSTEM_FAILURE2' => Xphp::$_lang['WEB_LOG_SYSTEM_SYSBAKREC_AUTO_BACKUP_SYSTEM_FAILURE2'],
    'SYSTEM_LOG_SYSBAKREC_AUTO_BACKUP_SYSTEM_FAILURE3' => Xphp::$_lang['WEB_LOG_SYSTEM_SYSBAKREC_AUTO_BACKUP_SYSTEM_FAILURE3'],
    'SYSTEM_LOG_SYSBAKREC_AUTO_BACKUP_SYSTEM_FAILURE4' => Xphp::$_lang['WEB_LOG_SYSTEM_SYSBAKREC_AUTO_BACKUP_SYSTEM_FAILURE4'],
    'SYSTEM_LOG_SYSBAKREC_AUTO_BACKUP_SYSTEM_FAILURE5' => Xphp::$_lang['WEB_LOG_SYSTEM_SYSBAKREC_AUTO_BACKUP_SYSTEM_FAILURE5'],
    'SYSTEM_LOG_SYSBAKREC_USER_BACKUP_SYSTEM' => Xphp::$_lang['WEB_LOG_SYSTEM_SYSBAKREC_USER_BACKUP_SYSTEM'],
    'SYSTEM_LOG_SYSBAKREC_RECOVERY_SYSTEM' => Xphp::$_lang['WEB_LOG_SYSTEM_SYSBAKREC_RECOVERY_SYSTEM'],
    'SYSTEM_LOG_SYSBAKREC_SETTINGS' => Xphp::$_lang['WEB_LOG_SYSTEM_SYSBAKREC_SETTINGS'],
    'SYSTEM_LOG_SYSBAKREC_DELETE_TIMEPOINT' => Xphp::$_lang['WEB_LOG_SYSTEM_SYSBAKREC_DELETE_TIMEPOINT'],

    //系统配置-安全配置
    'SYSTEM_LOG_SETTINGS_ACCOUNT_SAFE' => Xphp::$_lang['WEB_LOG_SYSTEM_SETTINGS_ACCOUNT_SAFE'],
    'SYSTEM_LOG_SETTINGS_STORAGE_SAFE_ON' => Xphp::$_lang['WEB_LOG_SYSTEM_SETTINGS_STORAGE_SAFE_ON'],
    'SYSTEM_LOG_SETTINGS_STORAGE_SAFE_OFF' => Xphp::$_lang['WEB_LOG_SYSTEM_SETTINGS_STORAGE_SAFE_OFF'],
    'SYSTEM_LOG_SETTINGS_OS_SAFE' => Xphp::$_lang['WEB_LOG_SYSTEM_SETTINGS_OS_SAFE'],
    //系统配置-网络配置
    'SYSTEM_LOG_SETTINGS_DNS' => Xphp::$_lang['WEB_LOG_SYSTEM_SETTINGS_DNS'],
    'SYSTEM_LOG_SETTINGS_NIC' => Xphp::$_lang['WEB_LOG_SYSTEM_SETTINGS_NIC'],
    //GFS
    'VM_SYSTEMLOG_DESC_KEY_SET_TIMEPOINT_GFS_FLAG' => Xphp::$_lang['WEB_SYSTEMLOG_DESC_KEY_SET_TIMEPOINT_GFS_FLAG'],
    'VM_SYSTEMLOG_DESC_KEY_UNSET_TIMEPOINT_GFS_FLAG' => Xphp::$_lang['WEB_SYSTEMLOG_DESC_KEY_UNSET_TIMEPOINT_GFS_FLAG'],
    'BD_SYSTEMLOG_DESC_KEY_SET_TIMEPOINT_GFS_FLAG' => Xphp::$_lang['WEB_SYSTEMLOG_DESC_KEY_SET_TIMEPOINT_GFS_FLAG'],
    'BD_SYSTEMLOG_DESC_KEY_UNSET_TIMEPOINT_GFS_FLAG' => Xphp::$_lang['WEB_SYSTEMLOG_DESC_KEY_UNSET_TIMEPOINT_GFS_FLAG'],
    'BD_SYSTEMLOG_DESC_KEY_SET_TIMEPOINT_IMPORTANCE_FLAG' => Xphp::$_lang['WEB_SYSTEMLOG_DESC_KEY_SET_TIMEPOINT_IMPORTANCE_FLAG'],

    //升级检测
    'SYSTEM_ALARM_UPDATE_ONLINE_SUCCESS' => Xphp::$_lang['WEB_TIPS_SYSTEM_UPDATE_PACKAGE_TIP'],
    'BD_SYSTEMLOG_DESC_KEY_EXEC_UPDATE_SCRIPT_FAILED' => Xphp::$_lang['WEB_SYSTEMLOG_DESC_KEY_EXEC_UPDATE_SCRIPT_FAILED'],
    'BD_SYSTEMLOG_DESC_KEY_LOAD_COMMON_CONF_INFO' => Xphp::$_lang['WEB_SYSTEMLOG_DESC_KEY_LOAD_COMMON_CONF_INFO'],
    'BD_SYSTEMLOG_DESC_KEY_UPDATING_CONFIG_FILE' => Xphp::$_lang['WEB_SYSTEMLOG_DESC_KEY_UPDATING_CONFIG_FILE'],
    'BD_SYSTEMLOG_DESC_KEY_UPDATE_CONFIG_FILE_COMPLETED' => Xphp::$_lang['WEB_SYSTEMLOG_DESC_KEY_UPDATE_CONFIG_FILE_COMPLETED'],
    'BD_SYSTEMLOG_DESC_KEY_UPDATING_DATABASE_COLUMN' => Xphp::$_lang['WEB_SYSTEMLOG_DESC_KEY_UPDATING_DATABASE_COLUMN'],
    'BD_SYSTEMLOG_DESC_KEY_UPDATE_DATABASE_COLUMN_COMPLETED' => Xphp::$_lang['WEB_SYSTEMLOG_DESC_KEY_UPDATE_DATABASE_COLUMN_COMPLETED'],
    'BD_SYSTEMLOG_DESC_KEY_UPDATING_LIBRARY_FILE' => Xphp::$_lang['WEB_SYSTEMLOG_DESC_KEY_UPDATING_LIBRARY_FILE'],
    'BD_SYSTEMLOG_DESC_KEY_UPDATE_LIBRARY_FILE_COMPLETED' => Xphp::$_lang['WEB_SYSTEMLOG_DESC_KEY_UPDATE_LIBRARY_FILE_COMPLETED'],
    'BD_SYSTEMLOG_DESC_KEY_UPDATING_BIN_FILE' => Xphp::$_lang['WEB_SYSTEMLOG_DESC_KEY_UPDATING_BIN_FILE'],
    'BD_SYSTEMLOG_DESC_KEY_UPDATE_BIN_FILE_COMPLETED' => Xphp::$_lang['WEB_SYSTEMLOG_DESC_KEY_UPDATE_BIN_FILE_COMPLETED'],
    'BD_SYSTEMLOG_DESC_KEY_UPDATING_WEB_UI_FILE' => Xphp::$_lang['WEB_SYSTEMLOG_DESC_KEY_UPDATING_WEB_UI_FILE'],
    'BD_SYSTEMLOG_DESC_KEY_UPDATE_WEB_UI_FILE_COMPLETED' => Xphp::$_lang['WEB_SYSTEMLOG_DESC_KEY_UPDATE_WEB_UI_FILE_COMPLETED'],
    'BD_SYSTEMLOG_DESC_KEY_UPDATING_EXTRA_FILE' => Xphp::$_lang['WEB_SYSTEMLOG_DESC_KEY_UPDATING_EXTRA_FILE'],
    'BD_SYSTEMLOG_DESC_KEY_UPDATE_COMPLETED' => Xphp::$_lang['WEB_SYSTEMLOG_DESC_KEY_UPDATE_COMPLETED'],
    'BD_SYSTEMLOG_DESC_KEY_PATCH_PACKAGE_VERIFICATION_FAILED' => Xphp::$_lang['WEB_SYSTEMLOG_DESC_KEY_PATCH_PACKAGE_VERIFICATION_FAILED'],
    'BD_SYSTEMLOG_DESC_KEY_PERFORM_PRE_UPDATE_DETECTION' => Xphp::$_lang['WEB_SYSTEMLOG_DESC_KEY_PERFORM_PRE_UPDATE_DETECTION'],
    'BD_SYSTEMLOG_DESC_KEY_CAN_NOT_TO_UPDATE' => Xphp::$_lang['WEB_SYSTEMLOG_DESC_KEY_CAN_NOT_TO_UPDATE'],
    'BD_SYSTEMLOG_DESC_KEY_PATCH_ALREADY_INSTALLED' => Xphp::$_lang['WEB_SYSTEMLOG_DESC_KEY_PATCH_ALREADY_INSTALLED'],

    //卷cdp模块相关系统日志
    'VOL_CDP_LOG_DESC_KEY_SYSTEM_OP_DELETE_CONSISITENCY_LABEL' => Xphp::$_lang['WEB_VOL_CDP_LOG_DESC_KEY_SYSTEM_OP_DELETE_CONSISITENCY_LABEL'],
    'VOL_CDP_LOG_DESC_KEY_SYSTEM_OP_DELETE_ONE_BACKUPSET' => Xphp::$_lang['WEB_VOL_CDP_LOG_DESC_KEY_SYSTEM_OP_DELETE_ONE_BACKUPSET'],
    'VOL_CDP_LOG_DESC_KEY_SYSTEM_OP_DELETE_ONE_VOL_ALL_BACKUPSET' => Xphp::$_lang['WEB_VOL_CDP_LOG_DESC_KEY_SYSTEM_OP_DELETE_ONE_VOL_ALL_BACKUPSET'],
    'VOL_CDP_LOG_DESC_KEY_SYSTEM_OP_DELETE_ONE_AGENT_ALL_BACKUPSET' => Xphp::$_lang['WEB_VOL_CDP_LOG_DESC_KEY_SYSTEM_OP_DELETE_ONE_AGENT_ALL_BACKUPSET'],

    // 容灾演练平台
    'SYSTEM_LOG_EXERCISE_PLATFORM' => Xphp::$_lang['UI_EXERCISE_PLATFORM_MSG'],

    // template: 为NAS设备'%s'添加备份授权
    "PT_SYSTEMLOG_DESC_KEY_ADD_AUTH_TO_NAS_DEV" => Xphp::$_lang['WEB_LOG_SYSTEM_DESC_KEY_PT_ADD_AUTH_TO_NAS_DEV'],
    // template: 删除NAS设备'%s'备份授权
    "PT_SYSTEMLOG_DESC_KEY_DEL_AUTH_FROM_NAS_DEV" => Xphp::$_lang['WEB_LOG_SYSTEM_DESC_KEY_PT_DEL_AUTH_FROM_NAS_DEV'],

    // template: 系统授权将于'%s'过期
    "PT_SYSTEMLOG_DESC_KEY_AUTH_WILL_EXPIRE" => Xphp::$_lang['WEB_LOG_SYSTEM_DESC_KEY_PT_AUTH_WILL_EXPIRE'],

    //template: add agent, ip:'%s'(server-to-client)
    "BD_SYSTEMLOG_DESC_KEY_AGENT_ADD_NET_MODEL1" => Xphp::$_lang['WEB_LOG_SYSTEM_DESC_KEY_AGENT_ADD_NET_MODEL1'],

    //template: add agent, ip:'%s'(client-to-server)
    "BD_SYSTEMLOG_DESC_KEY_AGENT_ADD_NET_MODEL2" => Xphp::$_lang['WEB_LOG_SYSTEM_DESC_KEY_AGENT_ADD_NET_MODEL2'],

    //template: backup node '%s[%s]' storage available space is less than '%s'G
    "BD_SYSTEMLOG_DESC_KEY_SYSTEM_STORAGE_NOT_ENOUGH" => Xphp::$_lang['WEB_LOG_SYSTEM_DESC_KEY_STORAGE_NOT_ENOUGH'],

    //退出登录日志
    'SYSTEM_USER_LOGINOUT_SUCCESS' => Xphp::$_lang['WEB_LOG_SYSTEM_LOGINOUT_SUCCESS'],

    //M365
    'M365_ORG_DESC_KEY_ADD_ORGANIZATION_ERROR' => Xphp::$_lang['WEB_LOG_TASK_M365_ORG_DESC_KEY_ADD_ORGANIZATION_ERROR'],
    'M365_ORG_DESC_KEY_LOGIN_AZURE_AD_ERROR' => Xphp::$_lang['WEB_LOG_TASK_M365_ORG_DESC_KEY_LOGIN_AZURE_AD_ERROR'],
    'M365_ORG_DESC_KEY_ADD_ORGANIZATION_SUCCESS' => Xphp::$_lang['WEB_M365_ORG_DESC_KEY_ADD_ORGANIZATION_SUCCESS'],
    'M365_ORG_DESC_KEY_EDIT_ORGANIZATION_ERROR' => Xphp::$_lang['WEB_M365_ORG_DESC_KEY_EDIT_ORGANIZATION_ERROR'],
    'M365_ORG_DESC_KEY_LOGIN_AZURE_AD_SUCCESS' => Xphp::$_lang['WEB_M365_ORG_DESC_KEY_LOGIN_AZURE_AD_SUCCESS'],
    'M365_ORG_DESC_KEY_EDIT_ORGANIZATION_SUCCESS' => Xphp::$_lang['WEB_M365_ORG_DESC_KEY_EDIT_ORGANIZATION_SUCCESS'],
    'M365_ORG_DESC_KEY_REFRESH_ORGANIZATION_SUCCESS' => Xphp::$_lang['WEB_M365_ORG_DESC_KEY_REFRESH_ORGANIZATION_SUCCESS'],
    'M365_ORG_DESC_KEY_REFRESH_ORGANIZATION_ERROR' => Xphp::$_lang['WEB_M365_ORG_DESC_KEY_REFRESH_ORGANIZATION_ERROR'],
    'M365_ORG_DESC_KEY_DELETE_ORGANIZATION_SUCCESS' => Xphp::$_lang['WEB_M365_ORG_DESC_KEY_DELETE_ORGANIZATION_SUCCESS'],
    'M365_ORG_DESC_KEY_DELETE_ORGANIZATION_ERROR' => Xphp::$_lang['WEB_M365_ORG_DESC_KEY_DELETE_ORGANIZATION_ERROR'],
    'M365_ORG_DESC_KEY_ADD_ORGANIZATION_ABNORMAL' => Xphp::$_lang['WEB_M365_ORG_DESC_KEY_ADD_ORGANIZATION_ABNORMAL'],
    'M365_ORG_DESC_KEY_EDIT_ORGANIZATION_ABNORMAL' => Xphp::$_lang['WEB_M365_ORG_DESC_KEY_EDIT_ORGANIZATION_ABNORMAL'],
    'M365_SYSTEMLOG_DESC_KEY_DELETE_FULL_TIMEPOINT_SUCCESS' => Xphp::$_lang['WEB_M365_SYSTEMLOG_DESC_KEY_DELETE_FULL_TIMEPOINT_SUCCESS'],
    'M365_SYSTEMLOG_DESC_KEY_DELETE_FULL_TIMEPOINT_ERROR' => Xphp::$_lang['WEB_M365_SYSTEMLOG_DESC_KEY_DELETE_FULL_TIMEPOINT_ERROR'],
    'M365_SYSTEMLOG_DESC_KEY_SYNC_META_FILE_FROM_OSS_SUCCESS' => Xphp::$_lang['WEB_M365_SYSTEMLOG_DESC_KEY_SYNC_META_FILE_FROM_OSS_SUCCESS'],
    'M365_SYSTEMLOG_DESC_KEY_SYNC_META_FILE_FROM_OSS_ERROR' => Xphp::$_lang['WEB_M365_SYSTEMLOG_DESC_KEY_SYNC_META_FILE_FROM_OSS_ERROR'],

    // OBS
    'FS_SYSTEMLOG_DESC_KEY_OBS_OP' => Xphp::$_lang['WEB_FS_SYSTEMLOG_DESC_KEY_OBS_OP'],
    'FS_SYSTEMLOG_DESC_KEY_OBS_ADD' => Xphp::$_lang['WEB_FS_SYSTEMLOG_DESC_KEY_OBS_ADD'],
    'FS_SYSTEMLOG_DESC_KEY_OBS_MODIFY' => Xphp::$_lang['WEB_FS_SYSTEMLOG_DESC_KEY_OBS_MODIFY'],
    'FS_SYSTEMLOG_DESC_KEY_OBS_DELETE' => Xphp::$_lang['WEB_FS_SYSTEMLOG_DESC_KEY_OBS_DELETE'],
    'FS_SYSTEMLOG_DESC_KEY_OBS_REFRESH' => Xphp::$_lang['WEB_FS_SYSTEMLOG_DESC_KEY_OBS_REFRESH'],
    'PT_SYSTEMLOG_DESC_KEY_ADD_AUTH_TO_OBS' => Xphp::$_lang['WEB_PT_SYSTEMLOG_DESC_KEY_ADD_AUTH_TO_OBS'],
    'PT_SYSTEMLOG_DESC_KEY_DEL_AUTH_FROM_OBS' => Xphp::$_lang['WEB_PT_SYSTEMLOG_DESC_KEY_DEL_AUTH_FROM_OBS'],

    // 任务编排计划
    'BD_SYSTEMLOG_DESC_KEY_ADD_TASK_ORCHESTRATION_PLAN' => Xphp::$_lang['WEB_BD_SYSTEMLOG_DESC_KEY_ADD_TASK_ORCHESTRATION_PLAN'],
    'BD_SYSTEMLOG_DESC_KEY_MOD_TASK_ORCHESTRATION_PLAN' => Xphp::$_lang['WEB_BD_SYSTEMLOG_DESC_KEY_MOD_TASK_ORCHESTRATION_PLAN'],
    'BD_SYSTEMLOG_DESC_KEY_DEL_TASK_ORCHESTRATION_PLAN' => Xphp::$_lang['WEB_BD_SYSTEMLOG_DESC_KEY_DEL_TASK_ORCHESTRATION_PLAN'],
    'BD_SYSTEMLOG_DESC_KEY_START_TASK_ORCHESTRATION_PLAN' => Xphp::$_lang['WEB_BD_SYSTEMLOG_DESC_KEY_START_TASK_ORCHESTRATION_PLAN'],
    'BD_SYSTEMLOG_DESC_KEY_STOP_TASK_ORCHESTRATION_PLAN' => Xphp::$_lang['WEB_BD_SYSTEMLOG_DESC_KEY_STOP_TASK_ORCHESTRATION_PLAN'],
    'BD_SYSTEMLOG_DESC_KEY_ENABLE_TASK_ORCHESTRATION_PLAN' => Xphp::$_lang['WEB_BD_SYSTEMLOG_DESC_KEY_ENABLE_TASK_ORCHESTRATION_PLAN'],

    //hadoop
    'FS_SYSTEMLOG_DESC_KEY_HADOOP_ADD_SUCCESS' => Xphp::$_lang['WEB_LOG_HADOOP_FS_SYSTEMLOG_DESC_KEY_HADOOP_ADD_SUCCESS'],
    'FS_SYSTEMLOG_DESC_KEY_HADOOP_ADD_FAILED' => Xphp::$_lang['WEB_LOG_HADOOP_FS_SYSTEMLOG_DESC_KEY_HADOOP_ADD_FAILED'],
    'FS_SYSTEMLOG_DESC_KEY_HADOOP_MODIFY_SUCCESS' => Xphp::$_lang['WEB_LOG_HADOOP_FS_SYSTEMLOG_DESC_KEY_HADOOP_MODIFY_SUCCESS'],
    'FS_SYSTEMLOG_DESC_KEY_HADOOP_MODIFY_FAILED' => Xphp::$_lang['WEB_LOG_HADOOP_FS_SYSTEMLOG_DESC_KEY_HADOOP_MODIFY_FAILED'],
    'FS_SYSTEMLOG_DESC_KEY_HADOOP_DELETE_SUCCESS' => Xphp::$_lang['WEB_LOG_HADOOP_FS_SYSTEMLOG_DESC_KEY_HADOOP_DELETE_SUCCESS'],
    'FS_SYSTEMLOG_DESC_KEY_HADOOP_DELETE_FAILED' => Xphp::$_lang['WEB_LOG_HADOOP_FS_SYSTEMLOG_DESC_KEY_HADOOP_DELETE_FAILED'],
    'FS_SYSTEMLOG_DESC_KEY_HADOOP_REFRESH_SUCCESS' => Xphp::$_lang['WEB_LOG_HADOOP_FS_SYSTEMLOG_DESC_KEY_HADOOP_REFRESH_SUCCESS'],
    'FS_SYSTEMLOG_DESC_KEY_HADOOP_REFRESH_FAILED' => Xphp::$_lang['WEB_LOG_HADOOP_FS_SYSTEMLOG_DESC_KEY_HADOOP_REFRESH_FAILED'],
    'PT_SYSTEMLOG_DESC_KEY_ADD_AUTH_TO_HADOOP_CLUSTER' => Xphp::$_lang['WEB_PT_SYSTEMLOG_DESC_KEY_ADD_AUTH_TO_HADOOP_CLUSTER'],
    'PT_SYSTEMLOG_DESC_KEY_DEL_AUTH_FROM_HADOOP_CLUSTER' => Xphp::$_lang['WEB_PT_SYSTEMLOG_DESC_KEY_DEL_AUTH_FROM_HADOOP_CLUSTER'],
    // 公有云
    'PUBLIC_CLOUD_SYSTEMLOG_DESC_KEY_ADD_VCENTER_SUCCESS' => Xphp::$_lang['WEB_LOG_SYSTEM_ADD_PUBLIC_CLOUD_PLATFORM_SUCCESS'],
    'PUBLIC_CLOUD_SYSTEMLOG_DESC_KEY_MODIFY_VCENTER_SUCCESS' => Xphp::$_lang['WEB_LOG_SYSTEM_MODIFY_PUBLIC_CLOUD_PLATFORM_SUCCESS'],
    'PUBLIC_CLOUD_SYSTEMLOG_DESC_KEY_DELETE_VCENTER_SUCCESS' => Xphp::$_lang['WEB_LOG_SYSTEM_DELETE_PUBLIC_CLOUD_PLATFORM_SUCCESS'],

    // 病毒库
    'VIRUS_SYSTEMLOG_DESC_KEY_REFRESH_VIRUS' => Xphp::$_lang['WEB_LOG_SYSTEM_REFRESH_VIRUS'],  // 刷新病毒库
    'VIRUS_SYSTEMLOG_DESC_KEY_SET_DEFAULT_VIRUS' => Xphp::$_lang['WEB_LOG_SYSTEM_SET_DEFAULT_VIRUS'],  // 设置默认病毒库
    'VIRUS_SYSTEMLOG_DESC_KEY_UPLOAD_VIRUS' => Xphp::$_lang['WEB_LOG_SYSTEM_UPLOAD_VIRUS'],  // 上传病毒库
    'VIRUS_SYSTEMLOG_DESC_KEY_UPGRADE_VIRUS' => Xphp::$_lang['WEB_LOG_SYSTEM_UPGRADE_VIRUS'],  // 更新病毒库

    // 第三方推送
    'BD_SYSTEMLOG_DESC_KEY_ADD_THIRD_MONITOR_PLATFORM' => Xphp::$_lang['WEB_BD_SYSTEMLOG_DESC_KEY_ADD_THIRD_MONITOR_PLATFORM'],
    'BD_SYSTEMLOG_DESC_KEY_MOD_THIRD_MONITOR_PLATFORM' => Xphp::$_lang['WEB_BD_SYSTEMLOG_DESC_KEY_MOD_THIRD_MONITOR_PLATFORM'],
    'BD_SYSTEMLOG_DESC_KEY_DEL_THIRD_MONITOR_PLATFORM' => Xphp::$_lang['WEB_BD_SYSTEMLOG_DESC_KEY_DEL_THIRD_MONITOR_PLATFORM'],
    'BD_SYSTEMLOG_DESC_KEY_ADD_ALARM_PUSH_STRATEGY' => Xphp::$_lang['WEB_BD_SYSTEMLOG_DESC_KEY_ADD_ALARM_PUSH_STRATEGY'],
    'BD_SYSTEMLOG_DESC_KEY_MOD_ALARM_PUSH_STRATEGY' => Xphp::$_lang['WEB_BD_SYSTEMLOG_DESC_KEY_MOD_ALARM_PUSH_STRATEGY'],
    'BD_SYSTEMLOG_DESC_KEY_DEL_ALARM_PUSH_STRATEGY' => Xphp::$_lang['WEB_BD_SYSTEMLOG_DESC_KEY_DEL_ALARM_PUSH_STRATEGY'],

    //磁带
    'BD_SYSTEMLOG_DESC_KEY_TAPE_STORAGE_CARRIAGE_EXPIRED' => Xphp::$_lang['WEB_LOG_SYSTEM_TAPE_STORAGE_CARRIAGE_EXPIRED'],
    'BD_SYSTEMLOG_DESC_KEY_TAPE_STORAGE_BACKUPSET_EXPIRED' => Xphp::$_lang['WEB_LOG_SYSTEM_TAPE_STORAGE_BACKUPSET_EXPIRED'],

    //生产存储
    'BD_SYSTEMLOG_DESC_KEY_PRODUCTION_STORAGE_ADD' => Xphp::$_lang['WEB_LOG_SYSTEM_PRODUCTION_STORAGE_ADD'],
    'BD_SYSTEMLOG_DESC_KEY_PRODUCTION_STORAGE_MODIFY' => Xphp::$_lang['WEB_LOG_SYSTEM_PRODUCTION_STORAGE_MODIFY'],
    'BD_SYSTEMLOG_DESC_KEY_PRODUCTION_STORAGE_DELETE' => Xphp::$_lang['WEB_LOG_SYSTEM_PRODUCTION_STORAGE_DELETE'],

    // 资源池
    'BD_SYSTEMLOG_DESC_KEY_ADD_NODE_POOL' => Xphp::$_lang['WEB_LOG_SYSTEM_ADD_NODE_POOL'],
    'BD_SYSTEMLOG_DESC_KEY_MOD_NODE_POOL' => Xphp::$_lang['WEB_LOG_SYSTEM_MOD_NODE_POOL'],
    'BD_SYSTEMLOG_DESC_KEY_DEL_NODE_POOL' => Xphp::$_lang['WEB_LOG_SYSTEM_DEL_NODE_POOL'],
    'BD_SYSTEMLOG_DESC_KEY_ADD_STORAGE_RESOURCE_POOL' => Xphp::$_lang['WEB_LOG_SYSTEM_ADD_STORAGE_RESOURCE_POOL'],
    'BD_SYSTEMLOG_DESC_KEY_MOD_STORAGE_RESOURCE_POOL' => Xphp::$_lang['WEB_LOG_SYSTEM_MOD_STORAGE_RESOURCE_POOL'],
    'BD_SYSTEMLOG_DESC_KEY_DEL_STORAGE_RESOURCE_POOL' => Xphp::$_lang['WEB_LOG_SYSTEM_DEL_STORAGE_RESOURCE_POOL'],
    'BD_SYSTEMLOG_DESC_KEY_ADD_NETWORK_POOL' => Xphp::$_lang['WEB_LOG_SYSTEM_ADD_NETWORK_POOL'],
    'BD_SYSTEMLOG_DESC_KEY_MOD_NETWORK_POOL' => Xphp::$_lang['WEB_LOG_SYSTEM_MOD_NETWORK_POOL'],
    'BD_SYSTEMLOG_DESC_KEY_DEL_NETWORK_POOL' => Xphp::$_lang['WEB_LOG_SYSTEM_DEL_NETWORK_POOL'],
    'BD_SYSTEMLOG_DESC_KEY_ADD_AGENT_POOL' => Xphp::$_lang['WEB_LOG_SYSTEM_ADD_AGENT_POOL'],
    'BD_SYSTEMLOG_DESC_KEY_MOD_AGENT_POOL' => Xphp::$_lang['WEB_LOG_SYSTEM_MOD_AGENT_POOL'],
    'BD_SYSTEMLOG_DESC_KEY_DEL_AGENT_POOL' => Xphp::$_lang['WEB_LOG_SYSTEM_DEL_AGENT_POOL'],

    // 能耗监控平台
    'SYSTEM_LOG_CARBON_MONITOR_PLATFORM' => Xphp::$_lang['UI_SETTINGS_CARBON_MONITOR_PLATFORM_MSG'],

    // 行业合规
    'PT_INDUSTRY_REPORT_APPROVAL' => Xphp::$_lang['UI_INDUSTRY_REPORT_APPROVAL'],
    'PT_INDUSTRY_PLAN_APPROVAL' => Xphp::$_lang['UI_INDUSTRY_PLAN_APPROVAL'],
    'PT_INDUSTRY_REPORT_OPERATE' => Xphp::$_lang['UI_INDUSTRY_REPORT_OPERATE'],
    'PT_INDUSTRY_PLAN_OPERATE' => Xphp::$_lang['UI_INDUSTRY_PLAN_OPERATE'],
    'PT_INDUSTRY_REPORT_SHARE' => Xphp::$_lang['WEB_PLATFORM_INDUSTRY_REPORT_SHARE'],
    'PT_INDUSTRY_PLAN_SHARE' => Xphp::$_lang['WEB_PLATFORM_INDUSTRY_PLAN_SHARE'],
    'PT_INDUSTRY_TEMPLATE_OPERATE' => Xphp::$_lang['UI_INDUSTRY_TEMPLATE_OPERATE'],
    'PT_INDUSTRY_REPORT_CHANGE_APPROVAL' => Xphp::$_lang['UI_INDUSTRY_REPORT_CHANGE_APPROVAL'],
    'PT_INDUSTRY_PLAN_CHANGE_APPROVAL' => Xphp::$_lang['UI_INDUSTRY_PLAN_CHANGE_APPROVAL'],
    'PT_INDUSTRY_APPROVAL_ADD' => Xphp::$_lang['UI_INDUSTRY_APPROVAL_ADD'],
    'PT_INDUSTRY_APPROVAL_LOOK' => Xphp::$_lang['UI_INDUSTRY_APPROVAL_LOOK'],
    'PT_INDUSTRY_APPROVAL_EDIT' => Xphp::$_lang['UI_INDUSTRY_APPROVAL_EDIT'],
    'PT_INDUSTRY_APPROVAL_DELETE' => Xphp::$_lang['UI_INDUSTRY_APPROVAL_DELETE'],
    'PT_INDUSTRY_APPROVAL_ENABLE' => Xphp::$_lang['UI_INDUSTRY_APPROVAL_ENABLE'],
    'PT_INDUSTRY_APPROVAL_DISABLE' => Xphp::$_lang['UI_INDUSTRY_APPROVAL_DISABLE'],
    'PT_INDUSTRY_APPROVAL_GROUP_ADD' => Xphp::$_lang['UI_INDUSTRY_APPROVAL_GROUP_ADD'],
    'PT_INDUSTRY_APPROVAL_GROUP_LOOK' => Xphp::$_lang['UI_INDUSTRY_APPROVAL_GROUP_LOOK'],
    'PT_INDUSTRY_APPROVAL_GROUP_EDIT' => Xphp::$_lang['UI_INDUSTRY_APPROVAL_GROUP_EDIT'],
    'PT_INDUSTRY_APPROVAL_GROUP_DELETE' => Xphp::$_lang['UI_INDUSTRY_APPROVAL_GROUP_DELETE'],
    'PT_INDUSTRY_APPROVAL_GROUP_ENABLE' => Xphp::$_lang['UI_INDUSTRY_APPROVAL_GROUP_ENABLE'],
    'PT_INDUSTRY_APPROVAL_GROUP_DISABLE' => Xphp::$_lang['UI_INDUSTRY_APPROVAL_GROUP_DISABLE'],
    'PT_INDUSTRY_USER_GROUP_ADD' => Xphp::$_lang['UI_INDUSTRY_USER_GROUP_ADD'],
    'PT_INDUSTRY_USER_GROUP_LOOK' => Xphp::$_lang['UI_INDUSTRY_USER_GROUP_LOOK'],
    'PT_INDUSTRY_USER_GROUP_EDIT' => Xphp::$_lang['UI_INDUSTRY_USER_GROUP_EDIT'],
    'PT_INDUSTRY_USER_GROUP_DELETE' => Xphp::$_lang['UI_INDUSTRY_USER_GROUP_DELETE'],
    'PT_INDUSTRY_USER_GROUP_ENABLE' => Xphp::$_lang['UI_INDUSTRY_USER_GROUP_ENABLE'],
    'PT_INDUSTRY_USER_GROUP_DISABLE' => Xphp::$_lang['UI_INDUSTRY_USER_GROUP_DISABLE'],
    'PT_INDUSTRY_USER_ROLE_ADD' => Xphp::$_lang['UI_INDUSTRY_USER_ROLE_ADD'],
    'PT_INDUSTRY_USER_ROLE_LOOK' => Xphp::$_lang['UI_INDUSTRY_USER_ROLE_LOOK'],
    'PT_INDUSTRY_USER_ROLE_EDIT' => Xphp::$_lang['UI_INDUSTRY_USER_ROLE_EDIT'],
    'PT_INDUSTRY_USER_ROLE_DELETE' => Xphp::$_lang['UI_INDUSTRY_USER_ROLE_DELETE'],
    'PT_INDUSTRY_USER_ROLE_ENABLE' => Xphp::$_lang['UI_INDUSTRY_USER_ROLE_ENABLE'],
    'PT_INDUSTRY_USER_ROLE_DISABLE' => Xphp::$_lang['UI_INDUSTRY_USER_ROLE_DISABLE'],
    'PT_INDUSTRY_USER_ROLE_ALLOCATION' => Xphp::$_lang['UI_INDUSTRY_USER_ROLE_ALLOCATION'],
    'PT_INDUSTRY_USER_ROLE_ALLOCATIONS' => Xphp::$_lang['UI_INDUSTRY_USER_ROLE_ALLOCATIONS'],

    // Kubernetes
    'KUBE_CLUSTER_DESC_KEY_ADD_CLUSTER_SUCCESS' => Xphp::$_lang['WEB_LOG_KUBE_CLUSTER_DESC_KEY_ADD_CLUSTER_SUCCESS'],
    'KUBE_CLUSTER_DESC_KEY_ADD_CLUSTER_ERROR' => Xphp::$_lang['WEB_LOG_KUBE_CLUSTER_DESC_KEY_ADD_CLUSTER_ERROR'],
    'KUBE_CLUSTER_DESC_KEY_DELETE_CLUSTERS_SUCCESS' => Xphp::$_lang['WEB_LOG_KUBE_CLUSTER_DESC_KEY_DELETE_CLUSTERS_SUCCESS'],
    'KUBE_CLUSTER_DESC_KEY_DELETE_CLUSTERS_ERROR' => Xphp::$_lang['WEB_LOG_KUBE_CLUSTER_DESC_KEY_DELETE_CLUSTERS_ERROR'],

    // 存储同步
    // 时间点 '%s'的自描述文件不存在
    'BD_SYSTEMLOG_DESC_KEY_SELF_DESC_FILE_NOT_EXIST' => Xphp::$_lang['UI_BD_SYSTEMLOG_DESC_KEY_SELF_DESC_FILE_NOT_EXIST'],
    // 时间点 '%s'的自描述文件内容异常
    'BD_SYSTEMLOG_DESC_KEY_SELF_DESC_FILE_CONTENT_ABNORMAL' => Xphp::$_lang['UI_BD_SYSTEMLOG_DESC_KEY_SELF_DESC_FILE_CONTENT_ABNORMAL'],
    // 取消时间点 '%s'的删除标记失败
    'BD_SYSTEMLOG_DESC_KEY_UNSET_TIMEPOINT_DELETE_FLAG_ERROR' => Xphp::$_lang['UI_BD_SYSTEMLOG_DESC_KEY_UNSET_TIMEPOINT_DELETE_FLAG_ERROR'],
    // 更新时间点列表 [%s]的自描述文件为不可用状态失败
    'BD_SYSTEMLOG_DESC_KEY_UPDATE_TIMEPOINT_SELF_DESC_FILE_IS_UNAVAILABLE_ERROR' => Xphp::$_lang['UI_BD_SYSTEMLOG_DESC_KEY_UPDATE_TIMEPOINT_SELF_DESC_FILE_IS_UNAVAILABLE_ERROR'],
    // 更新时间点列表 [%s]的自描述文件为可用状态失败
    'BD_SYSTEMLOG_DESC_KEY_UPDATE_TIMEPOINT_SELF_DESC_FILE_IS_AVAILABLE_ERROR' => Xphp::$_lang['UI_BD_SYSTEMLOG_DESC_KEY_UPDATE_TIMEPOINT_SELF_DESC_FILE_IS_AVAILABLE_ERROR'],
    // 同步存储'%s'时间点信息失败
    'BD_SYSTEMLOG_DESC_KEY_SYNC_STORAGE_TIMEPOINTS_ERROR' => Xphp::$_lang['UI_BD_SYSTEMLOG_DESC_KEY_SYNC_STORAGE_TIMEPOINTS_ERROR'],
    // 同步存储'%s'时间点信息成功
    'BD_SYSTEMLOG_DESC_KEY_SYNC_STORAGE_TIMEPOINTS_SUCCESS' => Xphp::$_lang['UI_BD_SYSTEMLOG_DESC_KEY_SYNC_STORAGE_TIMEPOINTS_SUCCESS'],
    // 删除不可用的时间点'%s'
    'BD_SYSTEMLOG_DESC_KEY_DELETE_UNAVAILABLE_TIMEPOINT' => Xphp::$_lang['UI_BD_SYSTEMLOG_DESC_KEY_DELETE_UNAVAILABLE_TIMEPOINT'],

    // 备份数据管理
    'BD_SYSTEMLOG_DESC_KEY_DELETE_TIMEPOINT_ERROR' => Xphp::$_lang['WEB_LOG_SYSTEM_BD_SYSTEMLOG_DESC_KEY_DELETE_TIMEPOINT_ERROR'],
    'BD_SYSTEMLOG_DESC_KEY_ROLL_BACK_MERGE_ERROR' => Xphp::$_lang['WEB_LOG_SYSTEM_BD_SYSTEMLOG_DESC_KEY_ROLL_BACK_MERGE_ERROR'],
    'BD_SYSTEMLOG_DESC_KEY_DELETE_TIMEPOINT_IN_BATCH_ERROR' => Xphp::$_lang['WEB_LOG_SYSTEM_BD_SYSTEMLOG_DESC_KEY_DELETE_TIMEPOINT_IN_BATCH_ERROR'],
    'BD_SYSTEMLOG_DESC_KEY_TRANSPORT_GRAIN_FILE_ERROR' => Xphp::$_lang['WEB_LOG_SYSTEM_BD_SYSTEMLOG_DESC_KEY_TRANSPORT_GRAIN_FILE_ERROR'],
    'BD_TASK_DESC_KEY_UNLOCK_BACKUP_CHAIN_ERROR' => Xphp::$_lang['WEB_LOG_BD_TASK_DESC_KEY_UNLOCK_BACKUP_CHAIN_ERROR'], // 备份链解锁失败, 任务id: ’%s‘,时间点: ’%s‘
    'BD_TASK_DESC_KEY_LOCK_BACKUP_CHAIN_ERROR' => Xphp::$_lang['WEB_LOG_BD_TASK_DESC_KEY_LOCK_BACKUP_CHAIN_ERROR'], // 备份链加锁失败, 机器名: ’%s‘,时间点: ’%s‘
    'BD_SYSTEMLOG_DESC_KEY_SET_WORM_OF_TIMEPOINT' => Xphp::$_lang['WEB_LOG_BD_SYSTEMLOG_DESC_KEY_SET_WORM_OF_TIMEPOINT'], // 设置%s（模块）%s（备份模式）%s（时间点）worm成功，设置时间%s
    'BD_SYSTEMLOG_DESC_KEY_EXTEND_WORM_FOR_BACKUP_CHAIN' => Xphp::$_lang['WEB_LOG_BD_SYSTEMLOG_DESC_KEY_EXTEND_WORM_FOR_BACKUP_CHAIN'], // 延长%s（模块）%s（时间点）worm成功，延长时间%s
    'BD_SYSTEMLOG_DESC_KEY_VDP_NOT_RELOADED_ERROR' => Xphp::$_lang['WEB_LOG_BD_SYSTEMLOG_DESC_KEY_VDP_NOT_RELOADED_ERROR'], // VDP驱动程序未重新加载，节点: %s(%s)
);

?>