<?php
/**
 * 权限定义配置文件
 */
return array(
    //超级管理员,所有权限
    "administrator" => array(
        "homepage",
        "monitor",
            "task","current_job","history_job",
            "alarm","task_alarm","system_alarm",
            "log","job_log","system_log",
            "report","vm_report","storage_report", "job_report","server_report",
        "vmprotect",
            "vm_overview",
            "vmbackup",
            "vmrecover",
            "vminstantrecover",
            "vmrecovera",
            "vmdata",
        
        "vol_cdp_protect",  //卷CDP
            "vol_cdp_backup",
            "vol_cdp_recovery",
            "vol_cdp_takeover",
            "vol_cdp_backup_set",
        
        "dbtiming",
            "dbtbackup",
            "dbtrecovery",
            "dbtdata",
            "dbtagent",
            "dbtstorage",
            // "dbtlog",
        
        "dbprotect",
            "dbcdpbackup",
            "dbdataRecovery",
            "dbdata",
            "dbhost",
        "fileprotect",
            "filebackup",
            "filerecover",
            "filedata",
            "agent","agent_manager","my_agent",
        "datacopy",
            "vmcopy",
            "vmcopyback",
            "vmcopydata",
       "data_archive",
            "archive_add",
            "archive_back",
            "archive_data",
            "cloud_storage",
        "db_protect",
            "db_backup",
            "db_recovery",
            "db_agent_manager",
            "db_data_manager",
        "copy_protect",
            "copy",
            "copy_back",
            "copy_data",
        "orch",
            "orch_environment",
            "orch_plan",
            "orch_task",
            "orch_report",
        "resmanagement",
            "vcenter_manager",
            "appliance_manager",
            "node_manager",
            "storage_manager",
            "storage_lanfree",
            "global_strategy",
        "sysmanagement",
            "setting_manager",
//             "users",
            "safety",
            "authorization_module",
        //数据库实时
        "db_cdp_protect",
            "dbcdpcopy",
            "dbcdprecover",
            "dbcdpbackupData",
    ),
    
    //审计员
    "auditor" => array(
        "homepage",
        "monitor",
            "alarm","task_alarm","system_alarm",
            "log","job_log","system_log",
            "report","storage_report","vm_report", "job_report","server_report",
    ),
    
    
    
    //管理员
    "manager" => array(
        "homepage",
        "monitor",
            "task","current_job","history_job",
            "alarm","task_alarm","system_alarm",
            "log","job_log","system_log",
            "report","vm_report","storage_report", "job_report","server_report",
        "vmprotect",
            "vm_overview",
            "vmbackup",
            "vmrecover",
            "vminstantrecover",
            "vmrecovera",
            "vmdata",
        "dbtiming",
            "dbtbackup",
            "dbtrecovery",
            "dbtdata",
            "dbtagent",
            "dbtstorage",
            // "dbtlog",
        "dbprotect",
            "dbcdpbackup",
            "dbdataRecovery",
            "dbdata",
            "dbhost",
        "fileprotect",
            "filebackup",
            "filerecover",
            "filedata",
            "agent","agent_manager","my_agent",
        "datacopy",
            "vmcopy",
            "vmcopyback",
            "vmcopydata",
        "data_archive",
            "archive_add",
            "archive_back",
            "archive_data",
            "cloud_storage",
        "db_protect",
            "db_backup",
            "db_recovery",
            "db_agent_manager",
            "db_data_manager",
        "copy_protect",
            "copy",
            "copy_back",
            "copy_data",
        "orch",
            "orch_environment",
            "orch_plan",
            "orch_task",
            "orch_report",
        "resmanagement",
            "vcenter_manager",
            "appliance_manager",
            "node_manager",
            "storage_manager",
            "storage_lanfree",
            "global_strategy",
        "sysmanagement",
            "setting_manager",
//             "users",
            "safety",
            "authorization_module",
        "db_cdp_protect",
            "dbcdpcopy",
            "dbcdprecover",
            "dbcdpbackupData",
    ),
    
    //操作员
    "operator" => array(
        "homepage",
        "monitor",
            "task","current_job","history_job",
            "alarm","task_alarm","system_alarm",
            "log","job_log","system_log",
            "report","vm_report","storage_report", "job_report","server_report",
        "vmprotect",
            "vm_overview",
            "vmbackup",
            "vmrecover",
            "vminstantrecover",
            "vmrecovera",
            "vmdata",
        "dbtiming",
            "dbtbackup",
            "dbtrecovery",
            "dbtdata",
            "dbtagent",
            "dbtstorage",
            // "dbtlog",
        "dbprotect",
            "dbcdpbackup",
            "dbdataRecovery",
            "dbdata",
            "dbhost",
        "datacopy",
            "vmcopy",
            "vmcopyback",
            "vmcopydata",
        "data_archive",
            "archive_add",
            "archive_back",
            "archive_data",
            "cloud_storage",
        "db_protect",
            "db_backup",
            "db_recovery",
            "db_agent_manager",
            "db_data_manager",
    	"fileprotect",
    		"filebackup",
    		"filerecover",
    		"filedata",
    		"agent","my_agent",
        "copy_protect",
            "copy",
            "copy_back",
            "copy_data",
    	"orch",
    		"orch_environment",
    		"orch_plan",
    		"orch_task",
    		"orch_report",
        "resmanagement",
//             "vcenter_manager",
            "appliance_manager",
//             "node_manager",
//             "storage_manager",
//             "storage_lanfree",
            "global_strategy",
        "db_cdp_protect",
            "dbcdpcopy",
            "dbcdprecover",
            "dbcdpbackupData",
    ),
    
    //标准版admin用户权限
    "admin" => array(
        "homepage",
        "monitor",
            "task","current_job","history_job",
            "alarm","task_alarm","system_alarm",
            "log","job_log","system_log",
            "report","vm_report","storage_report", "job_report","server_report",
        "vmprotect",
            "vm_overview",
            "vmbackup",
            "vmrecover",
            "vminstantrecover",
            "vmdata",
        "resmanagement",
            "vcenter_manager",
            "appliance_manager",
            "node_manager",
            "storage_manager",
            "storage_lanfree",
            "global_strategy",
        "sysmanagement",
            "setting_manager",
            "authorization_module",
        "copy_protect",
            "copy",
            "copy_back",
            "copy_data",

    ),

);

